### ISSUE TITLE
BaiduEN8k Model Configuration

### ISSUE THREAD

**Issue by ryanleary** [PaddlePaddle/DeepSpeech#100]
I was wondering if you could document what configuration of the network was used for training the released baidu 8k model?

**Comment by pkuyym** [comment]
Please refer https://github.com/PaddlePaddle/DeepSpeech/blob/develop/examples/baidu_en8k/run_test_golden.sh

**Comment by kenyeung128** [comment]
@pkuyym what about the mandarin model? Do u have an example of it?

**Comment by pkuyym** [comment]
@kenyeung128 You mean the trained model? or example?
For example, please refer  https://github.com/PaddlePaddle/DeepSpeech/tree/develop/examples/aishell,
For downloading trained model, please refer https://github.com/PaddlePaddle/DeepSpeech#speech-model-released

**Comment by kenyeung128** [comment]
actually it's the BaiduCN1.2k Model, seems there are no example how to run it? I tried to get it up but failed. thanks

**Comment by pkuyym** [comment]
@kenyeung128 I see, you can unzipped the tar file and will find a REAME file, key configurations are listed in the file.

**Comment by ryanleary** [comment]
Does that include information on LR and momentum, etc?

**Comment by kuke** [comment]
This configuration mainly includes some structure parameters of the [network](https://github.com/PaddlePaddle/DeepSpeech/blob/develop/train.py). And about the training strategy,  you can refer to the [deep speech 2 paper](https://arxiv.org/abs/1512.02595).
