### ISSUE TITLE
关于librispeech的数据

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#101]
hi,以前我是使用你们发布的模型进行使用的，我注意到，librispeech的manifest是分类的，比如train分为manifest.train-clean-100,manifest.train-clean-360之类的。而train.py是使用manifest.train这个数据的，你们是把train的三种文件合一了吗？就是说，你们是使用librispeech的train-clean-100，train-clean-360，test-other三种数据共960小时的数据进行训练的吗？那么dev文件也是这样处理的吗？

**Comment by pkuyym** [comment]
是的，你可以参考
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/examples/librispeech/run_data.sh

**Comment by yyhlvdl** [comment]
好的，多谢。
