### ISSUE TITLE
Live Demo - how does it process real-time audio.

### ISSUE THREAD

**Issue by vucuong12** [PaddlePaddle/DeepSpeech#102]
I am wondering how the live demo works.
If I say "Today I am going to the supermarket to buy some beer", then does the live demo record the whole sentence then do the inference step (speech to text), or does it do that for smaller chunks (For example, "Today I am", then "going to the supermarket", and so on) ?

**Comment by yyhlvdl** [comment]
是的，的确是这样，就是你用麦克风说一句话，程序会把这个语音文件保存在一个目录(你可以自己设置)，然后程序会把识别结果打印出来。不过，有些细节需要注意：如果你在docker中运行程序，那么最好这样，sudo nvidia-docker run -it --net=host -v $(pwd)/DeepSpeech:/DeepSpeech paddlepaddle/deep_speech:latest-gpu /bin/bash
否则，客户端和服务器会连接不成功。当然，如果你不是在docker中使用，那就不需要这么麻烦了。

**Comment by vucuong12** [comment]
Thank you
