### ISSUE TITLE
寻求关于训练参数的建议

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#104]
@pkuyym 
你好，我最近想自己训练下模型，就是用librispeech的数据。因为硬件关系，我只好把batchsize改成16，不是你们最初的256了，那么epoch和迭代率等参数应该改成多少，可以给我一些建议吗？因为实验室硬件稀缺，我不好多次调整参数，只好麻烦你们了。

**Comment by pkuyym** [comment]
比较好奇，我们已经提供了librispeech的模型，这个不满足要求还是？

**Comment by yyhlvdl** [comment]
怎么说呢？我最近想搭建一个新的模型，当然基本都是deepspeech里面的层，所以我想看看自己的模型怎么样，所以想重新训练下。

**Comment by pkuyym** [comment]
OK，了解，学习率可以选用默认的，但是主要当loss不再下降的时候，要decay一下学习率，然后训练好的模型注意搜索alpha beta

**Comment by yyhlvdl** [comment]
那么epoch还是200吗，需要改变吗

**Comment by yyhlvdl** [comment]
@pkuyym 
不好意思，再次打扰了。我开始训练了。我使用的是4个gpu,最开始训练的时候，每个gpu占用的内存是2000m，然后在差不多半个小时后，每个gpu的内存占用到了5000m，这个内存泄露的问题，请问是我的代码问题还是paddle的问题，因为我看到也有人提出这个问题，请问有办法解决吗？

**Comment by pkuyym** [comment]
这个不一定是内存泄漏，第一个pass应该开启了sortagrad，样本是从短到长开始训练的，如果想确认是否显存够用，你可以训练一下最长的样本看看（一个batch）

**Comment by yyhlvdl** [comment]
好的

**Comment by yyhlvdl** [comment]
我尝试将max_duration从inf改为15，希望可以成功
