### ISSUE TITLE
询问一下关于硬件的信息

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#105]
@pkuyym
不好意思，再次打扰了。昨天，我开始训练，然而我只能让持续时间少于11s的librispeech的语音数据进入训练，这样的话，只有将近8万条语音进入训练，而不是你们使用的将近29万语音。我注意到，在readme中，你们是使用6-7s的语音来验证多gpu加速的性能。那么，可以告诉我，你们做librispeech的时候，使用的硬件的具体信息吗？最低配置就可以，因为实验室实在是没办法为我一个人就花费那么大的资金，更不可能去不断试不同的配置，只能向你们请求一下，我们可以一次性配置好。只要尽可能的让持续时间更长的语音数据进入训练，我就满足了，可以给我些建议吗？(深度学习果然首先是看硬件的)

**Comment by kuke** [comment]
@yyhlvdl librispeech这个model我们实际训练用的是8卡的K40m。如果你的硬件资源有限，只能尝试较小batch size的方式来用上所有的训练数据了。

**Comment by yyhlvdl** [comment]
...我的实验室是4块泰坦，每块12g内存，然后batch_size是1，还是跑不了27s的数据。你们的是8块，96g内存，但是是256的size,完全没理由啊。我再试试。

**Comment by yyhlvdl** [comment]
哦，我注意到是这样的，在我的batch_size为1的时候，4块gpu其中一块的内存被占用完了，而另外3块内存没有什么占用，请问可以解决这个问题吗？paddle好像有把数据分散的方式啊。

**Comment by pkuyym** [comment]
@yyhlvdl batch_size为1，没办法进行数据并行

**Comment by yyhlvdl** [comment]
@pkuyym 我明白你的意思，然而现在的情况是，持续时间为27s的语音数据它应该是只在一块gpu上运行，即使我将batch_size改为4，也并不意味着这个27s的数据会把它占用的内存分配到4块gpu上去。所以，我想咨询的是，有没有什么方法，可以将这个27s数据所占用的内存分散开来，而不是只使用一块内存。

**Comment by pkuyym** [comment]
@yyhlvdl 目前paddle应该是没有模型并行的，其实你完全可以把duration很长的音频过滤掉

**Comment by yyhlvdl** [comment]
@pkuyym 是的，我设置为11s可以。然而，这样实际进入训练的只有8万多的数据了。我感觉效果可能不是很好，所以才一直想尽可能让更多的数据可以进行训练。多谢你的回复。
