### ISSUE TITLE
PaddlePaddle新年大礼！周边产品送不停！

### ISSUE THREAD

**Issue by angelashane** [PaddlePaddle/DeepSpeech#107]
各位亲爱的PaddlePaddle用户：

2017年已经过去，感谢你们一直陪伴PaddlePaddle在深度学习领域共同成长，无论是应用、贡献、还是review、纠错；每一个人的付出对于PaddlePaddle都是至关重要的。**值此新年，PaddlePaddle准备了一批周边小礼物赠送给各位，与各位一同迎接更好的2018！PaddlePaddle，一起加油！**

**周边礼物领取方式如下：**
请各位使用者、贡献者将**如下信息**发到PaddlePaddle-TechWriter@baidu.com
**【“姓名“+“github账号名” +“周边礼物快递邮寄地址”+”快递联系电话“+”定制卫衣号码（S：160，M：165，L：170，XL：175，xxL：180）“】** →发到PaddlePaddle-TechWriter@baidu.com
我们会根据邮件中的地址为您送上PaddlePaddle周边礼物一份。
您也可以同时回复此issue-”你对PaddlePaddle的祝福和嘱咐“或“PaddlePaddle，一起加油！”来提醒我们查收您的邮件。

# 礼物内容如下：
每位发送邮件的用户都能获得PaddlePaddle**礼袋一个，内置“LOGO卫衣+贴纸+纪念小徽章“**

![image](https://user-images.githubusercontent.com/27677185/34556980-9ed91f42-f173-11e7-974c-e0db65314868.png)

# 重要贡献用户随机加发下列周边产品之一：
## PaddlePaddle定制款-膳魔师保温水杯

![image](https://user-images.githubusercontent.com/27677185/34556983-a3bcbed8-f173-11e7-9c0c-7fe35348b0c7.png)

## PaddlePaddle定制款-机械键盘

![image](https://user-images.githubusercontent.com/27677185/34556989-a9dc7c4a-f173-11e7-80d0-5af5ec9f2a20.png)

## PaddlePaddle定制款-树莓派

![image](https://user-images.githubusercontent.com/27677185/34557019-d4f113e6-f173-11e7-9489-265ac6ba207b.png)

# 如有其他疑问，可以直接回复本issue~~感谢大家的支持！

**Comment by fedoral** [comment]
已发送 赞~~ PaddlePaddle 越来越好

**Comment by witkeyshare** [comment]
最近在研究使用百度一系列的AI产品，很不错。还是百度给力啊，祝越来越好

**Comment by wanghaolw** [comment]
PaddlePaddle，一起加油！

**Comment by ddx27527** [comment]
PaddlePaddle，2018,一起加油！

**Comment by qianlongchen** [comment]
PaddlePaddle，2018,一起加油！

**Comment by Des-yangzi** [comment]
新年新气象，祝愿2018，PaddlePaddle 我们一起加油！
