### ISSUE TITLE
Failed to download Mandarin LM

### ISSUE THREAD

**Issue by misbullah** [PaddlePaddle/DeepSpeech#111]
Hi,

I tried to download the Mandarin LM from the following link:

Small: http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e 
Larger: http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37

But, it failed. I tried it many times from different network.

In the beginning, it can download well, but it will be stopped after a while or some MB of size. It always happened like that.
 
Do you have any suggestion?

Thanks,
Alim

**Comment by yyhlvdl** [comment]
Seems our DNS forwarding limits the download, you can set /etc/hosts file mannually adding:

180.76.189.142  cloud.dlnel.org
and try download again.

I suggest that you can read other issues,because your ploblems may happen on others,and maybe have been solved by oyhers

**Comment by misbullah** [comment]
Hi @yyhlvdl,

Thanks a lot for your reply.

I tried to read other issues actually, but I just focus on title of issues.

Next time, I will read them in detail.

Thanks,
Alim

**Comment by kuke** [comment]
Thanks to @yyhlvdl

**Comment by BookGin** [comment]
Thanks to @yyhlvdl :)
