### ISSUE TITLE
无法安装，一直提示ImportError: No module named swig_decoders

### ISSUE THREAD

**Issue by uuid128** [PaddlePaddle/DeepSpeech#113]
import swig_decoders
后，一直提示
ImportError: No module named swig_decoders

也没有说具体的原因

**Comment by kuke** [comment]
这是因为decoder没有安装成功，你可以cd到decoders目录下，单独运行`setup.sh`脚本，安装decoder

**Comment by gdfspy** [comment]
不用docker运行paddle，基本难成功

**Comment by harold-yh** [comment]
DeepSpeech根目录下运行sh setup.sh也可以。

**Comment by fantasyoooo** [comment]
@kuke @harold-yh 
你好
按你们说的运行了setup.sh
root@amax-SYS-7048GR-TR:/data/DeepSpeech/decoders# sh setup.sh
Install all dependencies successfully.
run_train.sh的时候还是出现了错误
root@amax-SYS-7048GR-TR:/data/DeepSpeech/examples/tiny# sh run_train.sh
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model_utils.model import DeepSpeech2Model
  File "/data/DeepSpeech/model_utils/model.py", line 15, in <module>
    from decoders.swig_wrapper import Scorer
  File "/data/DeepSpeech/decoders/swig_wrapper.py", line 6, in <module>
    import swig_decoders
ImportError: No module named swig_decoders
Fail in training!
0.0

**Comment by fantasyoooo** [comment]
@kuke @harold-yh 
你好
按你们说的运行了setup.sh
root@amax-SYS-7048GR-TR:/data/DeepSpeech/decoders# sh setup.sh
Install all dependencies successfully.

run_train.sh的时候还是出现了错误
root@amax-SYS-7048GR-TR:/data/DeepSpeech/examples/tiny# sh run_train.sh
Traceback (most recent call last):
File "train.py", line 9, in
from model_utils.model import DeepSpeech2Model
File "/data/DeepSpeech/model_utils/model.py", line 15, in
from decoders.swig_wrapper import Scorer
File "/data/DeepSpeech/decoders/swig_wrapper.py", line 6, in
import swig_decoders
ImportError: No module named swig_decoders
Fail in training!
0.0

**Comment by fantasyoooo** [comment]
@kuke @harold-yh 
我用pip安装了一下,发现是有swig_decoders的..

Requirement already satisfied: swig_decoders in /home/amax/anaconda2/lib/python2.7/site-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg

**Comment by fantasyoooo** [comment]
@kuke @harold-yh 
安装了下面这个再试还是不行..
root@amax-SYS-7048GR-TR:~/anaconda2/lib/python2.7/site-packages# easy_install swig_decoders-1.1-py2.7-linux-x86_64.egg
Processing swig_decoders-1.1-py2.7-linux-x86_64.egg
Copying swig_decoders-1.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
Adding swig-decoders 1.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg
Processing dependencies for swig-decoders==1.1
Finished processing dependencies for swig-decoders==1.1

**Comment by beyondboy** [comment]
@fantasyoooo  have you solved this problem? i encounter the same problem

**Comment by fantasyoooo** [comment]
@beyondboy 
nope..
The author recommended to use docker，so i use docker instead pip . 
The problem has disappeared

**Comment by loongw** [comment]
```
brew install boost
brew install swig
```
then goto `decoders/swig` and run:
```
sh setup.sh
```

**Comment by bolt163** [comment]
同踩坑，这个问题除了在docker里运行能规避，就没有更优雅一点的解决方式吗

**Comment by seiriosPlus** [comment]
1. build and install swig by source 3.0.12
cd swig
./autogen.sh
./configure
make
make install

2. entry decoders/swig， rerun setup.sh

**Comment by Kaijien** [comment]
seiriosPlus 正解，将swig更新至3.0.12，就可以比安装了

**Comment by Kaijien** [comment]
seiriosPlus 正解，将swig更新至3.0.12，就可以安装了

**Comment by sunjunlishi** [comment]
我是ubuntu下载3.0.12 ./configure make make install.
还是那样的错误，biadu没有解决这个问题吗，还是我们比较笨啊。

**Comment by OttoOu** [comment]
cd decoders/swig
sh setup.sh

**Comment by zyb8543d** [comment]
> 1. build and install swig by source 3.0.12
>    cd swig
>    ./autogen.sh
>    ./configure
>    make
>    make install
> 2. entry decoders/swig， rerun setup.sh

follow it,sloved, thanks
