### ISSUE TITLE
试了en8k，识别率真不错！但有个问题...

### ISSUE THREAD

**Issue by gdfspy** [PaddlePaddle/DeepSpeech#115]
params.tar.gz能继续训练其它语音数据吗？还是要等DeepSpeech3？

**Comment by kuke** [comment]
@gdfspy 可以用params.tar.gz恢复训练，但不能保证识别率能有进一步的提升，原因主要有两个：一是en8k模型已经充分训练；二是其它语音数据和我们的训练数据分布不同，效果难以预计。关于语音识别，我们还有后续计划，但暂时还不能给出明确的时间线。

**Comment by gdfspy** [comment]
谢谢 kuke
