### ISSUE TITLE
demo_server用cn 1.2k推荐什么配置？

### ISSUE THREAD

**Issue by gdfspy** [PaddlePaddle/DeepSpeech#116]
我用虚拟机 8G内存，预热那个步骤就非常慢，要10几分钟，还识别不出任何内容，是内存少吗？

**Comment by pkuyym** [comment]
@gdfspy 有几个点需要注意一下：
1. cn 1.2K的音频频率为8k，demo默认的是16k，需要改动：https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_client.py#L77 和 https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_server.py#L118
2. 请设置cutoff_prob小于1.0，比如0.99

**Comment by gdfspy** [comment]
谢谢，现在识别率很高了。
LM用2.8G的速度快，70G的准确度高。
但我用70G的LM要100多秒，2.8G的则1秒之内识别出来，正常吗？

**Comment by pkuyym** [comment]
@gdfspy 不太正常，理论上LM加在进去后，query时间的差别没这么大，请查看加载70G的LM后，是否用到了swap分区，这个有可能拖慢速度

**Comment by gdfspy** [comment]
Mem:  Total 7975, used 4026, free 126
swap   Total 4095. used 551, free 3544

**Comment by pkuyym** [comment]
@gdfspy 信息比较少，不太确定是否是swap引起的

**Comment by gdfspy** [comment]
我用cat /proc/swaps查看运行前后的差别：
/dev/dm-1   size 4194300  used 377528
/dev/dm-1   size 4194300  used 753736

**Comment by pkuyym** [comment]
@gdfspy 可以做一下profile，看运行热点在哪？

**Comment by fangmingbnu** [comment]
@pkuyym @gdfspy 请教一下，我用mac去跑demo_server. 我的demo_server是可以跑出来，运行效果如下：
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0913/BAC009S0913W0364.wav')
Response Time: 3.273213, Transcript: 邀请专家学者等三十馀人组成志愿者培训导师
('Warm-up Test Case %d: %s', 1, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0912/BAC009S0912W0384.wav')
Response Time: 1.695054, Transcript: 冰雪爱好者不得不选择出国
('Warm-up Test Case %d: %s', 2, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0902/BAC009S0902W0467.wav')
Response Time: 1.467976, Transcript: 黄色渣土车一头撞进了路边的攻防
-----------------------------------------------------------
ASR Server Started.
但是我的demo_client.py不知道有没有运行成功，我输入python -u deploy/demo_client.py --host_ip 'localhost'  --host_port 8086， 也没有报错。只是没有翻译，我按空格键，他就出现空格，并没有录音，按“esc"键也不会退出。同时server端没有任何输出。我是在同一台机子上跑的，不知道有什么问题，请假一下，谢谢！

**Comment by gdfspy** [comment]
应该是客户端的问题，那段录音代码在你本机运行有些问题，建议用pycharm调试一下，看看pyaudio运行有没有出错。
我这边按住空格能正常录音。





在 2018-04-04 09:32:21，"Ming Fang, Ph.D." <notifications@github.com> 写道：

@pkuyym@gdfspy 请教一下，我用mac去跑demo_server. 我的demo_server是可以跑出来，运行效果如下：
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0913/BAC009S0913W0364.wav')
Response Time: 3.273213, Transcript: 邀请专家学者等三十馀人组成志愿者培训导师
('Warm-up Test Case %d: %s', 1, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0912/BAC009S0912W0384.wav')
Response Time: 1.695054, Transcript: 冰雪爱好者不得不选择出国
('Warm-up Test Case %d: %s', 2, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0902/BAC009S0902W0467.wav')
Response Time: 1.467976, Transcript: 黄色渣土车一头撞进了路边的攻防

ASR Server Started.
但是我的demo_client.py不知道有没有运行成功，我输入python -u deploy/demo_client.py --host_ip 'localhost' --host_port 8086， 也没有报错。只是没有翻译，我按空格键，他就出现空格，并没有录音，按“esc"键也不会退出。同时server端没有任何输出。我是在同一台机子上跑的，不知道有什么问题，请假一下，谢谢！

**Comment by Ckj409399** [comment]
@gdfspy 你好，方便交流一下该程序的运行问题吗，小白刚入门现在用cn 1.2k运行报错，希望能指导一下。QQ：409399732

**Comment by sunjunlishi** [comment]
正确率提高了，到底怎样啊。我的按照说明改了，效果不对啊。@gdfspy

**Comment by dxhgq-github** [comment]
现在用70G的LM，识别一句话要好几分钟，请问运行70G的LM ，需要多少G的内存？

**Comment by dxhgq-github** [comment]
请问一下，使用70G具体做少需要多大的内存，感觉太慢了。

**Comment by ccbptm** [comment]
> 应该是客户端的问题，那段录音代码在你本机运行有些问题，建议用pycharm调试一下，看看pyaudio运行有没有出错。 我这边按住空格能正常录音。 在 2018-04-04 09:32:21，"Ming Fang, Ph.D." <notifications@github.com> 写道： @pkuyym@gdfspy 请教一下，我用mac去跑demo_server. 我的demo_server是可以跑出来，运行效果如下： Warming up ... ('Warm-up Test Case %d: %s', 0, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0913/BAC009S0913W0364.wav') Response Time: 3.273213, Transcript: 邀请专家学者等三十馀人组成志愿者培训导师 ('Warm-up Test Case %d: %s', 1, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0912/BAC009S0912W0384.wav') Response Time: 1.695054, Transcript: 冰雪爱好者不得不选择出国 ('Warm-up Test Case %d: %s', 2, u'/Users/Desktop/DeepSpeech/data/aishell/wav/test/S0902/BAC009S0902W0467.wav') Response Time: 1.467976, Transcript: 黄色渣土车一头撞进了路边的攻防 ASR Server Started. 但是我的demo_client.py不知道有没有运行成功，我输入python -u deploy/demo_client.py --host_ip 'localhost' --host_port 8086， 也没有报错。只是没有翻译，我按空格键，他就出现空格，并没有录音，按“esc"键也不会退出。同时server端没有任何输出。我是在同一台机子上跑的，不知道有什么问题，请假一下，谢谢！ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

你好，我想问下怎么用aishell的测试集去测试baidu cn 1.2k的模型效果啊
