### ISSUE TITLE
tools/tune.py感觉没有根据最新的data.py进行更新

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#117]
在我用tune.py进行调节参数的时候，出现这样的错误：KeyError: u'sequence_offset'，于是我就自己修改了文件，运行。这里提醒一下这个bug,当然，也可能是我自己修改了太多东西，很可能哪里不协调，而官网的本来是协调的。

**Comment by kuke** [comment]
Thx. I will fix it later
