### ISSUE TITLE
Mandarin LM  query speed is very slow

### ISSUE THREAD

**Issue by zhaoningning** [PaddlePaddle/DeepSpeech#119]
I have tried the chinese language Model (zh_giga.no_cna_cmn.prune01244.klm) in decoding process,but the speed is very slow,nearly 2 seconds per sample, how can i speed this?

**Comment by pkuyym** [comment]
@zhaoningning hi, could you offer more details? How did you evaluate the querying speed ?

**Comment by zhaoningning** [comment]
Thanks for you reply!  I measured  the CTC beam search decoding time,and it's nearly 2 sec per sample,is that true?

**Comment by kuke** [comment]
@zhaoningning Yes. The speed should be reasonable.
