### ISSUE TITLE
Missing num_conv_layers in data_generator (tune.py)

### ISSUE THREAD

**Issue by misbullah** [PaddlePaddle/DeepSpeech#120]
Hi,

I found that there is an issue in tune.py when call DataGenerator function as shown in below.

    data_generator = DataGenerator(
        vocab_filepath=args.vocab_path,
        mean_std_filepath=args.mean_std_path,
        augmentation_config='{}',
        specgram_type=args.specgram_type,
        num_threads=args.num_proc_data,
        keep_transcription_text=True,
        num_conv_layers=args.num_conv_layers)

There is no argument for num_conv_layers in DataGenerator (data_utils/data.py)

Thanks,
Alim

**Comment by kuke** [comment]
This problem will be fixed by #122
