### ISSUE TITLE
inference in real time

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#124]
There is any plans to publish a real time streaming code that performs like google api?
Do you think I will able to use the pertained model and execute inference fast enough? 

Thanks!

**Comment by yyhlvdl** [comment]
百度的官方有这种API吧，只需要调用之类的。

**Comment by alanbekker** [comment]
do you have a link?

**Comment by yyhlvdl** [comment]
I do not use.maybe this http://ai.baidu.com/docs#/ASR-Android-SDK/top

**Comment by alanbekker** [comment]
could you please elaborate it a bit more in case I'll do it by myself.

Thanks!

**Comment by kuke** [comment]
@alanbekker As mentioned in the [deep speech 2 paper](https://arxiv.org/pdf/1512.02595.pdf), the row convolution layer can be used to replace the bidirectional RNN layer for streaming decoding. [Row convolution layer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L6611) has been supported in PaddlePaddle, you can have a try if you like.

**Comment by alanbekker** [comment]
Do you know if Baidu released the Row convolutional layer based pertained
model?

**Comment by kuke** [comment]
@alanbekker As far as I know, almost no other teams released well-trained models like what what we did. But many APIs provided by Baidu should support streaming decoding.

**Comment by Slyne** [comment]
Is the current decoder applicable for online decoding?
Could you give some hints about how to change it?
