### ISSUE TITLE
用docker编译paddlepaddle出错..

### ISSUE THREAD

**Issue by fantasyoooo** [PaddlePaddle/DeepSpeech#125]
用docker编译paddlepaddle出错..
错误是
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[ERROR]	Update failed for google.golang.org/grpc: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
.
.
.
[ 63%] Linking CXX static library libexpand_op.a
cpplint: Checking source code style
Done processing expand_op.cc
Done processing expand_op.cu
Done processing /paddle/paddle/operators/expand_op.h
Total errors found: 0
[ 63%] Built target expand_op
make: *** [all] Error 2
Makefile:160: recipe for target 'all' failed

**Comment by pkuyym** [comment]
如果是编译PaddlePaddle的问题，建议在这里https://github.com/PaddlePaddle/Paddle/issues提issue

**Comment by fantasyoooo** [comment]
@pkuyym 
链接打不开..

**Comment by fantasyoooo** [comment]
@pkuyym 好的
