### ISSUE TITLE
感谢，如果用DeepSpeech做孤立词识别，有没有比较好的建议，从数据准备到模型训练等

### ISSUE THREAD

**Issue by wanghaolw** [PaddlePaddle/DeepSpeech#126]
感谢百度对开源所作的贡献，我们现在尝试在做孤立词识别，用过CMU、HTK、Kaldi，也用过DNN等算法模型，都是自己准备数据，自己训练模型，但是效果却不是很理想，貌似现在的平台更擅长做连续语音识别，当然我们目前的研究依然十分浅薄，望能指点一二，谢谢！

**Comment by kuke** [comment]
@wanghaolw 我们的工作也没有涉及到孤立词识别，所以很难给出专业性的建议。建议你关注一下最新的研究工作， 看能否得到启发。

**Comment by wanghaolw** [comment]
好的，谢谢，我们再研究研究

**Comment by zhouyikang** [comment]
用tensorflow的 speechcommand 看看
