### ISSUE TITLE
Context window width-  feed forward question

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#128]
Let's assume my audio segment consists of 8000 samples at 16khz (0.5sec)
In the preprocessing stage using a sliding window of 20msec and stride of 10msec I receive 50 different spectrograms..you can reach this number by yourself (500msec/10msec=50)

When I run prediction I can see that the softmax output consist of 17 distribution vectors.

Why 17? I assume this is a result of context window width of +-1 (and then 50/3=~17), but I have no reference that the context width indeed is +-1..can someone correct point out a reference for this or correct me?

Thanks in advance!

**Comment by pkuyym** [comment]
Configuration of the 1st conv layer is:
* kernel_size (11, 41)
* stride_size (3, 2)
* padding_size (5, 2)

For the time length, we can do the math to get the reduced length: (original_length + 2 * padding_size - filter_size) / stride_size + 1. In your case, the length will be reduced to (50 + 2 * 5 - 11)/3 + 1=17.
