### ISSUE TITLE
demo server error -  ValueError: No such parameter ___recurrent_layer_0__.w0

### ISSUE THREAD

**Issue by lightsailpro** [PaddlePaddle/DeepSpeech#130]
I got this error when running CUDA_VISIBLE_DEVICES=0 python deploy/demo_server.py with baidu_en8k. Here is command output. Could someone help?

ml@tesla1a:~/Paddle/DeepSpeech$ CUDA_VISIBLE_DEVICES=0 python deploy/demo_server.py
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: models/baidu_en8k/mean_std.npz
model_path: models/baidu_en8k/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: False
vocab_path: models/baidu_en8k/vocab.txt
warmup_manifest: data/librispeech/manifest.test-clean
------------------------------------------------
I0119 13:57:54.665096 60035 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1
[INFO 2018-01-19 13:57:59,480 layers.py:2714] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-19 13:57:59,482 layers.py:3282] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-19 13:57:59,483 layers.py:7454] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-19 13:57:59,484 layers.py:2714] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-01-19 13:57:59,485 layers.py:3282] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-01-19 13:57:59,486 layers.py:7454] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-01-19 13:58:04,793 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-01-19 13:58:17,973 model.py:253] language model: is_character_based = 0, max_order = 5, dict_size = 400000
[INFO 2018-01-19 13:58:18,154 model.py:254] end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/home/ml/.cache/paddle/dataset/speech/libri/test-clean/LibriSpeech/test-clean/7176/92135/7176-92135-0025.flac')
Traceback (most recent call last):
  File "deploy/demo_server.py", line 217, in <module>
    main()
  File "deploy/demo_server.py", line 213, in main
    start_server()
  File "deploy/demo_server.py", line 196, in start_server
    num_test_cases=3)
  File "deploy/demo_server.py", line 135, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "deploy/demo_server.py", line 171, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/home/ml/Paddle/DeepSpeech/deploy/../model_utils/model.py", line 193, in infer_batch_probs
    output_layer=self._log_probs, parameters=self._parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 63, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___recurrent_layer_0__.w0

**Comment by yyhlvdl** [comment]
share_rnn_weights: True设置为False试试，也许这个模型使用的是gru

**Comment by lightsailpro** [comment]
Thanks.  Setting use_gru=True worked.

**Comment by lightsailpro** [comment]
The issue is resolved.

**Comment by 18811737901** [comment]
> The issue is resolved.

How do I solve this problem?

**Comment by 18811737901** [comment]
> The issue is resolved.
Can tell me how to solve this problem?Thanks.
