### ISSUE TITLE
log10(0) in rms_db(self)

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#131]
in data_utils/audio.py  the method self.rms_db() computes:
 mean_square = np.mean(self._samples**2)
 return 10 * np.log10(mean_square)

and at inference time in on elf my utterances: self._samples is a vector of zeros therefore the np.log10(mean_square)
obviously cause a core dump..any ideas how to treat this?

1.This makes sense receiving self._samples is a vector of zeros?
2. which epsilon do you recommend to add in order to avoid this in  np.log10(mean_square+epsilon) and not harm the preprocessing stage?

**Comment by pkuyym** [comment]
@alanbekker

> 1.This makes sense receiving self._samples is a vector of zeros?

It seems that `self._samples` being all zeros is not a common situation, I'm a little curious that in which situation `self._samples` would be all zeros. 

> 2.  which epsilon do you recommend to add in order to avoid this in np.log10(mean_square+epsilon) and not harm the preprocessing stage?

For avoiding the numeric problem, I think set `epsilon` to be any small enough number like `1e-9` or `1e-6` will work.

**Comment by alanbekker** [comment]
I think the user is pressing mute during the recording
