### ISSUE TITLE
incorporate hints in the decoding phase

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#132]
I'm trying to implement hints in the decoding phase..any ideas or suggestions how to implement this?

Thanks!

**Comment by kuke** [comment]
@alanbekker Could you please provide more details?

**Comment by alanbekker** [comment]
Assume you have a prior knowledge about a set of words the user might use
in a specific audio segment..I would like to incorporate this information
in the beam search in order to increase the recognition performance..

**Comment by kuke** [comment]
@alanbekker Sorry for the late reply. DeepSpeech2 uses this formula to rank the decoding result
<img width="809" alt="2018-01-25 6 15 57" src="https://user-images.githubusercontent.com/3064195/35383008-fee40d28-01fb-11e8-8a3e-c78784680fbf.png">
A simple and direct approach is to add a term to this formula incorporating the prior information, such as an indicator or the appearance frequency, then retune the hyper-parameters similar to the way in README.

FYR

**Comment by alanbekker** [comment]
Assume a hint( set of words a user may use) is provided to me in real time
and I hav not enough time to build a LM with them..what wold be your
approach in that case?

Thanks!

Alan
