### ISSUE TITLE
maximum length of audio clip that can be transcribed using en8k model

### ISSUE THREAD

**Issue by lightsailpro** [PaddlePaddle/DeepSpeech#133]
I tested the en8k model using the demo server. For longer audio clips e.g. 28 seconds of wave file, it seems that only last 10 seconds or so of the wave file got transcribed. The 1st 18 seconds just got discarded. Does anyone know why?

**Comment by kuke** [comment]
This model should be able to transcribe the whole audio file. Please check whether audio is recorded correctly in the first 18s.

**Comment by viig99** [comment]
Can you let us know whats the maximum that can be done ?
