### ISSUE TITLE
changing the ctc_beam_search_decoder.cpp function

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#135]
I wonder maybe you have a main.cpp function which you used to debug ctc_beam_search_decoder.cpp function.

I would like to change thectc_beam_search_decoder.cpp and need ability to debug the changes with breakpoint...any ideas how to do so?

**Comment by kuke** [comment]
@alanbekker  We'd never used a main.cpp for debugging, usually a python wrapper is enough and more friendly. If you want you can implement a simple one, just set ```ext_scorer``` to ```null``` and generate some random matrices as the input.

**Comment by alanbekker** [comment]
I want to be able to stop with a breakpoint inside the modified cpp
function, how can I do that using the python wrapper?


Thanks!
