### ISSUE TITLE
Floating point exception in ctc_beam_search_decoder

### ISSUE THREAD

**Issue by neozhangthe1** [PaddlePaddle/DeepSpeech#136]
Error in 
https://github.com/PaddlePaddle/DeepSpeech/blob/edaed68f33b7fff2455c26b880340ba680621f5c/decoders/swig/ctc_beam_search_decoder.cpp#L137
when decoding using beam search. 

[INFO 2018-01-24 14:29:35,342 model.py:244] begin to initialize the external scorer for decoding
[INFO 2018-01-24 14:29:35,439 model.py:255] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2018-01-24 14:29:35,439 model.py:256] end initializing scorer. Start decoding ...
*** Aborted at 1516804178 (unix time) try "date -d @1516804178" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fe13bdd2f36) received by PID 8361 (TID 0x7fe12114b700) from PID 1004351286; stack trace: ***
    @     0x7fe16d7e4390 (unknown)
    @     0x7fe13bdd2f36 PathTrie::iterate_to_vec()
    @     0x7fe13bdd2ed8 PathTrie::iterate_to_vec()
    @     0x7fe13bdc8992 ctc_beam_search_decoder()
    @     0x7fe13bdc9bd7 std::_Function_handler<>::_M_invoke()
    @     0x7fe13bdc9589 std::__future_base::_State_baseV2::_M_do_set()
    @     0x7fe16d7e1a99 __pthread_once_slow
    @     0x7fe13bdc98ef std::__future_base::_Task_state<>::_M_run()
    @     0x7fe13bdcac11 _ZNSt6thread5_ImplISt12_Bind_simpleIFZN10ThreadPoolC4EmEUlvE_vEEE6_M_runEv
    @     0x7fe14b51ac80 (unknown)
    @     0x7fe16d7da6ba start_thread
    @     0x7fe16d5103dd clone
    @                0x0 (unknown)

Floating point exception (core dumped)

The model is trained on an internal mandarin speech dataset.

trainer_count = 1
beam_size = 500
num_proc_bsearch = 8
num_proc_data = 8
num_conv_layers = 2
num_rnn_layers = 3
rnn_layer_size = 2048
alpha = 1.0
beta = 2.329
cutoff_prob = 1.0
cutoff_top_n = 40
use_gru = True
use_gpu = True
share_rnn_weights = False
lang_model_path = '/mnt/models/lm/zh_giga.no_cna_cmn.prune01244.klm'
decoding_method = 'ctc_beam_search'
error_rate_type = 'cer'
specgram_type = 'linear'

**Comment by kuke** [comment]
@neozhangthe1 Sorry we cannot reproduce your error. Does it work if using the provided Mandarin model?

**Comment by fancyerii** [comment]
I came across the same problem when running run_train.sh in examples/aishell
