### ISSUE TITLE
Floaing point exception in demo_server.py

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#141]
warmup_manifest: ../models/baidu_en8k/manifest.test-clean
------------------------------------------------
-----------------------------------------------------------
Warming up ...
-----------------------------------------------------------
ASR Server Started.
Received utterance[length=61440] from 14.143.40.242, saved to demo_cache/20180129074345_14.143.40.242.wav.
Response Time: 10.588990, Transcript:
Received utterance[length=196608] from 14.143.40.242, saved to demo_cache/20180129074401_14.143.40.242.wav.
*** Aborted at 1517211841 (unix time) try "date -d @1517211841" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f407961fbc3) received by PID 29663 (TID 0x7f407a70a700) from PID 2036464579; stack trace: ***
    @     0x7f407a2ed390 (unknown)
    @     0x7f407961fbc3 log10f
    @     0x7f406c7843a5 PyUFunc_f_f
    @     0x7f406c8817dc trivial_two_operand_loop
    @     0x7f406c889ec4 PyUFunc_GenericFunction
    @     0x7f406c88a585 ufunc_generic_call
    @           0x4b0c93 PyObject_Call
    @           0x4c9f9f PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4de69e (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4b0901 PyObject_CallFunction
    @           0x4b01bc _PyObject_GenericGetAttrWithDict
    @           0x4c442c PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4ca088 PyEval_EvalFrameEx
@           0x4c2705 PyEval_EvalCodeEx
    @           0x4ca088 PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4ca7df PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4ca7df PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4ca7df PyEval_EvalFrameEx
    @           0x4c9d7f PyEval_EvalFrameEx
    @           0x4c2705 PyEval_EvalCodeEx
    @           0x4de69e (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4f452e (unknown)
    @           0x4b0c93 PyObject_Call
    @           0x4ce540 PyEval_CallObjectWithKeywords
    @           0x4e15b4 PyInstance_New

**Comment by pkuyym** [comment]
Is it normal for recognition of warmup_manifest?

**Comment by cogmeta** [comment]
It is inconsistent. It does not happen always. May be external (memory) issue.

**Comment by philiptzou** [comment]
@cogmeta Check my fix.
