### ISSUE TITLE
GPU memory leak with demo_server and demo_client?

### ISSUE THREAD

**Issue by lightsailpro** [PaddlePaddle/DeepSpeech#142]
I am testing the demo_server and demo_client with the en8k model. I noticed that the GPU (K40c with 12G ram) ram consumption kept increasing with each use of then client. Is this normal? I worry that GPU will run out ram after certain amount of calls.

**Comment by kuke** [comment]
@lightsailpro A little increase in GPU memory may be normal during decoding. Have you ever encountered out of memory problem?

**Comment by lightsailpro** [comment]
Thanks for the explanation. Tested with a few hundreds of calls. The RAM consumption seems fine, fluctuating around 1GB. Closed the issue.
