### ISSUE TITLE
can I enlarge the size of characters in the vocab.txt of the existing model?

### ISSUE THREAD

**Issue by onlywordding** [PaddlePaddle/DeepSpeech#147]
I have tried  to use BaiduCN1.2k Model as initial  model to train model using Aishell Dataset(already coverted to 8k) , but there are some characters which are not included in the vocab.txt. I wonder how to enlarge the size of characters.

**Comment by pkuyym** [comment]
You can do fine tune in your own dataset.

**Comment by onlywordding** [comment]
好的，谢谢！
