### ISSUE TITLE
Do I need to create my own Language Model if I generate a ASR model?

### ISSUE THREAD

**Issue by PHDZheng** [PaddlePaddle/DeepSpeech#151]
I used a data with 8000 Mandarin characters  to train a the DeepSpeech model. I wonder if I need to generate an own Language Model based on the data, or I can still use the baidu released Language Model?

I also want to know what is the relationship between the 'vocab.txt' of the  DeepSpeech model and the Language Model?

**Comment by kuke** [comment]
@PHDZheng It is not necessary to build your own language model. The language model can be general and independent from the training data of the acoustic model. But if you have abundant data, you can build a more powerful one if you like.

Usually, the vocabulary is generated from the training data of the acoustic model, consisting of almost all the words or characters appeared. That is to say, it has no direct relationship with the language model.

**Comment by PHDZheng** [comment]
thanks
