### ISSUE TITLE
Is it possible to train from features file (MFCC) not wave files

### ISSUE THREAD

**Issue by misbullah** [PaddlePaddle/DeepSpeech#158]
Hi,

How to train the model in DeepSpeech if I only have the MFCC features from Kaldi Toolkit format?
Is it possible?

I can make the MFCC features to be readable.

Thanks.
Alim

**Comment by kuke** [comment]
@misbullah It is feasible to train model by using feature data, only need to make some adaptation in data reprocessing.  

https://github.com/PaddlePaddle/DeepSpeech/blob/develop/data_utils/featurizer/speech_featurizer.py#L76

This line extracts features from audio segment, which can be replaced by reading from disk directly. Meanwhile, adjust the parameters in network if it is necessary

https://github.com/PaddlePaddle/DeepSpeech/blob/develop/model_utils/network.py
