### ISSUE TITLE
How to create my own language model

### ISSUE THREAD

**Issue by chesterkuo** [PaddlePaddle/DeepSpeech#161]
I got issue to download Language mode
 ( http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e)
 as the file show its 2.x G in size, but i always can download file up to 1.x GB only,it didn't help even i add to hosts file.

180.76.189.142  cloud.dlnel.org

Is there any other alternative server i can download ?

**Comment by chesterkuo** [comment]
Also, the language model based on binary file or arpa file if using kenlm tool ?

**Comment by kuke** [comment]
@chesterkuo Is the md5sum right? The decoder supports language model both in binary or arpa format.

**Comment by pkuyym** [comment]
@chesterkuo 

> Also, the language model based on binary file or arpa file if using kenlm tool ?

Yes, all the language models are trained using kenlm tool.

**Comment by chesterkuo** [comment]
there is one issue i can't figure out. Mandarin LM, based on info , 
===================
Mandarin LM
Different from the English language model, Mandarin language model is character-based where each token is a Chinese character. We use internal corpus to train the released Mandarin language models. The corpus contain billions of tokens. The preprocessing has tiny difference from English language model and main steps include:
===================

In this case the file for kenlm training will be 
"有 望 首 先 令 杭 州 以 及 浙 江 当 地 的 基 建 上 市 公 司 获 益"
or
"有望 首先 令 杭州 以及 浙江 当地 的 基建 上市公司 获益"

Different here is , using Jieba to to work seg of second case.


Any comment how we can train our own LM ?

**Comment by chesterkuo** [comment]
I'm asking this as i'd like to check if my LM file created correctly or not.

Here is case on those two LM (one is download from pre-created) , another is my LM that created based on aishell transcript file with white space on each char.

1)
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: data/aishell/mean_std.npz
model_path: checkpoints/aishell/params.latest.tar.gz
num_conv_layers: 2
num_proc_bsearch: 1
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
trainer_count: 1
use_gpu: 1
use_gru: 1
vocab_path: data/aishell/vocab.txt
------------------------------------------------
I0228 04:28:29.346346 29036 Util.cpp:166] commandline:  --use_gpu=1 --rnn_use_batch=True --trainer_count=1
[INFO 2018-02-28 04:28:38,561 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:28:38,562 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:28:38,563 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:28:38,564 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:28:38,565 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:28:38,566 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:28:43,316 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-02-28 04:28:48,350 model.py:253] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2018-02-28 04:28:48,351 model.py:254] end initializing scorer
[INFO 2018-02-28 04:28:48,351 infer.py:103] start inference ...

Target Transcription: 但是由于直销改为经销
Output Transcription: 但是由于直销改为经销
Current error rate [cer] = 0.000000

Target Transcription: 如今则猛增到一两亿美元
Output Transcription: 如今则某增到一二亿美元
Current error rate [cer] = 0.181818

Target Transcription: 相关公司股票走势农产品
Output Transcription: 相关公司股票走势农产品
Current error rate [cer] = 0.000000

Target Transcription: 汉能曾计划今年底前将这一数字提高到三百家
Output Transcription: 汉龙曾计划今年底前将这一数次提高到三百家
Current error rate [cer] = 0.100000

Target Transcription: 即一些财大气粗的科技公司自己不创新
Output Transcription: 即一些财大气粗的科技公司自己不创新
Current error rate [cer] = 0.000000

Target Transcription: 加强海外信息监测为企业提供对外投资指导
Output Transcription: 加强海外信息监测为企业提供对外投资指导
Current error rate [cer] = 0.000000

Target Transcription: 他们会拥有较快的速度
Output Transcription: 他们会拥有较快的速度
Current error rate [cer] = 0.000000

Target Transcription: 避免中国企业境外恶性竞争
Output Transcription: 避免中国企业境外恶性竞争
Current error rate [cer] = 0.000000

Target Transcription: 本月二八日超级月亮和最圆中秋月喜相逢
Output Transcription: 本月二十八日超级月亮和岁圆中秋月喜相逢
Current error rate [cer] = 0.111111

Target Transcription: 一二线城市虽然也处于调整中
Output Transcription: 一二线城市虽然也处于调整中
Current error rate [cer] = 0.000000
[INFO 2018-02-28 04:28:49,738 infer.py:124] finish inference

2) my own LM based aishell transcript.
-----------  Configuration Arguments -----------
alpha: 2.6
beam_size: 300
beta: 5.0
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: cer
infer_manifest: data/aishell/manifest.test
lang_model_path: examples/aishell/mylm/manifest.test.csv.new.arpa.bin
mean_std_path: data/aishell/mean_std.npz
model_path: checkpoints/aishell/params.latest.tar.gz
num_conv_layers: 2
num_proc_bsearch: 1
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 1024
share_rnn_weights: 0
specgram_type: linear
trainer_count: 1
use_gpu: 1
use_gru: 1
vocab_path: data/aishell/vocab.txt
------------------------------------------------
I0228 04:31:48.722075 29120 Util.cpp:166] commandline:  --use_gpu=1 --rnn_use_batch=True --trainer_count=1
[INFO 2018-02-28 04:31:56,499 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:31:56,500 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:31:56,502 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-02-28 04:31:56,503 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:31:56,504 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:31:56,505 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-02-28 04:32:01,899 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-02-28 04:32:01,916 model.py:253] language model: is_character_based = 0, max_order = 5, dict_size = 4299
[INFO 2018-02-28 04:32:01,916 model.py:254] end initializing scorer
[INFO 2018-02-28 04:32:01,916 infer.py:103] start inference ...

Target Transcription: 但是由于直销改为经销
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 如今则猛增到一两亿美元
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 相关公司股票走势农产品
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 汉能曾计划今年底前将这一数字提高到三百家
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 即一些财大气粗的科技公司自己不创新
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 加强海外信息监测为企业提供对外投资指导
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 他们会拥有较快的速度
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 避免中国企业境外恶性竞争
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 本月二八日超级月亮和最圆中秋月喜相逢
Output Transcription:
Current error rate [cer] = 1.000000

Target Transcription: 一二线城市虽然也处于调整中
Output Transcription:
Current error rate [cer] = 1.000000
[INFO 2018-02-28 04:32:03,217 infer.py:124] finish inference

**Comment by chesterkuo** [comment]
If I change to use CTC greedy (without LM case )with same trained param  , output result looks good.

**Comment by pkuyym** [comment]
@chesterkuo Thanks a lot, I have checked the `Aishell.py` and as you said, it is actually a bug. However, our model was trained on correct manifest. Would you please push a fix to fix the bug?

**Comment by chesterkuo** [comment]
@pkuyym , a pull request submit (https://github.com/PaddlePaddle/DeepSpeech/pull/165) for Aishell manifest issue.

About LM creation , do you have any idea on it ?

**Comment by wujsy** [comment]
@chesterkuo , I encountered  the same problem as you did, it's ok to use pre-load lm, but no output to use my own generated lm, have you sovled the problem yet ?
