### ISSUE TITLE
aishell预训练模型的结果糟糕

### ISSUE THREAD

**Issue by luweishuang** [PaddlePaddle/DeepSpeech#162]
我使用 aishell的预训练模型做 python infer.py，超参数采用aishell/run_infer_golden.sh里面的值, 在aishell的数据集train, dev, test数据集上的平均 cer 各为  0.015873， 0.086128， 0.029167，识别结果比较好。但是当我使用自己的数据集进行测试的时候，识别结果非常糟糕，平均 cer 为 1.153333。 我使用的测试音频是 16k 采样率，16位的，
[test_wavs_16k.zip](https://github.com/PaddlePaddle/DeepSpeech/files/1750830/test_wavs_16k.zip)
aishell 预训练模型的识别结果(lm 使用的zh_giga.no_cna_cmn.prune01244.klm)：
        groundtruth label: 出租房屋的话收益如何
        predict label: 澳洲房屋的话称如
        Current error rate [cer] = 0.500000

        groundtruth label: 我不太清楚地铁通吗
        predict label: 偶然之后二十二日
        Current error rate [cer] = 1.000000

        groundtruth label: 有没有健身房之类的
        predict label: 有的也不少一人的
        Current error rate [cer] = 0.777778

是有其他需要改动的地方吗？ 还是 aishell 模型不适用于该种数据集，finetune aishell的预训练模型会有帮助吗

**Comment by pkuyym** [comment]
如果配置没有问题，可能原因是测试集音频与aishell数据集的音频差异较大，这种情况下finetune应该会有明显效果。中文模型的训练对音频数据的需求比较大，请确保训练数据足够。

**Comment by luweishuang** [comment]
追问一句，我想将中文语音识别的groundtruth 由每个汉字变成 每个词，比如说原始的 vocab.txt里面的内容是“等，方，关，觉...."这样的，约5303个(baidu_cn1.2k模型)。我想把它变成 ”公司，好，你说，哪儿....“这样的词，约1000个。然后训练集以 aishell 为例，对原始的wav,txt对中的txt做一些修改，举例”BAC009S0002W0129 四十一 个 已 正式 取消 或 变相 放松 了 限购“(来自aishell_transcript_v0.8.txt)， 改为”BAC009S0002W0129 unknow 取消 unknow 限购“这样的(因为取消和限购在我的新的vocab.txt里)。然后还是使用目前的deep-speech2的模型架构来训练新的aishell数据集，这样的方案可行吗？
我觉得这有点类似于分类任务，但是碍于缺少数据集并且将已有数据集进行对齐切割的工作量过于巨大，所以想了这个折中的方案， @pkuyym 您觉得能行吗？
如果finetune一个新的数据集，请问多少时长的数据集是合适的？
