### ISSUE TITLE
ctc_beam_search_decoder documentation

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#163]
Do you have any documentation of ctc_beam_search_decoder.cpp?

more specifically: I wondering about score,ctc approx_ctc,log_prob_b_prev ,log_prob_nb_prev,log_prob_b_cur,log_prob_nb_cur parameters?

Could you please explain each of them?

Thanks!

**Comment by mrfox321** [comment]
Read the papers
