### ISSUE TITLE
基于该项目可以构建一个纯c++的asr识别系统么？

### ISSUE THREAD

**Issue by beyondboy** [PaddlePaddle/DeepSpeech#164]
项目需求，后续会有中文phoneme或者音节作为建模单元，需要引入wfst构图
并且后面部署需要纯c++，有人能给些参考建议么？
我目前的想法:
1.声学模型inference部分,用paddle 的capi
2.解码部分也方便可以换成c++的
现在麻烦的是声学特征提取部分，都是基于python的，有等价的c++方案么？

**Comment by kuke** [comment]
@beyondboy 你所说的1和2是比较容易实现的，但数据部分目前只有python实现，如有需求，可能需要自己用C++来实现这部分的等价逻辑

**Comment by Pelhans** [comment]
@beyondboy Kaldi那面有很多C++的特征提取工具

**Comment by cogmeta** [comment]
We have acoustic feature extraction implemented in pure c. We can help you with that. but, we need help with 1.Acoustic model inference part, using paddle's capi . Can you give a step by step insructions to recreate the network in paddle capi. Thanks.

**Comment by zxk1995** [comment]
> 项目需求，后续会有中文phoneme或者音节作为建模单元，需要引入wfst构图
> 并且后面部署需要纯c++，有人能给些参考建议么？
> 我目前的想法:
> 1.声学模型inference部分,用paddle 的capi
> 2.解码部分也方便可以换成c++的
> 现在麻烦的是声学特征提取部分，都是基于python的，有等价的c++方案么？

请问现在有实现等价的C++方案吗，我遇到了和你一样的问题，非常期待您的回复。
