### ISSUE TITLE
训练集与测试集的音频时长需要严格相似？

### ISSUE THREAD

**Issue by luweishuang** [PaddlePaddle/DeepSpeech#166]
我使用自己的数据集微调 baidu_cn1.2k中文模型， 训练音频是16k的采样率，训练集共7676个音频，平均时长为 3.01秒。测试集大小为56个，平均时长为 4.86秒。原始baidu_cn1.2k模型在该测试集上的 
         Final error rate [cer] (56/56) = 0.148315，
微调过后模型在同样测试集上的表现为：
    groundtruth label: 他希望大家团结一致努力工作在新的一年里取得更大成绩
predict label: 他是在家工作在一年期存款
Current error rate [cer] = 18.000000
Error rate [cer] (10/56) = 0.857143

groundtruth label: 排在马路边的真假音像制品宣传牌引得过往行人驻足浏览
predict label: 还在里边在今天工信息提前做
Current error rate [cer] = 23.000000
Error rate [cer] (11/56) = 0.862963

groundtruth label: 据行家估计时下在欧美流行的苏格兰呢计有三十余种之多
predict label: 今天在这里的人有多
Current error rate [cer] = 21.000000
Final error rate [cer] (30/56) = 0.86101
错误率显著上升且可以发现识别的文字结果变短了。是由于训练测试集数据集的音频时长不一致造成的吗?

**Comment by pkuyym** [comment]
@luweishuang baidu_cn1.2k的训练集采样频率是8k，跟16k存在差异

**Comment by luweishuang** [comment]
在 DeepSpeech/data_utils/featurizer/audio_featurizer.py 里有 target_sample_rate=16000 ， 并且                   allow_downsampling=True,  allow_upsampling=True，我debug 发现无论训练集音频是 8k 还是 16k 都会走这句的。 @pkuyym 你是指 finetune baidu_cn1.2k模型时 需要将  target_sample_rate改为8000 吗？

**Comment by pkuyym** [comment]
主要是8K音频算出来的mean std跟16K算出来的不太一样，所以如果8K音频训练的模型来预测16K音频，显然有问题。

**Comment by luweishuang** [comment]
@pkuyym 可能是git 版本不一致，最新版本的代码在 data_utils/featurizer/audio_featurizer.py 里有 target_sample_rate=16000，就是无论输入什么音频，都会转换到16k 的采样率，所以我觉得采样率没有问题。为什么你一直强调  baidu_cn1.2k的训练集采样频率是8k？无论是compute_mean_std还是训练的时候，都要经过audio_featurizer.py里的AudioFeaturizer啊

**Comment by sunjunlishi** [comment]
@luweishuang  你解释的非常棒，但是为啥不能识别出好的结果呀，不知道结果到底怎么样，唉

**Comment by sunjunlishi** [comment]
8k很多地方这样说，代码暂时研究的不够深入。不能更好的解释
