### ISSUE TITLE
TrainCost vs ValidationCost

### ISSUE THREAD

**Issue by kenyeung128** [PaddlePaddle/DeepSpeech#167]
Hi might i ask what's the TrainCost and ValidationCost during training, and what would be the optimal values for it?

**Comment by luweishuang** [comment]
just my opinion. I think the trainCost and validationCost should have similar value and they should get less when training process going. For they are all some kind of loss

**Comment by kenyeung128** [comment]
ok @luweishuang is there any benchmark value like <1 or <10 if it indicates a good model?

**Comment by kuke** [comment]
@luweishuang The is no benchmark. The optimal two costs should depend what training data you use.
