### ISSUE TITLE
memory leak ctc_beam_search_decoder

### ISSUE THREAD

**Issue by mrfox321** [PaddlePaddle/DeepSpeech#169]
If I repeatedly call the swig decoder `ctc_beam_search_decoder,` I get a memory leak of around 10MB per iteration.
```python
def score():

    scorer = Scorer(alpha,beta,language_model_path,vocab)
    best_path = ctc_beam_search_decoder(probs_seq2,vocab,beam_size,
                                            cutoff_prob=cutoff_p,cutoff_top_n=cutoff_n,
                                            ext_scoring_func=scorer)
    print best_path[0][1]

for i in range(num_iter):
    score()
```
Here is the memory profiler output after the first iteration:

> Line     Mem usage    Increment   Line Contents
================================================
    21     35.6 MiB     35.6 MiB   @profile
    22                                         def score():
    23                             
    24    878.4 MiB    842.7 MiB       scorer = Scorer(alpha,beta,language_model_path,vocab)
    25    878.4 MiB      0.0 MiB       best_path = ctc_beam_search_decoder(probs_seq2,vocab,beam_size,
    26    878.4 MiB      0.0 MiB                                               cutoff_prob=cutoff_p,cutoff_top_n=cutoff_n,
    27    878.7 MiB      0.4 MiB                                               ext_scoring_func=scorer)
    28    878.7 MiB      0.0 MiB       print best_path[0][1]

and after N iterations:

> Line #    Mem usage    Increment   Line Contents
================================================
    21   1446.4 MiB   1446.4 MiB   @profile
    22                             def score():
    23                             
    24   2061.3 MiB    614.9 MiB       scorer = Scorer(alpha,beta,language_model_path,vocab)
    25   2061.3 MiB      0.0 MiB       best_path = ctc_beam_search_decoder(probs_seq2,vocab,beam_size,
    26   2061.3 MiB      0.0 MiB                                               cutoff_prob=cutoff_p,cutoff_top_n=cutoff_n,
    27   2061.3 MiB      0.0 MiB                                               ext_scoring_func=scorer)
    28   2061.3 MiB      0.0 MiB       print best_path[0][1]

it seems that when I change the loop to:

```python 
for j in range(100):
    scorer = Scorer(alpha,beta,language_model_path,vocab)
    for i in range(num_iter):
        score()

    del scorer
```
The memory leak occurs in the outer loop associated with the construction of the scorer.  The memory is roughly constant in each inner loop iteration.

Additionally, if I do not run `score(),` the construction of `scorer` does not leak.

**Comment by kuke** [comment]
@mrfox321 First, the init of scorer only needs to be called once, so we haven't noticed the memory leak yet. Any new findings?

**Comment by mrfox321** [comment]
I call it multiple times in order to search of beam-search params.  I put each hyperparam evaluation into a process via `Pool()`, it can then be properly garbage collected.

**Comment by Engineering-Course** [comment]
@mrfox321 @kuke 
Do you figure out the problem?  I also find the memory leak in ctc_beam_search_decoder.
I profile the function and find that there will be around 0.3M memory increased after calling the function each time.
Any ideas?

`
    @profile

    def forward(self, log_probs, log_probs_length):
        beam_results = swig_decoders.ctc_beam_search_decoder(
            log_probs.tolist(), self.vocab, self.beam_width, self.cutoff_prob, self.cutoff_top_n,
            self.scorer)
        beam_results = [(res[0], res[1]) for res in beam_results]
        return beam_results
`
![image](https://user-images.githubusercontent.com/7713394/84971868-41f07880-b150-11ea-8f42-68cb7f12e680.png)

**Comment by mrfox321** [comment]
I never followed up. I am surprised it was never addressed.
