### ISSUE TITLE
Ubuntu14.04 安装过程问题总结

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/DeepSpeech#170]

**Comment by seiriosPlus** [comment]
1. setuptools 需要升级至新版，否则编译decoders/swig失败
2. flac 用apt-get安装的是1.3.0版本，需要下载源码安装1.3.2版本，否则安装libsndfile失败

**Comment by bolt163** [comment]
楼主这里能具体说下 setuptools的新版是什么版本吗，还有不升到新版有哪些问题表像供后来者参考。。。

**Comment by seiriosPlus** [comment]
采用pip install setuptools --upgrade 进行的升级，我当前版本是 38.5.2
