### ISSUE TITLE
a bug  in ctc beam search decoder

### ISSUE THREAD

**Issue by kiddding** [PaddlePaddle/DeepSpeech#171]
https://github.com/PaddlePaddle/DeepSpeech/blob/edaed68f33b7fff2455c26b880340ba680621f5c/decoders/swig/decoder_utils.cpp
The bug locates in line 30. It happens if you use **cutoff_top_n** but not **cutoff_prob** to prune log_probs of vocabulary. 
A correct version should be like this:
`prob_idx = std::vector<std::pair<int, double>>(
        prob_idx.begin(), prob_idx.begin() + (cutoff_top_n<cutoff_len)?cutoff_top_n:cutoff_len);` 
@kuke

**Comment by kuke** [comment]
No, line 30 is not a bug. Pay attention to 

https://github.com/PaddlePaddle/DeepSpeech/blob/edaed68f33b7fff2455c26b880340ba680621f5c/decoders/swig/decoder_utils.cpp#L26

When executed to line 30, ```cutoff_len``` should always not be greater than ```cutoff_top_n```

**Comment by kiddding** [comment]
Well, if I set **cutoff_top_n**=40 and **cutoff_prob**=1.0, lines between 20 and 28 will not be executed, when **cutoff_len** still holds the initial value, the number of all classes.
