### ISSUE TITLE
Noise file can't be downloaded

### ISSUE THREAD

**Issue by Rai220** [PaddlePaddle/DeepSpeech#179]
Hi! Thank you for your work! It is great project!
But I have trouble with noise emulation. Nose files from samples can't be downloaded, because the link from chime3_background.py was broken for now.
Can you fix it please?

**Comment by kuke** [comment]
@Rai220 Thanks for your attention. We will fix it soon.

**Comment by pkuyym** [comment]
@Rai220 Please refer https://github.com/PaddlePaddle/DeepSpeech/issues/62

**Comment by Rai220** [comment]
@pkuyym Thank you very much! It works now!
