### ISSUE TITLE
write audio feature generator in c/c++

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#180]
We want to write a complete c/c++ server. We have got a good hang of decoders. We were wondering whether it will be easy to write the feature generator code in c/c++. I think you are using third party library python_speech_features for that if i am not mistaken? Any points for generating those features in c/c++?

**Comment by kuke** [comment]
@cogmeta The library ```python_speech_features``` is for extracting the mfcc feature. But the power spectrum feature, which we used to train the released model, doesn't heavily depend on other third-party libraries. So it is not very hard to implement the feature generator in C/C++, I think.

**Comment by cogmeta** [comment]
I should have read your reply thoroughly before I went ahead and implemented MFCC feature generator in c/c++ assuming it was needed. Well, hopefully it will be useful somewhere else.

Just wanted double check again this time. For linear specgram you are just using FFT values scaled by certain factor. What is the logic behind the scale factor?


scale = np.sum(weighting**2) * sample_rate
 fft[1:-1, :] *= (2.0 / scale)
  fft[(0, -1), :] /= scale

**Comment by cogmeta** [comment]
Also, can you please provide hints/pointers to create (or rather  recreate) the paddle network in c/c++ for the deep speech BaiduEN8k Model? thanks.
