### ISSUE TITLE
我用自己训练的中文语言模型做测试，提示如下：

### ISSUE THREAD

**Issue by uuid128** [PaddlePaddle/DeepSpeech#182]
我按照kenlm工具来做的中文语言模型，然后生成的二进制文件。

在运行run_infer.sh时，提示如下：
UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-41: ordinal not in range(128)

在运行run_test.sh时，提示如下：
Error rate [cer] (128/?) = 0.795897
Error rate [cer] (256/?) = 0.806996
Error rate [cer] (384/?) = 0.803812
Error rate [cer] (512/?) = 0.798943
......

这里的问号？是什么含义呢？语言模型文件编码是哪种？

**Comment by pkuyym** [comment]
@yangzhengzhe 默认使用的是UTF-8

**Comment by Lebron-Kun** [comment]
> @pkuyym 感谢！问题已经解决。原因是使用的docker容器系统设置的问题。修改了infer.py文件，直接把推理结果保存在了文本中，这样就不会提示错误了。

能否简单说一下，训练好的语言模型或者声学模型，调用哪个代码可以进行测试，希望能指点一二
