### ISSUE TITLE
getting the loss of a audio file with a certain transcription

### ISSUE THREAD

**Issue by alanbekker** [PaddlePaddle/DeepSpeech#186]
Any chance to get a guidance on hoe to receive the ctc_loss of a (audio,transcrption) pair via the python wrapper?

Thanks in advance!

**Comment by kuke** [comment]
Please refer to this method
https://github.com/PaddlePaddle/DeepSpeech/blob/dad1c2727e375beb05dd747b06b04d0438e4a78d/model_utils/model.py#L158-L174

**Comment by alanbekker** [comment]
It tried it already...do you have any documentation or example how to use
this function..
any combination I tried failed, like: infer_data=[(speech,txt)] or
[speech,txt] or (speech,txt) with different errors or dumps..

**Comment by hui001** [comment]
@alanbekker  Have you figured it out ? I incurred the same problem, looking forward your reply, thanks.

**Comment by hui001** [comment]
I have figured it out , just set the DataGenerator's keep_transcription_text to False and make the same preprocess as in  infer_batch_probs()：
data_generator = DataGenerator(
        vocab_filepath=args.vocab_path,
        mean_std_filepath=args.mean_std_path,
        augmentation_config='{}',
        specgram_type=args.specgram_type,
        num_threads=8,
        keep_transcription_text=False)
