### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by VictorBebnev** [PaddlePaddle/DeepSpeech#187]
Hi! we have some problem with training own acoustic model. After each era, the consumption of RAM increases and, as a result, training stops. Could you help me?
Thanks.

**Comment by kuke** [comment]
What's your environment? Memory leak is not often to be seen. If the training loss decreasing normally, you can resume training from the latest saved model.

**Comment by VictorBebnev** [comment]
Ubuntu 14.04 
GeForce GTX 1060 6Gb x 2
Intel® Xeon® E5-2698 v3

> If the training loss decreasing normally, you can resume training from the latest saved model.


I think this isn't good idea. Our memory leak equals 2Gb RAM

**Comment by VictorBebnev** [comment]
Our env:
Ubuntu 14.04
Cuda 8.0
Intel® Xeon® E5-2698 v3
GeForce GTX 1060 6gb
24Gb RAM
RAM begins to flow at the beginning of every epoch. The leak equals 2 Gb.
I think that this workaround is bad choice. Do you have another idea?

**Comment by kuke** [comment]
You mean 2Gb per epoch?  It's quite strange that we never saw so severe memory leak.
