### ISSUE TITLE
下载Mandarin LM Small模型后端出现错误

### ISSUE THREAD

**Issue by DLZSY** [PaddlePaddle/DeepSpeech#191]
已经尝试过 在/etc/hosts 添加 180.76.189.142 cloud.dlnel.org 并且重启了网卡服务，(mac/linux) 
但是仍然无法下载，提示 A server error occurred.  Please contact the administrator.

请问如何解决？

**Comment by sailordiary** [comment]
同问，下载不了

**Comment by Cxywzx** [comment]
问题已解决！
#185 [Fix invlid download url.](https://github.com/PaddlePaddle/DeepSpeech/pull/185/commits/20533f5383838c2ed1d8c185fe0b8c1cbdc92b91)
非常感谢 @pkuyym

**Comment by frozenfires** [comment]
我下载的只有1.6个G，运行提示大小不够，你能把下载完成的文件上传到云盘或其他地方吗 @Cxywzx

**Comment by Lebron-Kun** [comment]
> 问题已解决！
> #185 [Fix invlid download url.](https://github.com/PaddlePaddle/DeepSpeech/pull/185/commits/20533f5383838c2ed1d8c185fe0b8c1cbdc92b91)
> 非常感谢 @pkuyym

您好，想问一下，下载好的语言模型或者声学模型怎么用？能否指教一下，调用那个代码可以直接加载训练好的模型，想试一下效果

**Comment by Cxywzx** [comment]
> 我下载的只有1.6个G，运行提示大小不够，你能把下载完成的文件上传到云盘或其他地方吗 @Cxywzx

反复下载几次就好了，我当初也是下了几次才下完整的。

**Comment by Cxywzx** [comment]
> > 问题已解决！
> > #185 [Fix invlid download url.](https://github.com/PaddlePaddle/DeepSpeech/pull/185/commits/20533f5383838c2ed1d8c185fe0b8c1cbdc92b91)
> > 非常感谢 @pkuyym
> 
> 您好，想问一下，下载好的语言模型或者声学模型怎么用？能否指教一下，调用那个代码可以直接加载训练好的模型，想试一下效果

直接运行/examples下面的例子就可以了
