### ISSUE TITLE
Production Level DeepSpeech

### ISSUE THREAD

**Issue by rmalav15** [PaddlePaddle/DeepSpeech#192]
Hi,

According to my best understanding, the demo_server provided with does not implement any of the improvement discussed in section[7] (Deployment) of the DeepSpeech2 paper, right?

I wanted to know, are the discussed deployment improvements i.e Batch Dispatch, half-precision matrix-matrix multiply kernel, Improved beam-search, row-convolution unidirectional model provided with this Repo? If yes, can you please share the details?

Thanks,
Ram

**Comment by kuke** [comment]
@rmalav15 We have a [C++ decoder](https://github.com/PaddlePaddle/DeepSpeech/tree/develop/decoders/swig) with  highly-optimized beam search. About other features you mentioned, no, not yet.
