### ISSUE TITLE
求助：下载国语模型失败

### ISSUE THREAD

**Issue by Cxywzx** [PaddlePaddle/DeepSpeech#193]
求助！问题如下：
1、Mandarin LM Small下载失败，报500服务器错误。
![错误信息](https://user-images.githubusercontent.com/24585538/37955409-0963c416-3198-11e8-8e7b-423f70424a78.png)
2、Mandarin LM Large总是下载不完整，一般下载到1~5G就完了，是否可以支持断点续传。

**Comment by pkuyym** [comment]
For question 2, please refer https://github.com/PaddlePaddle/models/issues/301.

**Comment by Cxywzx** [comment]
@pkuyym 
谢谢您的回复！
加了本机域名解析之后，到目前为止，已经下载了13G，没出现中断，继续下载中。
完成后，再来回复。

**Comment by Cxywzx** [comment]
@pkuyym 
非常感谢！70.4G大文件已下载完成。
`[root@localhost work]# wget -c 'http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e' -O ./zh_giga.no_cna_cmn.prune01244.klm
--2018-03-28 11:27:51--  http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e
正在解析主机 cloud.dlnel.org (cloud.dlnel.org)... 180.76.189.142
正在连接 cloud.dlnel.org (cloud.dlnel.org)|180.76.189.142|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2018-03-28 11:27:52 错误 500：Internal Server Error。

[root@localhost work]# ls
baidu-research  DeepSpeech  deps_src  LuaRocks  OpenSLR  PaddlePaddle  tmp_data  torch  zh_giga.no_cna_cmn.prune01244.klm
[root@localhost work]# wget -c 'http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37' -O ./zhidao_giga.klm
--2018-03-28 11:31:29--  http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37
正在解析主机 cloud.dlnel.org (cloud.dlnel.org)... 180.76.189.142
正在连接 cloud.dlnel.org (cloud.dlnel.org)|180.76.189.142|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：未指定 [text/html]
正在保存至: “./zhidao_giga.klm”

    [                                                   <=>                                            ] 75,588,585,027 5.63MB/s 用时 7h 24m                     <=>                     ] 61,233,496,064 6.23MB/s             

2018-03-28 18:56:25 (2.70 MB/s) - “./zhidao_giga.klm” 已保存 [75588585027]

[root@localhost work]#`

**Comment by Cxywzx** [comment]
问题1已解决： #185 [Fix invlid download url.](https://github.com/PaddlePaddle/DeepSpeech/pull/185/commits/20533f5383838c2ed1d8c185fe0b8c1cbdc92b91)
非常感谢 @pkuyym

**Comment by whaozl** [comment]
add /etc/hosts:
180.76.189.142  cloud.dlnel.org

wget -c 'http://cloud.dlnel.org/filepub/?uuid=5cd1688e-78d9-4b9e-9c2f-6f104bd5b518' -O ./zh_giga.no_cna_cmn.prune01244.klm
wget -c 'http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37' -O ./zhidao_giga.klm
