### ISSUE TITLE
中文声韵母建模

### ISSUE THREAD

**Issue by tao-githup** [PaddlePaddle/DeepSpeech#202]
项目需要，用中文的声韵母来做建模单元，解码时需要wfst构图，请问这部分有代码参考吗，谢谢

**Comment by pkuyym** [comment]
@tao-githup 我理解应该是kaldi的解码？参照这里：https://github.com/PaddlePaddle/models/tree/develop/fluid/DeepASR/decoder

**Comment by tao-githup** [comment]
@pkuyym 太感谢了，如果借鉴这个代码的话，里面的fst的图是不是特别大呢，

**Comment by bolt163** [comment]
@tao-githup  这里是打算用 中文的声韵母来替代 alphabet.txt 里的中文汉字吗

**Comment by bolt163** [comment]
@pkuyym   /fluid/DeepASR/decoder
这个目录在最新的 PaddlePaddle源代码目录怎么找不到。。。，这是为何？
