### ISSUE TITLE
Why is there a constant score for OOV?

### ISSUE THREAD

**Issue by ankitmundada** [PaddlePaddle/DeepSpeech#205]
[This](https://github.com/PaddlePaddle/DeepSpeech/blob/e1013dc44f88746c95e3b49643cc156e54e6dfae/decoders/swig/scorer.cpp#L84) line gives a score of -1000 (which is declared [here](https://github.com/PaddlePaddle/DeepSpeech/blob/e1013dc44f88746c95e3b49643cc156e54e6dfae/decoders/swig/scorer.h#L16)), to any n-gram which contains an OOV. 
Why have you used this approach instead of getting an OOV based score from the language model itself? My guess is because the LM used by you is developed using common_crawl dataset and is heavily pruned, so it makes sense to have a much stricter OOV check. Is the same approach necessary for a language model which is not built using Common_crawl and uses our own higher quality dataset?

**Comment by pkuyym** [comment]
To punish those candidate sequences containing OOV, we set a very small score for beam path having OOV. However, this strategy is rarely related to the quality of LM. For your case, I think it's better to do some experiments. Let the results tell whether to use this strategy or not.

**Comment by ankitmundada** [comment]
@pkuyym  Thank you very much for your insights!
My understanding of the `OOV Penalty` strategy that you use was the sheer size of the dataset (common_crawl) which you've used. The vocab for such LM trained using common_crawl will be huge and hence chances of a word being `OOV` are very rare.
The Language Model that we're building uses a much smaller dataset relative common crawl dataset but is of much higher quality (it is manually verified). But because of the size is small, vocab will be small than common_crawl. Then the chances of a word to be an `OOV` should be higher. That is why I don't think it will be the best strategy for us to use `OOV Penalty`. Do you think this to be a right rationale for not going with `OOV Penalty`? We are thinking of following changes:
- Language Model:
  1. No Pruning
  2. No `<unk>` tokens for rare words

- Ctcdecode:
  1. Skip `OOV_SCORE` completely
  2. Whenever an `OOV` is encountered, set `word_index=0` and use that index for getting the LM score.
