### ISSUE TITLE
what are the tuning's required for far field recognition using BaiduEN8k model

### ISSUE THREAD

**Issue by saibharani** [PaddlePaddle/DeepSpeech#219]
I want to test the far field recognition accuracy of BaiduEN8k model can anyone suggest some hyper parameter tunings or any other tips for increasing the present poor accuracy levels for far-field recognition.
Thank you. @pkuyym

**Comment by kuke** [comment]
The tuning process should following the same way if you have a well-trained model by far field audio data.
