### ISSUE TITLE
soundfile问题

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/DeepSpeech#222]
在运行examples/tiny里的run_data，出现以下错误：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 373, in read
    subtype, endian, format, closefd) as f:
  File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 1265, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '61-70968-0000.flac': File contains data in an unimplemented format.
这一般是什么原因引起的呢？

**Comment by kuke** [comment]
```
sudo apt-get install -y pkg-config libflac-dev libogg-dev libvorbis-dev libboost-dev swig
```
一般是因为flac, ogg, vorbis这几个依赖没有安装好

**Comment by robin521111** [comment]
我用的是Docker也遇到了这个问题，相关的库应该是装好了的。还有其它人遇到了这个问题了吗？

> root@1fcc0767197d:/DeepSpeech/DeepSpeech/examples/aishell# apt-get install -y pkg-config libflac-dev libogg-dev libvorbis-dev libboost-dev swig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-dev is already the newest version (1.58.0.1ubuntu1).
libflac-dev is already the newest version (1.3.1-4).
libogg-dev is already the newest version (1.3.2-1).
libvorbis-dev is already the newest version (1.3.5-3).
pkg-config is already the newest version (0.29.1-0ubuntu1).
swig is already the newest version (3.0.8-0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
root@1fcc0767197d:/DeepSpeech/DeepSpeech/examples/aishell#

**Comment by gekelly** [comment]
> 在运行examples/tiny里的run_data，出现以下错误：
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 373, in read
> subtype, endian, format, closefd) as f:
> File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 740, in **init**
> self._file = self._open(file, mode_int, closefd)
> File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 1265, in _open
> "Error opening {0!r}: ".format(self.name))
> File "/home/hwja/anaconda3/envs/py2/lib/python2.7/site-packages/soundfile.py", line 1455, in _error_check
> raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
> RuntimeError: Error opening '61-70968-0000.flac': File contains data in an unimplemented format.
> 这一般是什么原因引起的呢？

我尝试下面人说法安装依赖包，但最终也没能解决我滴问题。所以想问下最终是怎么解决？

**Comment by Aionrichman** [comment]
我也遇到同样的问题
