### ISSUE TITLE
在PASS:14时SWAP空间被占满

### ISSUE THREAD

**Issue by Cxywzx** [PaddlePaddle/DeepSpeech#223]
系统环境：CentOS7 64bit，1块GTX 1080TI，内存32G，SWAP：100G
运行 aishell 训练脚本，在PASS: 14, Batch: 5000 ... 时 SWAP空间被占满，deepspeech或paddlepaddle不会自动释放空间吗？还是原本就需要很大的SWAP？那么SWAP大小设置多少比较合适？
![_20180429155352](https://user-images.githubusercontent.com/24585538/39404763-04d1b6a8-4bcc-11e8-9199-c07e6108adba.png)
![_20180429155406](https://user-images.githubusercontent.com/24585538/39404764-0514312c-4bcc-11e8-8fbe-aa1951f4e53a.png)

**Comment by Cxywzx** [comment]
停止训练，修改/proc/sys/vm/drop_caches，0改成3后，继续训练，SWAP占用空间目前没看到大的增长。
![default](https://user-images.githubusercontent.com/24585538/39404879-fa0efaee-4bcd-11e8-9f20-8858b938211b.PNG)

**Comment by kuke** [comment]
@Cxywzx 有可能在你的系统上发生了内存泄漏， 如果改小batch size会减缓这个问题吗？

**Comment by Cxywzx** [comment]
batch size设置成了24
在此之前batch size是16 提示梯度激增 后来改成24就能正常训练了
结果每到PASS14就复现上述问题

**Comment by Cxywzx** [comment]
@kuke 你好！我这次设置batch_size=16，训练到PASS 15 又报无法分配内存了。具体错误如下：
`Pass: 15, Batch: 7500, TrainCost: 1.358304
.....
------- Time: 5492 sec,  Pass: 15, ValidationCost: 10.9255721649
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 125, in main
    train()
  File "train.py", line 116, in train
    test_off=args.test_off)
  File "/home/work/deepspeech/model_utils/model.py", line 155, in train
    feeding=adapted_feeding_dict)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/trainer.py", line 162, in train
    for batch_id, data_batch in enumerate(reader()):
  File "/home/work/deepspeech/model_utils/model.py", line 391, in adapted_reader
    for instance in data():
  File "/home/work/deepspeech/data_utils/data.py", line 199, in batch_reader
    for instance in instance_reader():
  File "/home/work/deepspeech/data_utils/utility.py", line 178, in xreader
    manager = Manager()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/usr/lib64/python2.7/multiprocessing/managers.py", line 524, in start
    self._process.start()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Failed in training!`

**Comment by Cxywzx** [comment]
在之前batch_size=24时，也有在PASS15报该错误的情况。

**Comment by pkuyym** [comment]
@Cxywzx 试试这个PR https://github.com/PaddlePaddle/DeepSpeech/pull/154 ？

**Comment by Cxywzx** [comment]
@pkuyym 好的，已经按照这个PR修改了，现在正在训练，估计要十几个小时之后才能验证到。在有结果后，我会第一时间反馈。非常感谢！

**Comment by Cxywzx** [comment]
@pkuyym @kuke @VictorBebnev 
应该已经解决了，到目前PASS18为止没有发生内存溢出问题。待最终训练结束后，我再把结果反馈回来。非常感谢 @pkuyym
![image](https://user-images.githubusercontent.com/24585538/39731542-b5c2b924-529a-11e8-91a4-f2f504656aef.png)
![image](https://user-images.githubusercontent.com/24585538/39731552-c5726680-529a-11e8-86df-4a0a478c5db0.png)
![image](https://user-images.githubusercontent.com/24585538/39731561-d11672b0-529a-11e8-914b-d582d8655236.png)

**Comment by Cxywzx** [comment]
@VictorBebnev 
我这里的问题是SWAP存储溢出问题。
我想你说的内存溢出，很有可能是GPU内存溢出。我之前遇到过，在设置了大的batch_size时会很容易出现。我现在的设置是batch_size=24，GPU的12G内存刚好够用。
![image](https://user-images.githubusercontent.com/24585538/39731731-e027e058-529b-11e8-837a-5df9bcae2199.png)

**Comment by Cxywzx** [comment]
PASS35没发生过SWAP区爆满现象。
