### ISSUE TITLE
中文识别时间问题

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/DeepSpeech#224]
使用aishell模型进行中文识别，感觉非常慢，而且效果也不好。
另外，想基于baidu_1.2k_model进行识别，但是模型里没有vocab.text，此外，相应的warmup_manifest也没有，需要怎么进行设置呢?
（待识别的数据本来是一条3-5min的，但是实在太慢，就换成aishell的其中一条wav数据了，只有几秒钟，还是非常慢，等了很久也没有最终的结果出来，是我的设置有问题吗还是参数需要调整一下？）
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: models/aishell/mean_std.npz
model_path: models/aishell/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: my_data
use_gpu: False
use_gru: 1
vocab_path: data/aishell/vocab.txt
warmup_manifest: data/aishell/manifest.test
------------------------------------------------
I0506 15:04:53.478561  3892 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2018-05-06 15:04:53,587 layers.py:2689] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-06 15:04:53,588 layers.py:3251] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-06 15:04:53,589 layers.py:7409] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-06 15:04:53,590 layers.py:2689] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-06 15:04:53,591 layers.py:3251] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-06 15:04:53,591 layers.py:7409] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-05-06 15:05:00,766 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-05-06 15:05:06,010 model.py:253] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2018-05-06 15:05:06,010 model.py:254] end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0913/BAC009S0913W0441.wav')
Response Time: 51.677608, Transcript: 篮
('Warm-up Test Case %d: %s', 1, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0912/BAC009S0912W0243.wav')
Response Time: 46.002436, Transcript: 篮
('Warm-up Test Case %d: %s', 2, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0902/BAC009S0902W0189.wav')
Response Time: 40.113678, Transcript: 篮
-----------------------------------------------------------
ASR Server Started.

**Comment by jiaozhusos** [comment]
修改了参数，warmup基本正常，但是识别时间真的是非常慢，一直在运行，都没有结果，
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0913/BAC009S0913W0441.wav')
Response Time: 9.861244, Transcript: 就回家律师事务所律师邱宝昌表示
('Warm-up Test Case %d: %s', 1, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0912/BAC009S0912W0243.wav')
Response Time: 6.432676, Transcript: 推动环保基础设施和服务向农村延伸
('Warm-up Test Case %d: %s', 2, u'/home/hwja/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0902/BAC009S0902W0189.wav')
Response Time: 4.880340, Transcript: 农业产业体系更趋完善
-----------------------------------------------------------
ASR Server Started.
之后就什么都没有了。。。

**Comment by wuzong19** [comment]
你好，可以互加一下qq么？398673054

**Comment by Ckj409399** [comment]
@jiaozhusos 你好，请问你的问题：

“想基于baidu_1.2k_model进行识别，但是模型里没有vocab.text，此外，相应的warmup_manifest也没有，需要怎么进行设置呢?”

有办法解决了吗？可以交流一下吗

**Comment by sunjunlishi** [comment]
data/aishell/manifest.test 文件从哪搞到，能发个？

**Comment by whaozl** [comment]
录音文件 那都是读取问题 要指定格式 int 就是整数 float就是浮点数

**Comment by sunjunlishi** [comment]
@whaozl 讲的不错，读取问题都可以正确。但是 百度 这个 貌似 不是 很准确识别其他的。？？

**Comment by whaozl** [comment]
很准确识别其他的 指的是？

**Comment by sunjunlishi** [comment]
除了训练样本以外的。识别你的准确吗

**Comment by whaozl** [comment]
我的能识别出来的，大概20~30%错误率，样本不够，正在想办法加样本

**Comment by liuborama** [comment]
@jiaozhusos  使用baidu_1.2k_model，解决了warmup_manifest 的设置问题了吗？

@whaozl  麻烦问一下基于那个model进行训练的呢？方便贴一下设置参数吗？

这个热度不够啊。。。

**Comment by whaozl** [comment]
我没有用paddlepaddle 自己写的
