### ISSUE TITLE
model infer时infer_results中出现nan

### ISSUE THREAD

**Issue by neozhangthe1** [PaddlePaddle/DeepSpeech#226]
使用自有数据训练的模型，在预测过程中时常报以下错误
*** Aborted at 1516804178 (unix time) try "date -d @1516804178" if you are using GNU date ***
PC: @ 0x0 (unknown)
*** SIGFPE (@0x7fe13bdd2f36) received by PID 8361 (TID 0x7fe12114b700) from PID 1004351286; stack trace: ***

经过debug发现问题出在https://github.com/PaddlePaddle/DeepSpeech/blob/dad1c2727e375beb05dd747b06b04d0438e4a78d/model_utils/model.py#L197

对于特定的utterance，infer_results中会出现nan，具体表现是infer得到的向量值随着time step减小，最终变成nan

例子如下
![35201525813754_ pic_hd](https://user-images.githubusercontent.com/1272486/39784768-2d9a8a38-534c-11e8-962d-1117b310eeac.jpg)

![35171525813706_ pic_hd](https://user-images.githubusercontent.com/1272486/39784751-1fa2841c-534c-11e8-9f0f-730657da6b7b.jpg)

其中每行为time step以及对应的向量

**Comment by pkuyym** [comment]
请描述一下上面的输出是什么？是概率矩阵么？
特定utterance有什么特点，过长？过短？还是label有些问题？
```
对于特定的utterance，infer_results中会出现nan，具体表现是infer得到的向量值随着time step减小，最终变成nan
```
建议在training data上面测一下cer，看模型是否收敛正常。

**Comment by neozhangthe1** [comment]
是模型Infer得到的hidden state，utterance没有发现特别的问题，模型正常，大多数情况下可以的到正确结果。
对于不同的模型，出现问题的utterance也不同，utterance a在模型A中会出问题，但是在模型B中可以正常infer。而模型B对于utterance b可能出问题。比较诡异
