### ISSUE TITLE
安装paddlepaddle报错

### ISSUE THREAD

**Issue by songxia928** [PaddlePaddle/DeepSpeech#227]
你好，我再机器上执行（pip install paddlepaddle）装paddlepaddle的时候，报以下错误：
[xxxxxx@l22-240-81 DeepSpeech]$ pip install paddlepaddle
Collecting paddlepaddle
  Using cached https://files.pythonhosted.org/packages/9c/bf/5f466741befa8b27a36cb8b224912f7fd7b0c4af58d6cdbb7b47bb366ae7/paddlepaddle-0.11.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting graphviz (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/84/44/21a7fdd50841aaaef224b943f7d10df87e476e181bb926ccf859bcb53d48/graphviz-0.8.3-py2.py3-none-any.whl
Collecting scipy>=0.19.0 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting nltk>=3.2.2 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/50/09/3b1755d528ad9156ee7243d52aa5cd2b809ef053a0f31b53d92853dd653a/nltk-3.3.0.zip
Collecting opencv-python (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/57/81/0a678c3f457f880c26ab4bd32c4bdcd3fb6fa5d335e9e8683798d290c9b3/opencv_python-3.4.0.12-cp27-cp27mu-manylinux1_x86_64.whl
Collecting numpy>=1.12 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/c0/e7/08f059a00367fd613e4f2875a16c70b6237268a1d6d166c6d36acada8301/numpy-1.14.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting Pillow (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/00/49/a0483e7308b4b04b5a898789911dbb876d9fea54e7df0453915e47744cfd/Pillow-5.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting matplotlib (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/33/da/6409d32c46778ed20308e83bc501ff2ff8a9cbda5dd7b26362c5e99a6149/matplotlib-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting recordio>=0.1.0 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/01/29/ee510d487bb2665e53b0171a6473531a3df86341ade7ab68d879cc6a2ac4/recordio-0.1.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting requests==2.9.2 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/8b/e7/229a428b8eb9a7f925ef16ff09ab25856efe789410d661f10157919f2ae2/requests-2.9.2-py2.py3-none-any.whl
Collecting rarfile (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/de/a4/8b4abc72310da6fa53b6de8de1019e0516885d05369d6c91cba23476abe5/rarfile-3.0.tar.gz
Collecting protobuf==3.1 (from paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/b2/30/ab593c6ae73b45a5ef0b0af24908e8aec27f79efcda2e64a3df7af0b92a2/protobuf-3.1.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from nltk>=3.2.2->paddlepaddle) (1.9.0)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/b8/2f/49e53b0d0e94611a2dc624a1ad24d41b6d94d0f1b0a078443407ea2214c2/subprocess32-3.2.7.tar.gz
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from matplotlib->paddlepaddle) (2018.4)
Collecting python-dateutil>=2.1 (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/3a/62/a8c9bef3059d55ab38e41fe9cba4fad773bfc04e47290bab84db1c18262e/kiwisolver-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib->paddlepaddle)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from protobuf==3.1->paddlepaddle) (0.9.8)
rtslib-fb 2.1.63 has requirement pyudev>=0.16.1, but you'll have pyudev 0.15 which is incompatible.
matplotlib 2.2.2 has requirement six>=1.10, but you'll have six 1.9.0 which is incompatible.
Installing collected packages: graphviz, numpy, scipy, nltk, opencv-python, Pillow, pyparsing, backports.functools-lru-cache, subprocess32, python-dateutil, kiwisolver, cycler, matplotlib, recordio, requests, rarfile, protobuf, paddlepaddle
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/graphviz'
Consider using the `--user` option or check the permissions.

=======================================================
系统版本 ： Linux version 4.9.0 (root@localhost.localdomain) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Wed May 2 11:23:23 CST 2018
Python版本：2.7

请教有什么办法吗？

**Comment by pkuyym** [comment]
看起来是权限问题？试试 `pip install paddlepaddle --user`
```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/graphviz'
Consider using the --user option or check the permissions.
```
