### ISSUE TITLE
Update bench mark data for Libri model and corresponding url

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/DeepSpeech#23]
- [x] evaluate on libri-test.clean and libri-test.other
- [x] evaluate on vox data

**Comment by pkuyym** [comment]
Test Set                | LibriSpeech Model 
:---------------------  | ---------------:
LibriSpeech Test-Clean  | 0.075953
LibriSpeech Test-Other  | 0.234954           
VoxForge American-Canadian |
VoxForge Commonwealth   |     
VoxForge European       |     
VoxForge Indian         |         
Baidu Internal Testset  |

**Comment by kuke** [comment]
Please  present WERs in percentage.

**Comment by pkuyym** [comment]
Already updated
