### ISSUE TITLE
有没有完整的中文教程，能让我这种傻瓜都会使用！

### ISSUE THREAD

**Issue by wuzong19** [PaddlePaddle/DeepSpeech#236]
我研究了两天了，还是没有搞明白，但是现在公司项目又需要自己做语音识别！
而且很急的那种········
而我又很菜，英文不好！！！
不知道有没有哪位大神有完整的操作教程！
有经验的大神笔记给抄一下也好！留个联系方式，我加你！

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/README_cn.md 中文文档已经上线了 @wuzong19
