### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#25]
我一直在寻找ctc加上语言模型的实现方式，虽然有苗亚杰博士的示范，但是shell脚本实在是艰涩，没想到找到了这个项目。非常感谢作者。在这里提个想法，不知道可以把解码文件转化为python文件吗？

**Comment by pkuyym** [comment]
@john81529 你是说python实现？我们较早版本确实是python实现的，ctc+lm，你可以查看commit 175457bf64afd89696925b46bc00e0586eee71dc，里面有个decoder.py

**Comment by john81529** [comment]
嗯嗯。是的。

**Comment by kuke** [comment]
@john81529 谢谢你的关注。我们曾经实现过一个python的decoder，[decoder](https://github.com/PaddlePaddle/DeepSpeech/tree/develop/decoders/decoders_deprecated.py)以及[语言模型部分](https://github.com/PaddlePaddle/DeepSpeech/blob/develop/decoders/scorer_deprecated.py)都还保留在这个工程中，作为原型你可以参考。不过为了追求效率和精度，我们现在正在用的是一个C++版的decoder，其实现更加复杂，在看懂了python版的基础上，你可以进一步看下这个decoder。

**Comment by john81529** [comment]
谢谢。我觉得，你们这个工作真的是造福很多这个方向的研究者。kaldi实在是太过艰涩，而且很多模型令人怀疑。所以，我一直想实现ctc加上attention机制，无奈一直不知道怎么实现ctc加语言模型。你们的工作真是给我打开了一扇门。我感觉，在这个基础上，实现百度的deepspeech3，应该就有基础了。再次感谢。对了，github上很多基于tensorflow的都没有加上语言模型，算是玩具。我觉得，你们这个几乎算是半工程实现。非常感谢。

**Comment by kuke** [comment]
@john81529 感谢你对我们工作的肯定。让更多的研究人员和开发者低门槛应用DeepSpeech2、认识和接受PaddlePaddle，是我们做这个工作的初衷，我们也力求做到达到工业级应用的标准。非常高兴看到这个项目为你的研究工作带来了便宜和启发，期望能得到更多这样积极的反馈。

这个项目还在完善阶段，在使用中有任何问题，请多多给我们提有益的建议和意见。

再次感谢你的关注！

**Comment by Lebron-Kun** [comment]
> 我一直在寻找ctc加上语言模型的实现方式，虽然有苗亚杰博士的示范，但是shell脚本实在是艰涩，没想到找到了这个项目。非常感谢作者。在这里提个想法，不知道可以把解码文件转化为python文件吗？

兄弟，能否留个邮箱，我现在也在做CTC-lm的实现，可以交流一下

**Comment by Lebron-Kun** [comment]
> 谢谢。我觉得，你们这个工作真的是造福很多这个方向的研究者。kaldi实在是太过艰涩，而且很多模型令人怀疑。所以，我一直想实现ctc加上attention机制，无奈一直不知道怎么实现ctc加语言模型。你们的工作真是给我打开了一扇门。我感觉，在这个基础上，实现百度的deepspeech3，应该就有基础了。再次感谢。对了，github上很多基于tensorflow的都没有加上语言模型，算是玩具。我觉得，你们这个几乎算是半工程实现。非常感谢。

您好，我最近也在做这个工作，但是我想对拼音建模，通过【声学模型】得到一串拼音，然后再经过【语言模型】--【解码（把拼音解码为汉字）】这个过程，也就是CTC+语言模型的解码过程。。。。。。。。所以能否留个邮箱，请教您一下
