### ISSUE TITLE
BaiduCN1.2k Model  调参问题

### ISSUE THREAD

**Issue by jiaozhusos** [PaddlePaddle/DeepSpeech#252]
中文识别，
模型为：BaiduCN1.2k Model 
语言模型为：Mandarin LM Large
识别效果不理想，想对alpha和beta进行调参，但是tools\tune.py里的tune_manifest参数只有英文的，中文的数据没有，如何进行调整呢？

**Comment by xuzhaoqing** [comment]
@jiaozhusos  hi, I'm also facing this problem. Have you solved it yet? Could u pls help me with it? My QQ is 827106588, thanks very much!!

**Comment by liuborama** [comment]
@jiaozhusos 你好，麻烦问一下， 使用BaiduCN1.2k Model，是如何设置manifest的呢？你解决了吗？
我想跑demo_server.py，但是这个warmup_manifest参数不知道如何来设置，能帮忙一下吗？

**Comment by GallonHu** [comment]
> @jiaozhusos 你好，麻烦问一下， 使用BaiduCN1.2k Model，是如何设置manifest的呢？你解决了吗？
> 我想跑demo_server.py，但是这个warmup_manifest参数不知道如何来设置，能帮忙一下吗？

把那一部分注释掉
