### ISSUE TITLE
百度SDK

### ISSUE THREAD

**Issue by Sundy1219** [PaddlePaddle/DeepSpeech#253]
请问百度AI开放平台中的中文语音识别SDK,是采用deepspeech2的框架吗？多谢

**Comment by pkuyym** [comment]
这里的实现跟SDK没有太大关系

**Comment by Sundy1219** [comment]
很感谢你的回复，我的意思是：百度SDK,中采用语音识别模型是声学模型采用汉字建模，＋kenlm+ctc beam_search解码方案吗？＠ pkuyym

**Comment by pkuyym** [comment]
@Sundy1219 具体不是很清楚，工业上基于phone特征的方案可能更多一些

**Comment by Sundy1219** [comment]
那还得基于wfst解码吧？＠pkuyym

**Comment by pkuyym** [comment]
可以参考这个 https://github.com/PaddlePaddle/models/blob/develop/fluid/DeepASR/decoder/post_decode_faster.cc

**Comment by Sundy1219** [comment]
基于wfst这种解码方案，我已经搞定了。我现在就想知道以汉字建模以及用ctc beam_search+kenlm解码方案比wfst解码方案有没有优势？＠pkuyym

**Comment by nashannashui** [comment]
@Sundy1219  针对中文 这个得根据具体场景来看 你说的这个问题是和建模粒度相关 一般来说ci-phone/cd-phone/syallbel都需要wfst构图进行解码 基于单字不需要 也是这个项目用的方案 我们自己做实验发现 在数据接近1万小时左右 这几种建模粒度能达到得效果都差不多 如果数据小得做实验看 选那种建模粒度好 解码速度的话 一般建模粒度越大 速度越快

**Comment by Sundy1219** [comment]
你好，我最近将基于声韵母建模，以wfst为解码器的方案和你们现在的方案在性能上对比了一下，发现beam search 方案比以wfst为解码器的方案wer高3个点，数据是我们内部的数据，大概八百个小时，解码速度相差不大。我发现beam search 方案在运行时，相比WFST，挺耗CPU的，不知你们是否也是如此。另外有些想法，ngram语言模型，对于大词汇语音识别来说，构建起来实在太大，有没有可能在beam search打分的时候将ngram换成神经网络语言模型，或者将两者进行插值，将神经网络语言模型作为通用语言模型，将N-gram作为domain语言模型，当然这可能会增加计算量，解码时间。不知道你们对此可有些想法，希望可以交流交流，谢谢＠ nashannashui
