### ISSUE TITLE
hl_cuda_cudnn.cc:251] Check failed: CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 3) Cudnn Error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by krishnamohan191** [PaddlePaddle/DeepSpeech#254]
When use_gpu is False issue is not observed.
But when use_gpu is True below issue is observed.
Can you please tell me why this is happening.

Issue summary:
F0613 11:34:18.334713  1145 hl_cuda_cudnn.cc:251] Check failed: CUDNN_STATUS_SUCCESS == cudnnStat (0 vs. 3) Cudnn Error: CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f184d74304d  google::LogMessage::Fail()
    @     0x7f184d745398  google::LogMessage::SendToLog()
    @     0x7f184d742b5b  google::LogMessage::Flush()
    @     0x7f184d74626e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f184d6e4290  hl_conv_workspace()
    @     0x7f184d37b6e7  paddle::ConvBaseProjection::reshape()
    @     0x7f184d37960b  paddle::ConvProjection::forward()
    @     0x7f184d345df9  paddle::CudnnConvBaseLayer::forward()
    @     0x7f184d3d09ff  paddle::NeuralNetwork::forward()
    @     0x7f184d1caf46  _wrap_GradientMachine_forward
    @           0x4bc3fa  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4d54b9  (unknown)
    @           0x4eebee  (unknown)
    @           0x4a577e  PyObject_Call
    @           0x4c5e10  PyEval_CallObjectWithKeywords
During startup program terminated with signal SIGABRT, Aborted.

**Comment by krishnamohan191** [comment]
I had to extend the code for multiple clients using multi-threading.
When I call AsrRequestHandler.handle() function using Threads and use_gpu = False, it's working well enough.
When I call AsrRequestHandler.handle() function using Threads and use_gpu = True, SIGABRT happening.
Even when single thread launches a handle() function with gpu=true, the behavior is SIGABRT.
It seems Paddle code is not Thread-safe when gpu=True.

**Comment by kuke** [comment]
It should be the problem of using cudnn in multiple threading

**Comment by krishnamohan191** [comment]
Is there any solution to make cudnn calls to be thread-safe?
