### ISSUE TITLE
is Transfer Learning possible with Baidu En model

### ISSUE THREAD

**Issue by saibharani** [PaddlePaddle/DeepSpeech#256]
Can we use Transfer Learning on Baidu English model and make speech recognition for other languages.
Thank you.

**Comment by kuke** [comment]
I believe yes we can. But we haven't trained a model by using transfer learning. Just have a try, please.

**Comment by viig99** [comment]
@saibharani any luck with transfer learning, have you tried to adapt the model to indian accents ?

**Comment by saibharani** [comment]
Transfer learning seems to yield better results than directly trained models
