### ISSUE TITLE
Where is our own model?

### ISSUE THREAD

**Issue by RongerSnow** [PaddlePaddle/DeepSpeech#261]
I wonder whether we will get models that end with tar.gz if we train our own model. Because I only get 20 files in checkpoint directory that end with .tar.gz instead of .klm.

**Comment by frozenfires** [comment]
Only Speech Model we can train

**Comment by RongerSnow** [comment]
Emmm do you know why we can not download the perfect model? When I want to run the command "sh run_infer_golden.sh", I will always get an error called "ERROR 502: Bad Gateway."
