### ISSUE TITLE
下载 BaiduCN1.2k Model 直接报 502 错误，跟#301那个错误不一样

### ISSUE THREAD

**Issue by JinmingZhao** [PaddlePaddle/DeepSpeech#263]
网页直接点击链接，会直接502。
如果是执行 models/aishell/download_model.sh  的话会报如下错误 ，IP可以ping通，下面也显示connected。 跟#301那个错误不一样，我添加之后也还是一样的错误。比较着急用，麻烦各位大佬回复一下。
--2018-07-23 12:18:01--  http://cloud.dlnel.org/filepub/?uuid=499569a6-0025-4f40-83e6-1c99527431a6
Resolving cloud.dlnel.org (cloud.dlnel.org)... 180.76.189.142
Connecting to cloud.dlnel.org (cloud.dlnel.org)|180.76.189.142|:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2018-07-23 12:18:01 ERROR 502: Bad Gateway.

**Comment by mp-lu** [comment]
同問 中文語言模型都報502 error
使用sh檔 或 直接從readme網址下載都一樣

**Comment by JinmingZhao** [comment]
现在可以了

**Comment by huntzhan** [comment]
@JinmingZhao hi, 请问 speech model BaiduCN1.2k Model 可以 share 一下吗
