### ISSUE TITLE
识别aishell中test语音文件正常,识别自己的wav文件就完全不对

### ISSUE THREAD

**Issue by zhouyikang** [PaddlePaddle/DeepSpeech#273]
文件我看都是16khz和16位的,  我自己的文件基本识别不出来

-----------  Configuration Arguments -----------
alpha: 2.6
beam_size: 500
beta: 5.0
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: 0.0.0.0
host_port: 8086
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: data/aishell/mean_std.npz
model_path: checkpoints/aishell/params.latest.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: False
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: True
vocab_path: data/aishell/vocab.txt
warmup_manifest: data/aishell/manifest.test
------------------------------------------------

**Comment by sunjunlishi** [comment]
why ？is ok

**Comment by sunjunlishi** [comment]
16k 32bit的吗，我看他们都这样说的

**Comment by sunjunlishi** [comment]
纠结中。。。

**Comment by sunjunlishi** [comment]
@zhouyikang 你好我们可以联系下吗，我也是如此的问题。

**Comment by hui001** [comment]
请问这个原因搞清楚了么？
