### ISSUE TITLE
语言模型Mandarin LM Small	下载失败

### ISSUE THREAD

**Issue by uestc-lfs** [PaddlePaddle/DeepSpeech#274]
文件名：zh_giga.no_cna_cmn.prune01244.klm
文件大小2.8G，每次执行
`sh run_infer.sh`
都只能下载400多M

网页访问下载链接结果如下
![image](https://user-images.githubusercontent.com/18738958/44502451-1fac8180-a6c4-11e8-955b-0ff2cd12b0fe.png)

**Comment by zhouyikang** [comment]
在etc/hosts 文件 增加 180.76.189.142 cloud.dlnel.org 一行就可以
