### ISSUE TITLE
demo_server.py默认换成Aishell后执行报错

### ISSUE THREAD

**Issue by 18811737901** [PaddlePaddle/DeepSpeech#283]
/data/DeepSpeech2/deploy$ CUDA_VISIBLE_DEVICES=0 python2 demo_server.py --host_ip localhost --host_port 8086 --use_gpu False
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: /data/DeepSpeech2/models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: /data/DeepSpeech2/models/aishell/mean_std.npz
model_path: /data/DeepSpeech2/checkpoints/aishell/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: /data/DeepSpeech2/gintong
use_gpu: 0
use_gru: False
vocab_path: /data/DeepSpeech2/models/aishell/vocab.txt
warmup_manifest: /data/DeepSpeech2/data/aishell/manifest.test
------------------------------------------------
I0927 15:58:18.889097  2591 Util.cpp:166] commandline:  --use_gpu=0 --trainer_count=1 
W0927 15:58:18.889184  2591 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
[INFO 2018-09-27 15:58:18,964 layers.py:2716] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-09-27 15:58:18,966 layers.py:3361] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-09-27 15:58:18,967 layers.py:7533] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-09-27 15:58:18,968 layers.py:2716] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-09-27 15:58:18,969 layers.py:3361] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-09-27 15:58:18,971 layers.py:7533] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-09-27 15:58:26,537 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-09-27 15:58:26,657 model.py:253] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2018-09-27 15:58:26,657 model.py:254] end initializing scorer
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'/data/.cache/paddle/dataset/speech/Aishell/data_aishell/wav/test/S0913/BAC009S0913W0419.wav')
Traceback (most recent call last):
  File "demo_server.py", line 215, in <module>
    main()
  File "demo_server.py", line 211, in main
    start_server()
  File "demo_server.py", line 195, in start_server
    num_test_cases=3)
  File "demo_server.py", line 135, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "demo_server.py", line 171, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/data/DeepSpeech2/deploy/../model_utils/model.py", line 193, in infer_batch_probs
    output_layer=self._log_probs, parameters=self._parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 64, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___recurrent_layer_0__.w0

**Comment by Slyne** [comment]
share_rnn_weights: False

**Comment by liuborama** [comment]
The same error, @Slyne ,  your advice doesn't work for me.

**Comment by wiboson** [comment]
@liuborama Have you solved this problem? I have encountered the same problem。Thank you
