### ISSUE TITLE
Fail in example/tiny run_infer_golden.sh

### ISSUE THREAD

**Issue by Vincent-Zh** [PaddlePaddle/DeepSpeech#284]
After reading LM model (successfully), then error occurs. 

root@7a87c4436d18:~/DeepSpeech/examples/tiny# sh run_infer_golden.sh 
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: wer
infer_manifest: data/tiny/manifest.test-clean
lang_model_path: models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: models/librispeech/mean_std.npz
model_path: models/librispeech/params.tar.gz
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 1
specgram_type: linear
trainer_count: 1
use_gpu: 0
use_gru: 0
vocab_path: models/librispeech/vocab.txt
------------------------------------------------
I1009 19:13:51.660266   442 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_batch=True --trainer_count=1 
[INFO 2018-10-09 19:13:51,872 layers.py:2716] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-09 19:13:51,873 layers.py:3361] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-09 19:13:51,874 layers.py:7533] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-09 19:13:51,874 layers.py:2716] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-09 19:13:51,875 layers.py:3361] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-09 19:13:51,875 layers.py:7533] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-09 19:13:54,459 model.py:243] begin to initialize the external scorer for decoding
Loading the LM will be faster if you build a binary file.
Reading models/lm/common_crawl_00.prune01111.trie.klm
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
terminate called after throwing an instance of 'util::EndOfFileException'
  what():  End of file Byte: 0
*** Aborted at 1539112434 (unix time) try "date -d @1539112434" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1ba) received by PID 442 (TID 0x7f704cc49700) from PID 442; stack trace: ***
    @     0x7f704c826390 (unknown)
    @     0x7f704c480428 gsignal
    @     0x7f704c48202a abort
    @     0x7f703388684d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f70338846b6 (unknown)
    @     0x7f7033884701 std::terminate()
    @     0x7f7033884969 __cxa_rethrow
    @     0x7f702102d2f8 lm::ngram::detail::GenericModel<>::InitializeFromARPA()
    @     0x7f702102f0eb lm::ngram::detail::GenericModel<>::GenericModel()
    @     0x7f7021026aab lm::ngram::LoadVirtual()
    @     0x7f702113ecbf Scorer::load_lm()
    @     0x7f70211422a1 Scorer::setup()
    @     0x7f702114239d Scorer::Scorer()
    @     0x7f70210fd1a8 _wrap_new_Scorer
    @           0x4bc3fa PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4c15bf PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4ee7f6 (unknown)
    @           0x4aa9ab (unknown)
    @           0x4c15bf PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4c1e6f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
Aborted (core dumped)
Failed in inference!

**Comment by Laxmikant04** [comment]
Hi @Vincent-Zh ,

I am getting  this issue , How you fixed it ?
