### ISSUE TITLE
Training aborted due to the presence of an empty audio . 

### ISSUE THREAD

**Issue by praveenjune17** [PaddlePaddle/DeepSpeech#290]
Audio which has **no word spoken in it can disrupt the training process**. So before training ensure that the empty audios are removed. I used the below piece of code to identify the empty audios..

import soundfile as sf
data, samplerate = sf.read('any_file.wav')

if sum(data) == 0:
    remove the audio from the training sample

**Comment by sivagururaman** [comment]
Hi,
Can you please point me to the site from where you downloaded the language model?
common_crawl_00.prune01111.trie.klm is not available at the path mentioned in the script.

**Comment by praveenjune17** [comment]
This is the link I used to download the language model.

http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/en/deduped/en.00.deduped.xz

I was able to download it from this site.

**Comment by sivagururaman** [comment]
Thanks! Do I need to then perform any post process on this file to get the language model?

**Comment by praveenjune17** [comment]
you just need the .klm file . It should be inside the download
