### ISSUE TITLE
运行infer.py时报错: ValueError: No such parameter ___conv_0__.w0

### ISSUE THREAD

**Issue by jayxioresearch** [PaddlePaddle/DeepSpeech#291]
运行infer.py时报错，不知道是否与自制的语言模型有关。从输出中看，好像语言模型已经被成功读入了，谢谢。
python infer.py --use_gpu False --trainer_count 1
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: wer
infer_manifest: /home/xio/Baidu/BDeepSpeech2/amol.manifest
lang_model_path: /home/xio/Baidu/BDeepSpeech2/speech_model/lm3.binary
mean_std_path: /home/xio/Baidu/BDeepSpeech2/speech_model/mean_std.npz
model_path: /home/xio/Baidu/BDeepSpeech2/speech_model/baidu_en8k_model.tar.gz
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 1
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
trainer_count: 1
use_gpu: 0
use_gru: False
vocab_path: /home/xio/Baidu/BDeepSpeech2/speech_model/vocab.txt
------------------------------------------------
I1029 20:57:05.445317  6422 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_batch=True --trainer_count=1
[INFO 2018-10-29 20:57:05,494 layers.py:2716] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-29 20:57:05,495 layers.py:3361] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-29 20:57:05,495 layers.py:7533] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-10-29 20:57:05,496 layers.py:2716] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-29 20:57:05,497 layers.py:3361] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-29 20:57:05,497 layers.py:7533] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-10-29 20:57:06,238 model.py:243] begin to initialize the external scorer for decoding
[INFO 2018-10-29 20:57:06,571 model.py:253] language model: is_character_based = 0, max_order = 5, dict_size = 23264
[INFO 2018-10-29 20:57:06,571 model.py:254] end initializing scorer
[INFO 2018-10-29 20:57:06,571 infer_jay.py:103] start inference ...
Traceback (most recent call last):
 File "infer_jay.py", line 135, in <module>
   main()
 File "infer_jay.py", line 131, in main
   infer()
 File "infer_jay.py", line 105, in infer
   feeding_dict=data_generator.feeding)
 File "/home/xio/Baidu/BDeepSpeech2/DeepSpeech/model_utils/model.py", line 193, in infer_batch_probs
   output_layer=self._log_probs, parameters=self._parameters)
 File "/home/xio/venv/py27/local/lib/python2.7/site-packages/paddle/v2/inference.py", line 64, in __init__
   val.copyFromNumpyArray(parameters.get(name).flatten())
 File "/home/xio/venv/py27/local/lib/python2.7/site-packages/paddle/v2/parameters.py", line 242, in get
   return self.__getitem__(key=parameter_name)
 File "/home/xio/venv/py27/local/lib/python2.7/site-packages/paddle/v2/parameters.py", line 186, in __getitem__
   return self.__getter_inner(key, api.PARAMETER_VALUE)
 File "/home/xio/venv/py27/local/lib/python2.7/site-packages/paddle/v2/parameters.py", line 153, in __getter_inner
   shape = self.get_shape(key)
 File "/home/xio/venv/py27/local/lib/python2.7/site-packages/paddle/v2/parameters.py", line 200, in get_shape
   raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___conv_0__.w0

**Comment by ericput** [comment]
baidu_en8k的参数与librispeech的参数不同，因该参照examples/baidu_en8k/下的设置

**Comment by sruteesh-pivot** [comment]
`use_gru =True` if you're running baidu_en8k model

**Comment by jayxioresearch** [comment]
谢谢ericput和sruteesh-pivot 的回复。我参照“examples/baidu_en8k/run_infer_golden.sh"从新更改了参数，还是报一样的错。我猜测可能是我系统安装有问题，就按照建议下载了docker image，可是在docker image中运行"example/tiny"报了其他的错。请参照issues #129. 谢谢。

**Comment by nicole-zhao** [comment]
这个错可能是你模型的问题，别用下载的模型，你自己重新训练个模型试一下
