### ISSUE TITLE
中文语言模型下载1.01G就停止下载了，在/etc/hosts添加180.76.189.142 cloud.dlnel.org也尝试了，还是不行，可以解决一下吗？非常感谢

### ISSUE THREAD

**Issue by MrCuiHao** [PaddlePaddle/DeepSpeech#295]
sh download_lm_ch.sh
Download language model ...
download_lm_ch.sh: 8: [: 29e02312deb2e59b3c8686c7966d4fe3: unexpected operator
--2018-12-24 23:30:49--  http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37
Connecting to 127.0.0.1:8118... connected.
Proxy request sent, awaiting response... 200 OK
Cookie coming from cloud.dlnel.org attempted to set domain to baidu.com
Length: unspecified [text/html]
Saving to: ‘./zh_giga.no_cna_cmn.prune01244.klm’

./zh_giga.no_cna_cm     [       <=>          ]   1.01G  2.74MB/s    in 7m 19s  

2018-12-24 23:38:23 (2.36 MB/s) - ‘./zh_giga.no_cna_cmn.prune01244.klm’ saved [1087364578]

download_lm_ch.sh: 20: [: 29e02312deb2e59b3c8686c7966d4fe3: unexpected operator

**Comment by MrCuiHao** [comment]
可以了，我把shadowsocks关了就可以了，不知道什么原因，猛速下载中

**Comment by blood0708** [comment]
请问楼上的，具体是怎么解决的啊？怎么关闭shadowsocks

**Comment by blood0708** [comment]
我也遇到同样的问题，很郁闷

**Comment by MrCuiHao** [comment]
你在/etc/hosts添加180.76.189.142 cloud.dlnel.org了吗？添加完不要忘记networking restart

**Comment by blood0708** [comment]
感谢兄弟，添加了之后，可以了

**Comment by whaozl** [comment]
不能用代理上网，另外，添加/etc/hosts就行

**Comment by aaronlyt** [comment]
请问可以共享个语言模型么，现在好像被禁止了404

**Comment by huntzhan** [comment]
@MrCuiHao @blood0708 @whaozl @aaronlyt 🙏🙏🙏 官方下载链接失效了，可以帮忙云盘共享一下中文预训练模型吗？

**Comment by huntzhan** [comment]
@whaozl 刚试过了，报错“任务地址不存在“

**Comment by whaozl** [comment]
我的可以

**Comment by kuke** [comment]
Hi All，语言模型和预训练模型的url已更新，请重新尝试下载
