### ISSUE TITLE
有谁实验过，识别的效果怎么样阿？

### ISSUE THREAD

**Issue by blood0708** [PaddlePaddle/DeepSpeech#297]

**Comment by blood0708** [comment]
用 badi_cn1.2的模型识别效果不是一般的差阿

**Comment by liuborama** [comment]
@blood0708 麻烦问一下用 badi_cn1.2时候，参数方便贴一下吗？我这还没跑通，谢谢了

**Comment by tai960519073** [comment]
> 用 badi_cn1.2的模型识别效果不是一般的差阿

我目前的测试结果，安静的环境下识别效果还可以，但是真实语音通话环境下，效果很差

**Comment by YanqiangWang** [comment]
很差很差
