### ISSUE TITLE
使用docker训练时报错Check failed: cudaSuccess == err (0 vs. 8)

### ISSUE THREAD

**Issue by zongweiLi** [PaddlePaddle/DeepSpeech#302]
F0123 11:55:36.803860    19 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @     0x7fbf82b2a04d  google::LogMessage::Fail()
    @     0x7fbf82b2c398  google::LogMessage::SendToLog()
    @     0x7fbf82b29b5b  google::LogMessage::Flush()
    @     0x7fbf82b2d26e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbf8296d9df  hl_gpu_apply_unary_op<>()
    @     0x7fbf8296de1f  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7fbf8296e0e8  paddle::BaseMatrixT<>::zero()
    @     0x7fbf828de8b4  paddle::GpuMatrix::zeroMem()
    @     0x7fbf8278e421  paddle::BatchNormBaseLayer::init()
    @     0x7fbf8272fa62  paddle::CudnnBatchNormLayer::init()
    @     0x7fbf827b5d78  paddle::NeuralNetwork::init()
    @     0x7fbf827c938a  paddle::MultiGradientMachine::MultiGradientMachine()
    @     0x7fbf827ce1de  paddle::GradientMachine::create()
    @     0x7fbf82afa8bb  GradientMachine::createFromPaddleModelPtr()
    @     0x7fbf82afb4ce  GradientMachine::createByConfigProtoStr()
    @     0x7fbf825e23aa  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4cb45e  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4de8b8  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4f492e  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4f46a7  (unknown)
    @           0x4b670c  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4c9faf  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
Aborted (core dumped)
Failed in training!

**Comment by SunlerZRY** [comment]
Have you fixed the problwm? I met the same problem.

**Comment by djangogo** [comment]
The same problem....
