### ISSUE TITLE
Test pre-trained EN model on a .wav file 

### ISSUE THREAD

**Issue by Cloud299** [PaddlePaddle/DeepSpeech#308]
Hi there,

I just finished installing the DeepSpeech and I'm very curious about BaiduEN8k Model's performance versus Google STT on some of my test .wav files. How do I use this model to decode/transcribe a wavfile named "test.wav" ? 

Thank you

**Comment by rhamnett** [comment]
did you try this?

**Comment by Cloud299** [comment]
I have not been able to test the BaiduEN8k Model. Keep getting error when trying to run "sh run_test_golden.sh"

**Comment by rhamnett** [comment]
What error? you need to convert to flac and then add it to your own manifest and specify that manifest in the .sh

**Comment by Cloud299** [comment]
When running "sh run_data.sh", I get

`
 Traceback (most recent call last):
  File "data/librispeech/librispeech.py", line 19, in <module>
    from data_utils.utility import download, unpack
  File "DeepSpeech/data_utils/utility.py", line 14, in <module>
    from paddle.v2.dataset.common import md5file
ImportError: No module named v2.dataset.common `

**Comment by Cloud299** [comment]
Also, when I do "sh run_infer_golden.sh" from /DeepSpeech/examples/baidu_en8k/, I get:

`Download language model ...
../../utils/utility.sh: line 7: md5sum: command not found
../../utils/utility.sh: line 8: [: 099a601759d467cd0a8523ff939819c5: unary operator expected
--2019-03-27 18:32:14--  http://paddlepaddle.bj.bcebos.com/model_zoo/speech/common_crawl_00.prune01111.trie.klm
Resolving paddlepaddle.bj.bcebos.com (paddlepaddle.bj.bcebos.com)... 103.235.46.61
Connecting to paddlepaddle.bj.bcebos.com (paddlepaddle.bj.bcebos.com)|103.235.46.61|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-27 18:32:16 ERROR 404: Not Found.`

**Comment by rhamnett** [comment]
I saw that at some point i think. Try running all the tiny examples first in examples/tiny

**Comment by rhamnett** [comment]
for md5sum are you running on mac? might want to comment out that section or try alias md5sum=md5

**Comment by Cloud299** [comment]
> I saw that at some point i think. Try running all the tiny examples first in examples/tiny

I tried the tiny example (running on Mac) and got `Traceback (most recent call last):
  File "data/librispeech/librispeech.py", line 19, in <module>
    from data_utils.utility import download, unpack
  File "/Users/shiba/Desktop/callbox/work/DeepSpeech/data_utils/utility.py", line 14, in <module>
    from paddle.v2.dataset.common import md5file
ImportError: No module named v2.dataset.common
Prepare LibriSpeech failed. Terminated.
`

**Comment by rhamnett** [comment]
I suggest you use the docker image for the most chance of getting it working.

**Comment by Cloud299** [comment]
> I suggest you use the docker image for the most chance of getting it working.

Is there a way to run docker without nvidia gpu ?
