### ISSUE TITLE
语言模型下载链接出问题

### ISSUE THREAD

**Issue by aaronlyt** [PaddlePaddle/DeepSpeech#317]
网站未备案，暂时无法访问
该网站可能未进行备案或未完成转入百度云备案。根据工信部相关法规要求进行阻断显示。

请网站管理员尽快登录 百度云备案系统 根据法规要求完成备案。

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/DeepSpeech/pull/322 现已修复这个问题了
