### ISSUE TITLE
中文语言模型的衔接失效了吗？

### ISSUE THREAD

**Issue by ksellesk** [PaddlePaddle/DeepSpeech#32]
英文的可以，中文的下不下来。

**Comment by pkuyym** [comment]
Already fixed, please try again.

**Comment by zh794390558** [comment]
@pkuyym 能给出 LM 的 md5 吗？

**Comment by pkuyym** [comment]
@zh794390558 Your problem maybe relate to this issue https://github.com/PaddlePaddle/models/issues/301

**Comment by zh794390558** [comment]
@pkuyym It's work! Thanks.

**Comment by ksellesk** [comment]
Solved！
Thx so much.
