### ISSUE TITLE
How to run infer.py?

### ISSUE THREAD

**Issue by wshhja** [PaddlePaddle/DeepSpeech#323]
I ran the infer.py as follow:
python -u infer.py \
--use_gru=True \
--use_gpu=False \
--share_rnn_weights=False \
--infer_manifest='data/aishell/manifest.test' \
--mean_std_path='mean_std.npz' \
--vocab_path='vocab.txt' \
--model_path='params.tar.gz' \
--lang_model_path='zh_giga.no_cna_cmn.prune01244.klm' \

The params above are:
--infer_manifest='data/aishell/manifest.test' \   --------created by run example/aishell/run_data.sh
--mean_std_path='mean_std.npz' \  -------unzip from the speech model's compressed package(baidu_cn1.2k_model.tar.gz).
--vocab_path='vocab.txt' \   -------unzip from the speech model's compressed package(baidu_cn1.2k_model.tar.gz).
--model_path='params.tar.gz' \   -------unzip from the speech model's compressed package(baidu_cn1.2k_model.tar.gz).
--lang_model_path='zh_giga.no_cna_cmn.prune01244.klm' \`   -------the downloading language model

But it doesn't work and the console output remains as follow:
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: wer
infer_manifest: data/aishell/manifest.test
lang_model_path: zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: mean_std.npz
model_path: params.tar.gz
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 0
specgram_type: linear
trainer_count: 8
use_gpu: 0
use_gru: 1
vocab_path: vocab.txt
------------------------------------------------
I0423 22:42:26.985620 154393 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_batch=True --trainer_count=8 

How can i fixed this problems?Thanks.

**Comment by wshhja** [comment]
My paddle version is:
`PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: OFF
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF`

**Comment by wshhja** [comment]
Today,i run the infer.py via paddlepaddle-gpu(0.11.0).The script is:python -u infer.py \
--use_gru=True \
--use_gpu=True \
--share_rnn_weights=False \
--infer_manifest='data/aishell/manifest.test' \
--mean_std_path='mean_std.npz' \
--vocab_path='vocab.txt' \
--model_path='baidu_cn1.2k_model.tar.gz' \
--lang_model_path='zh_giga.no_cna_cmn.prune01244.klm' \

But the console output is the same as yesterday.

And,i want to know weather my model_path param is rigth.
Thanks

**Comment by AshishKarel** [comment]
Maybe try reducing the batch size
