### ISSUE TITLE
paddle related errors paddle.v2 and paddle.init

### ISSUE THREAD

**Issue by liuborama** [PaddlePaddle/DeepSpeech#327]
I fount the paddle has updated a lot.  we can't import paddle.v2 now .
If I change from paddle.v2 to paddle, then we will find the paddle.init 
can't find too.
We can't use train.py and infer.py because of this.
Does anyone find the solution for this paddle upgrade issue? Can anyone help?

**Comment by saibharani** [comment]
remove existing paddle version using command
sudo pip uninstall paddlepaddle-gpu
and install old deepspeech supported version for cuda 9.x and cudnn 7
sudo pip install paddlepaddle-gpu==1.2.0-post97
for cuda 8.x and cudnn 7
sudo pip install paddlepaddle-gpu==1.2.0-post87

**Comment by ulimmeh** [comment]
Any update on this? I keep getting the error `ModuleNotFoundError: No module named 'paddle.v2'`, when I run the deploy/demo_server.py script. Also, '`pip install paddle.v2`' doesn't work in anaconda command prompt.

**Comment by tylercollins590** [comment]
@ulimmeh did you ever get this figured out?

**Comment by fizzafarooq08** [comment]
@saibharani Is there any older paddle version for cuda10.2 and cudnn7 ? that will run with paddle.v2
