### ISSUE TITLE
下载预训练模型失败，502问题

### ISSUE THREAD

**Issue by YasinZhao** [PaddlePaddle/DeepSpeech#328]
你好，查看issue时有见到说下载链接问题已经解决了，但是我这里还是存在502问题，可以烦请官方人员帮忙看看吗，谢谢~

Download LibriSpeech model ...
download_model.sh: 8: [: 1f72d0c5591f453362f0caa09dd57618: unexpected operator
--2019-05-13 08:31:58--  http://cloud.dlnel.org/filepub/?uuid=117cde63-cd59-4948-8b80-df782555f7d6
Resolving cloud.dlnel.org (cloud.dlnel.org)... 115.239.210.226
Connecting to cloud.dlnel.org (cloud.dlnel.org)|115.239.210.226|:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
Cookie coming from cloud.dlnel.org attempted to set domain to baidu.com
2019-05-13 08:32:01 ERROR 502: Bad Gateway.

Fail to download LibriSpeech model!

**Comment by kuke** [comment]
Fixed by https://github.com/PaddlePaddle/DeepSpeech/pull/333

请更新下载模型的脚本
