### ISSUE TITLE
how to solve cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed]

### ISSUE THREAD

**Issue by wegamekinglc** [PaddlePaddle/DeepSpeech#330]
I run the examples/tiny from the docker image. My machine is equipped with 4 GTX 2080Ti gpu

**Comment by sumeet559** [comment]
I faced the same thing using CUDA 10.1 . Also nividia-docker seems to be deprecated. Can you please help regarding this.
Or update documentation.

**Comment by roywangtj** [comment]
I also faced same error when using  GTX2080, but same code and same driver/cuda version, nothing error was gone.
Why? please official dev give use detailed answer.
Maybe related paddle and cuda version.
