### ISSUE TITLE
cannot import name md5file

### ISSUE THREAD

**Issue by tai960519073** [PaddlePaddle/DeepSpeech#331]
from paddle.v2.dataset.common import md5file
导入报错，查看官网，老版本文档api没法看，新版本没找到 md5file。请问，最新的版本中怎么导入？

**Comment by SunlerZRY** [comment]
将这句话替换为import paddle.dataset.common.md5file，即可

**Comment by hsauod** [comment]
@tai960519073  哈喽你好，我跟你同样的原因，importError: No module named dataset.common
,请问你还记得当时怎么解决的吗？多谢多谢
