### ISSUE TITLE
BaiduCN1.2k Model的音频采样率、位深度、声道是什么啊

### ISSUE THREAD

**Issue by QAQ1551QAQ** [PaddlePaddle/DeepSpeech#332]
百度提供的BaiduCN1.2k Model所使用的音频采样率、位深度、声道是什么啊

![image](https://user-images.githubusercontent.com/50564800/59178674-3f992d00-8b92-11e9-9bcc-97ee3576eff3.png)

**Comment by tai960519073** [comment]
> 百度提供的BaiduCN1.2k Model所使用的音频采样率、位深度、声道是什么啊
> 
> ![image](https://user-images.githubusercontent.com/50564800/59178674-3f992d00-8b92-11e9-9bcc-97ee3576eff3.png)

同问，我也想知道。直接使用这个模型正确率基本为0

**Comment by wegamekinglc** [comment]
采样率是8k，这个好像要注意一下。改好了，正确率就还好

**Comment by tai960519073** [comment]
> 采样率是8k，这个好像要注意一下。改好了，正确率就还好

嗯，更改8k后正确率确实提高了。不过使用BaiduCN1.2k README.md文件中的参数设置后，发现识别的结果会“过度矫正”，比如“中国工商银行”，识别为“新中国工商银行”，其它结果类似。使用AISHELL模型反而会好一些。
请问，apla，beta等参数需要怎么改？多谢了

**Comment by QAQ1551QAQ** [comment]
采样率8k  位深度16和32位都可以，单声道。
--rnn_layer_size=2048 \
--alpha=1.15 \
--beta=0.15

**Comment by dxhgq-github** [comment]
请问，数字之类的比如2018年等为何识别不了，要用什么样的参数？

**Comment by tai960519073** [comment]
> 请问，数字之类的比如2018年等为何识别不了，要用什么样的参数？

我目前测试的结果是，数字能识别。但是，对音频质量要求太高了。。。

**Comment by dxhgq-github** [comment]
@tai960519073 谢谢

**Comment by nicole-zhao** [comment]
楼主，你用这两个大模型的错误率是多少呀？我用这两个测了几个aishell的测试集大概是0.5左右，测自己的数据就更差了，还没有用小模型测得好。。。

**Comment by wegamekinglc** [comment]
> 楼主，你用这两个大模型的错误率是多少呀？我用这两个测了几个aishell的测试集大概是0.5左右，测自己的数据就更差了，还没有用小模型测得好。。。
我也很关心这个问题，我们正在考虑自己测试一下

**Comment by tai960519073** [comment]
请问大家语音文件是怎么降噪的，干净的语音识别效果还可以，稍有噪音就比较差，谢谢了

**Comment by jasonlbx13** [comment]
> 请问大家语音文件是怎么降噪的，干净的语音识别效果还可以，稍有噪音就比较差，谢谢了

spleeter人声分离

**Comment by wuitson** [comment]
> > 请问，数字之类的比如2018年等为何识别不了，要用什么样的参数？
> 
> 我目前测试的结果是，数字能识别。但是，对音频质量要求太高了。。。

请问大神，数字能识别么，我这儿也识别不了。我看了vocab.txt里面根本就没有数字就一个1，其他都没有，怎么识别得了啊！求解，谢谢。

**Comment by ccbptm** [comment]
> 楼主，你用这两个大模型的错误率是多少呀？我用这两个测了几个aishell的测试集大概是0.5左右，测自己的数据就更差了，还没有用小模型测得好。。。

你好，请问你怎么用BaiduCN1.2k Model去测试aishell测试集的呀，我测试就是cer=1.000

**Comment by ccbptm** [comment]
> 楼主，你用这两个大模型的错误率是多少呀？我用这两个测了几个aishell的测试集大概是0.5左右，测自己的数据就更差了，还没有用小模型测得好。。。

aishell最开始的测试集是只有这么一点，但是如果用./tools/tune.py之后调整参数可用在aishell的测试集上cer在0.1左右
我想请教一下如何把BaiduCN1.2k Model用在aishell的测试集上去测试一下。我一配置就cer=1.000
