### ISSUE TITLE
Any plan to upgrade Baddle depency?

### ISSUE THREAD

**Issue by wegamekinglc** [PaddlePaddle/DeepSpeech#336]
Is there any plan to upgrade the paddle dependecy? Currently the project depends on a very old paddle version and python 2.7.

**Comment by nemo9903** [comment]
NO PLAN




------------------ Original ------------------

**Comment by kuke** [comment]
Done already. Please take a look at develop branch. Thanks

**Comment by wegamekinglc** [comment]
Thx
