### ISSUE TITLE
Error in training with predefined model

### ISSUE THREAD

**Issue by artinegi1607** [PaddlePaddle/DeepSpeech#337]
Hi, 
I am newbie to this. I just went through the ReadMe and started to follow it. 
When I start training the predefined model with tiny data via **"sh run_train.py"**,  I found the below error.

F0624 17:24:26.961547 14845 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: cudnn_conv
*** Check failure stack trace: ***
    @     0x7f4b04212eed  google::LogMessage::Fail()
    @     0x7f4b0421699c  google::LogMessage::SendToLog()
    @     0x7f4b04212a13  google::LogMessage::Flush()
    @     0x7f4b04217eae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4b03fd853b  paddle::Layer::create()
    @     0x7f4b03e99cd8  _ZZN6paddle13NeuralNetwork4initERKNS_11ModelConfigESt8functionIFviPNS_9ParameterEEERKSt6vectorINS_19enumeration_wrapper13ParameterTypeESaISB_EEbENKUlRKNS_11LayerConfigEE_clESI_
    @     0x7f4b03e9abff  paddle::NeuralNetwork::init()
    @     0x7f4b03e8f6c6  paddle::MultiGradientMachine::MultiGradientMachine()
    @     0x7f4b03e94f1f  paddle::GradientMachine::create()
    @     0x7f4b041ef935  GradientMachine::createFromPaddleModelPtr()
    @     0x7f4b041efb1f  GradientMachine::createByConfigProtoStr()
    @     0x7f4b03e4c857  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4c2e1e  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4d57a3  (unknown)
    @           0x4eef5e  (unknown)
    @           0x4eeb66  (unknown)
    @           0x4aaafb  (unknown)
    @           0x4c166d  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c17c6  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4c1f56  PyEval_EvalFrameEx
    @           0x4b9b66  PyEval_EvalCodeEx
    @           0x4eb69f  (unknown)
    @           0x4e58f2  PyRun_FileExFlags
Aborted (core dumped)
Fail in training!

Please help me!

**Comment by QAQ1551QAQ** [comment]
问同
我也是加载预训练模型训练的时候出错，--init_model_path = 'models/baiduCN/params.tar.gz'


I0626 07:27:05.990948  1586 Util.cpp:166] commandline:  --use_gpu=1 --rnn_use_batch=True --log_clipping=True --trainer_count=2 
[INFO 2019-06-26 07:27:07,147 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,148 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,148 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,149 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-06-26 07:27:07,150 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-06-26 07:27:07,150 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
I0626 07:27:26.776872  1586 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=2 numDevices=2
I0626 07:27:26.796452  1586 GradientMachine.cpp:94] Initing parameters..
I0626 07:27:29.301322  1586 GradientMachine.cpp:101] Init parameters done.
F0626 07:27:31.709532  1663 Vector.cpp:266] Check failed: src.getSize() == this->getSize() (8060928 vs. 4030464) 
*** Check failure stack trace: ***
F0626 07:27:31.712079  1659 Vector.cpp:266] Check failed: src.getSize() == this->getSize() (8060928 vs. 4030464) 
*** Check failure stack trace: ***
    @     0x7f30387ce04d  google::LogMessage::Fail()
    @     0x7f30387d0398  google::LogMessage::SendToLog()
    @     0x7f30387ce04d  google::LogMessage::Fail()
    @     0x7f30387d0398  google::LogMessage::SendToLog()
    @     0x7f30387cdb5b  google::LogMessage::Flush()
    @     0x7f30387d126e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f30387cdb5b  google::LogMessage::Flush()
    @     0x7f30385d3e3e  paddle::GpuVectorT<>::copyFrom()
    @     0x7f30387d126e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f303846aae4  paddle::TrainerThread::valueDispatchThread()
    @     0x7f30385d3e3e  paddle::GpuVectorT<>::copyFrom()
    @     0x7f30bf26bc80  (unknown)
    @     0x7f303846aae4  paddle::TrainerThread::valueDispatchThread()
    @     0x7f30c9a5b6ba  start_thread
    @     0x7f30c97913dd  clone
    @     0x7f30bf26bc80  (unknown)
    @     0x7f30c9a5b6ba  start_thread
    @              (nil)  (unknown)
Aborted (core dumped)
Failed in training!

**Comment by artinegi1607** [comment]
The error is resolved now.
I have reduced the batch_size to 8. Earlier it was 16. 
Now it is working fine.
