### ISSUE TITLE
在百度的BaiduCN1.2k Model基础上继续训练，出现错误 Check failed: src.getSize() == this->getSize() (8060928 vs. 4030464)

### ISSUE THREAD

**Issue by QAQ1551QAQ** [PaddlePaddle/DeepSpeech#339]
我也是加载预训练模型训练的时候出错，--init_model_path = 'models/baiduCN/params.tar.gz'

I0626 07:27:05.990948 1586 Util.cpp:166] commandline: --use_gpu=1 --rnn_use_batch=True --log_clipping=True --trainer_count=2
[INFO 2019-06-26 07:27:07,147 layers.py:2606] output for conv_0: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,148 layers.py:3133] output for batch_norm_0: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,148 layers.py:7224] output for scale_sub_region_0: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-06-26 07:27:07,149 layers.py:2606] output for conv_1: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-06-26 07:27:07,150 layers.py:3133] output for batch_norm_1: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-06-26 07:27:07,150 layers.py:7224] output for scale_sub_region_1: c = 32, h = 41, w = 54, size = 70848
I0626 07:27:26.776872 1586 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=2 numDevices=2
I0626 07:27:26.796452 1586 GradientMachine.cpp:94] Initing parameters..
I0626 07:27:29.301322 1586 GradientMachine.cpp:101] Init parameters done.
F0626 07:27:31.709532 1663 Vector.cpp:266] Check failed: src.getSize() == this->getSize() (8060928 vs. 4030464)
*** Check failure stack trace: ***
F0626 07:27:31.712079 1659 Vector.cpp:266] Check failed: src.getSize() == this->getSize() (8060928 vs. 4030464)
*** Check failure stack trace: ***
@ 0x7f30387ce04d google::LogMessage::Fail()
@ 0x7f30387d0398 google::LogMessage::SendToLog()
@ 0x7f30387ce04d google::LogMessage::Fail()
@ 0x7f30387d0398 google::LogMessage::SendToLog()
@ 0x7f30387cdb5b google::LogMessage::Flush()
@ 0x7f30387d126e google::LogMessageFatal::~LogMessageFatal()
@ 0x7f30387cdb5b google::LogMessage::Flush()
@ 0x7f30385d3e3e paddle::GpuVectorT<>::copyFrom()
@ 0x7f30387d126e google::LogMessageFatal::~LogMessageFatal()
@ 0x7f303846aae4 paddle::TrainerThread::valueDispatchThread()
@ 0x7f30385d3e3e paddle::GpuVectorT<>::copyFrom()
@ 0x7f30bf26bc80 (unknown)
@ 0x7f303846aae4 paddle::TrainerThread::valueDispatchThread()
@ 0x7f30c9a5b6ba start_thread
@ 0x7f30c97913dd clone
@ 0x7f30bf26bc80 (unknown)
@ 0x7f30c9a5b6ba start_thread
@ (nil) (unknown)
Aborted (core dumped)
Failed in training!

**Comment by Re-bin** [comment]
你好，可以问一下怎么用BaiduCN1.2k Model模型嘛，下载了之后要怎么使用，感谢

**Comment by QAQ1551QAQ** [comment]
> 你好，可以问一下怎么用BaiduCN1.2k Model模型嘛，下载了之后要怎么使用，感谢

修改train.py的参数，将--init_model_path 改为模型路径

**Comment by suntingfeng** [comment]
请问你这报错的问题解决了么？我也是在预训练模型基础上继续训练，也遇到了此问题。
@QAQ1551QAQ

**Comment by jchua127** [comment]
> 请问你这报错的问题解决了么？我也是在预训练模型基础上继续训练，也遇到了此问题。
> @QAQ1551QAQ

应该是你的vocab没有重新生成导致的

**Comment by llp123** [comment]
不使用预训练模型初始化最后一层参数，将最后一层参数数目定为你的vocab的数目

**Comment by springminhcm** [comment]
> 不使用预训练模型初始化最后一层参数，将最后一层参数数目定为你的vocab的数目

@llp123 您好，可否请教你说明一下具体的作法？我有去找你之前的文章，但看的不是很明白，例如，如何去删除最后一层参数？在*.tar.gz中，解开后有很多的档案，如___gru_5__.wbias.protobuf等，请问是要删那一个呢？

另外上述你所提到的将数目定为你的vocab的数目，是指你之前回覆文章时提到的“修改model.py中的_create_parameters()”这一段吗？

诚心请教 @llp123 大大，可否帮我解惑一下，真的麻烦你了~~~非常的感谢~

**Comment by llp123** [comment]
删除 ___fc_layer_6__.*，这几个是最后的全连接层的参数

**Comment by springminhcm** [comment]
> 删除 _**fc_layer_6**.*，这几个是最后的全连接层的参数

@llp123 真的非常感谢你的回覆，可否在帮忙一下，请问你上述提到的“将最后一层参数数目定为你的vocab的数目”这一部份如何做呢？是指修改model.py中的_create_parameters()”这一段吗？

**Comment by llp123** [comment]
@springminhcm 是的

**Comment by springminhcm** [comment]
@llp123 你好，回报一下，我改好后，以新增的语音档是可以训练了..... 但是结果有点惨，原本正确率有近70%，使用这个方式train后，正确率剩不到5% ....我想我可能有那里弄错吧？

**Comment by llp123** [comment]
@springminhcm 需要先训练，才可以做推理。并且原来的可以用为什么还要换？

**Comment by springminhcm** [comment]
@llp123您好，特别解释一下，我原本利用大约650小时，train一个模型，形成650HR.tar.gz档(这个档有近70%正确率)。但由于我之后会陆陆续续新增新的语音档来train，例如后面可能会陆续新增100小时、50小时、100小时之类。所以我希望能直接利用这650HR.tar.gz档，来做后续的训练，如只要针对新增的100小时来train。

只是目前我怎么试都试不出来，就会产生如Check failed: src.getSize() == this->getSize()的错误，我只能重头来train，只能用750小时(650+100)来重头train。

由于这样重头train，真的很耗时，所以我才会想询问有没有什么方式可以只针对新增的100小时train。
以上特别说明，非常感谢你的回覆，因我在别的讨论串中询问，官方人员都没回覆.....

**Comment by llp123** [comment]
@springminhcm 我说一下我的解决方式，首先建立一个包含基本常用汉字，数字，字幕等的字典，我的字典借鉴了百度预训练模型中的所有字符，以及自有数据涉及的字符，6000+，然后增加一个unk标记来标记未发现的字符。每次新增数据就可以只训练新增数据，而无需再次变动vocab。
