### ISSUE TITLE
请问输入的audio，该采用那一种格式呢？

### ISSUE THREAD

**Issue by stereomatchingkiss** [PaddlePaddle/DeepSpeech#340]
pocketsphinx的要求是

"single-channel (monaural), little-endian, unheadered 16-bit signed PCM audio file sampled at 16000 Hz". 

那么DeepSpeech的要求呢?谢谢

**Comment by jchua127** [comment]
具体没有要求，只要识别和训练的录音文件格式一致就好，Baidu1.2K模型用8K的效果比较好。
