### ISSUE TITLE
Which version of cuda is sutible for this project?

### ISSUE THREAD

**Issue by SunlerZRY** [PaddlePaddle/DeepSpeech#346]

**Comment by SunlerZRY** [comment]
I met the following problem, I'm not sure if there is somthing with cuda version.
![image](https://user-images.githubusercontent.com/45224648/62606731-67f19d80-b92f-11e9-9c92-6e8bb08dc52c.png)

**Comment by ssokhey** [comment]
If you have `CUDA 8` & `cuDNN 7.*` use the following command to install paddle;

`pip install paddlepaddle-gpu==0.11.0.post87`

For `CUDA 9` & `cuDNN 7.*`, use;

`pip install paddlepaddle-gpu==0.12.0.post97`

I have tested & worked on both!

PS: If you have multiple GPUs, make sure you explicitly mention the GPUs to use, like, `CUDA_VISIBLE_DEVICES=0,2`

**Comment by SunlerZRY** [comment]
Thanks！Did you use the docker provided by the author?

**Comment by SunlerZRY** [comment]
> If you have `CUDA 8` & `cuDNN 7.*` use the following command to install paddle;
> 
> `pip install paddlepaddle-gpu==0.11.0.post87`
> 
> For `CUDA 9` & `cuDNN 7.*`, use;
> 
> `pip install paddlepaddle-gpu==0.12.0.post97`
> 
> I have tested & worked on both!
> 
> PS: If you have multiple GPUs, make sure you explicitly mention the GPUs to use, like, `CUDA_VISIBLE_DEVICES=0,2`

**Comment by SunlerZRY** [comment]
> If you have `CUDA 8` & `cuDNN 7.*` use the following command to install paddle;
> 
> `pip install paddlepaddle-gpu==0.11.0.post87`
> 
> For `CUDA 9` & `cuDNN 7.*`, use;
> 
> `pip install paddlepaddle-gpu==0.12.0.post97`
> 
> I have tested & worked on both!
> 
> PS: If you have multiple GPUs, make sure you explicitly mention the GPUs to use, like, `CUDA_VISIBLE_DEVICES=0,2`

**Comment by SunlerZRY** [comment]
@ssokhey When I try to install paddlepaddle-gpu==0.12.0, there is recommondation that I must use python >=3.5, but this project need python 2.7. Do you meet this conflit? If so,how do you fix it? Thank you!

**Comment by ssokhey** [comment]
@SunlerZRY It works with Python 2.7 for me. Can you present some logs?

**Comment by shoegazerstella** [comment]
What about CUDA 10.1?
I have this error when running the `run_train.sh` from the examples
`PaddleCheckError: CUDNN_STATUS_INTERNAL_ERRORFailed to create Cudnn handle in DeviceContext at [/paddle/paddle/fluid/platform/device_context.cc:281]`
