### ISSUE TITLE
ModuleNotFoundError: No module named 'swig_decoders'

### ISSUE THREAD

**Issue by suntingfeng** [PaddlePaddle/DeepSpeech#347]
你好，安装swig已经成功安装，在pip list中也能看见，但是当使用python import swig_decoders的时候会报ModuleNotFoundError: No module named 'swig_decoders'错误，这个是什么原因导致的啊？ 谢谢！！！

**Comment by suntingfeng** [comment]
已经解决

**Comment by blackstrawlstm** [comment]
How did you resolve it? I am facing the same error

**Comment by ExpressGit** [comment]
你好 是怎么解决的

**Comment by suntingfeng** [comment]
你好，安装swig-decoders的时候需要注意系统swig的版本，如果swig版本较低需要安装高一点的版本，我使用的是3.0.12的版本

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: MK tank <notifications@github.com>
发送时间: Sunday, July 5, 2020 3:47:08 PM
收件人: PaddlePaddle/DeepSpeech <DeepSpeech@noreply.github.com>
抄送: suntingfeng <stf19900719@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [PaddlePaddle/DeepSpeech] ModuleNotFoundError: No module named 'swig_decoders' (#347)


你好 是怎么解决的

―

**Comment by zhangyifei1** [comment]
你好，大佬，请问下您是怎么解决这个问题的，目前已经被这个问题困扰几天了，非常期待您的回复、

**Comment by tongtongking** [comment]
我在通过Dockerfile构建的过程中也出现了类似的问题一直报：ModuleNotFoundError: No module named 'swig_decoders'，Dockerfile中安装命令是RUN git clone https://github.com/Slyne/ctc_decoder.git && cd ctc_decoder/swig && bash setup.sh这一行，bash setup.sh是一种比较老旧的安装方法（我有升级pip版本 pip install --update）,可以考虑改为：
RUN git clone https://github.com/Slyne/ctc_decoder.git && cd ctc_decoder/swig && pip install .
我是手动执行的命令执行完之后就没有再报错。
