### ISSUE TITLE
Why lookahead convolution is not implemented?

### ISSUE THREAD

**Issue by Jun-Fan** [PaddlePaddle/DeepSpeech#348]
In the original paper of [DeepSpeech2](https://arxiv.org/abs/1512.02595), **lookahead convolution** is introduced for unidirectional model to keep accuracy, lower the latency compared to bidirectional model. And the best English models in the paper is 3 layers of unidirectional GRU with lookahead convolution. So, it seems that lookahead convolution is great for real-time deploy, but why lookahead convolution is not implemented in this repository?

Thanks!

**Comment by gbxu** [comment]
it confuses me, too
