### ISSUE TITLE
请问什么时候会发布fluid的版本？谢谢

### ISSUE THREAD

**Issue by hui001** [PaddlePaddle/DeepSpeech#357]
@kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢

**Comment by onmywei** [comment]
同问~~
docker运行tune.py时候出现"Xbyak::Error"不知道什么情况

`root@e6ea63734dda:/DeepSpeech# python tools/tune.py 
-----------  Configuration Arguments -----------
alpha_from: 1.0
alpha_to: 3.2
batch_size: 256
beam_size: 500
beta_from: 0.1
beta_to: 0.45
cutoff_prob: 1.0
cutoff_top_n: 40
error_rate_type: wer
lang_model_path: models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: data/librispeech/mean_std.npz
model_path: ./checkpoints/libri/params.latest.tar.gz
num_alphas: 45
num_batches: -1
num_betas: 8
num_conv_layers: 2
num_proc_bsearch: 8
num_proc_data: 8
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
trainer_count: 8
tune_manifest: data/librispeech/manifest.dev-clean
use_gpu: True
use_gru: False
vocab_path: data/librispeech/vocab.txt
------------------------------------------------
terminate called after throwing an instance of 'Xbyak::Error'
  what():  internal error
Aborted (core dumped)`

**Comment by lfchener** [comment]
> @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢

fluid版本会在paddle 1.6中发布，尽请期待。

**Comment by hui001** [comment]
> > @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢
> 
> fluid版本会在paddle 1.6中发布，尽请期待。

好的，谢谢，希望fluid版本能支持CPU，现在这个我试了很久都没能把CPU版本跑起来

**Comment by tai960519073** [comment]
> > > @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢
> > 
> > 
> > fluid版本会在paddle 1.6中发布，尽请期待。
> 
> 好的，谢谢，希望fluid版本能支持CPU，现在这个我试了很久都没能把CPU版本跑起来

我是在CPU跑的，mac电脑，你遇到哪些问题了？

**Comment by tai960519073** [comment]
> > > > @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢
> > > 
> > > 
> > > fluid版本会在paddle 1.6中发布，尽请期待。
> > 
> > 
> > 好的，谢谢，希望fluid版本能支持CPU，现在这个我试了很久都没能把CPU版本跑起来
> 
> 我是在CPU跑的，mac电脑，你遇到哪些问题了？


> > @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢
> 
> fluid版本会在paddle 1.6中发布，尽请期待。

什么时候能放出来一些高质量的数据集？期待

**Comment by springminhcm** [comment]
您好，請問有人使用2080ti的gpu可正常執行嗎？

**Comment by springminhcm** [comment]
> > @kuke 您好，请问什么时候会发布fluid版本的deepspeech？谢谢
> 
> fluid版本会在paddle 1.6中发布，尽请期待。

您好，请问一下 fluid 1.6版，大概会何时发布呢？(只要一个大致的时间，如半年或一年之类)

**Comment by suntingfeng** [comment]
@hui001 我GPU和CPU均可跑通，是自己安装的环境，没有使用docker，你是遇到啥问题呢？

**Comment by springminhcm** [comment]
@suntingfeng 请问你的gpu是什么型号的呢？

**Comment by springminhcm** [comment]
@suntingfeng 在请问一下，依官方的文件，必须用docker才能执行，可否请教一下你如何自己安装呢？非常感谢你能回答，因为目前能购买的gpu显卡(全新)，都已不在是pascal架构~~~~

**Comment by hui001** [comment]
> @hui001 我GPU和CPU均可跑通，是自己安装的环境，没有使用docker，你是遇到啥问题呢？

我遇到的问题是大多是swig_decoder 的问题，然后就是core dump 的问题，然后我就用docker跑起来了，多谢回复~

**Comment by kuke** [comment]
谢谢大家的关注，develop 分支已更新到 Paddle Fluid API

**Comment by llp123** [comment]
2080Ti可以正常运行，安装readme步骤安装环境
