### ISSUE TITLE
请问 BaiduCN1.2k Model 模型要怎么调用

### ISSUE THREAD

**Issue by Re-bin** [PaddlePaddle/DeepSpeech#358]
请问 BaiduCN1.2k Model 模型要怎么调用，谢谢了。

**Comment by a2741432** [comment]
看以往Issues就可以调用成功 拒绝做伸手党哦

**Comment by tai960519073** [comment]
> 请问 BaiduCN1.2k Model 模型要怎么调用，谢谢了。

下载BaiduCN1.2k Model按照说明，改几个参数就可以了。另外，语音要求是8位的，16位的不行

**Comment by Re-bin** [comment]
> > 请问 BaiduCN1.2k Model 模型要怎么调用，谢谢了。
> 
> 下载BaiduCN1.2k Model按照说明，改几个参数就可以了。另外，语音要求是8位的，16位的不行

您好，可以具体的说说嘛，十分感谢。

**Comment by ccbptm** [comment]
> > 请问 BaiduCN1.2k Model 模型要怎么调用，谢谢了。
> 
> 下载BaiduCN1.2k Model按照说明，改几个参数就可以了。另外，语音要求是8位的，16位的不行

你好，我用BaiduCN1.2k Model模型，修改参数之后在aishell的测试集上测试，cer是1.000是。这个问题也是因为语音位导致的么？

**Comment by ccbptm** [comment]
> > 请问 BaiduCN1.2k Model 模型要怎么调用，谢谢了。
> 
> 下载BaiduCN1.2k Model按照说明，改几个参数就可以了。另外，语音要求是8位的，16位的不行

你这个语音要求是8位，是指8bit采样率么？
