### ISSUE TITLE
Client启动失败求助，缺乏包pynput

### ISSUE THREAD

**Issue by Re-bin** [PaddlePaddle/DeepSpeech#361]
```
root@34657c994c1d:/DeepSpeech# CUDA_VISIBLE_DEVICES=0 python -u deploy/demo_client.py --host_ip 'localhost' --host_port 8086
Traceback (most recent call last):
  File "deploy/demo_client.py", line 2, in <module>
    from pynput import keyboard
ImportError: No module named pynput

```

**Comment by DemoMoon** [comment]
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$ CUDA_VISIBLE_DEVICES=0 python -u deploy/demo_client.py --host_ip '192.168.16.150' --host_port 8086
Traceback (most recent call last):
  File "deploy/demo_client.py", line 2, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$ pip show keyboard
Name: keyboard
Version: 0.13.5
Summary: Hook and simulate keyboard events on Windows and Linux
Home-page: https://github.com/boppreh/keyboard
Author: BoppreH
Author-email: boppreh@gmail.com
License: MIT
Location: /Users/demo/PaddlePaddle/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages
Requires: pyobjc
Required-by: 
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$
