### ISSUE TITLE
基于Mandarin LM Large的剪枝

### ISSUE THREAD

**Issue by chen1399** [PaddlePaddle/DeepSpeech#363]
Mandarin LM Large下载的文件zhidao_giga.klm，能不能通过
` bin/lmplz -o5 --prune 0 1 1 2 2 -S 80% -T ./ zhidao_giga.klm `进行剪枝,

**Comment by chen1399** [comment]
lmplz支持.arpa模型文件，.klm不知道支不支持

**Comment by chen1399** [comment]
或者有没有介于Large和Small的中间版本

**Comment by heavengate** [comment]
Paddle有单独的PaddleSlim工具，支持剪枝，蒸馏，量化，硬件搜索等功能，建议使用这个~
https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim

**Comment by chen1399** [comment]
> Paddle有单独的PaddleSlim工具，支持剪枝，蒸馏，量化，硬件搜索等功能，建议使用这个~
> https://github.com/PaddlePaddle/models/tree/develop/PaddleSlim

你好，谢谢你的回答。这两种剪枝概念不太一样吧，这是语言模型的剪枝，是用来限制每个order删除单例的个数吧?应该在kenlm生成模型用lmplz进行--prune进行设定。

**Comment by heavengate** [comment]
麻烦提供下模型和剪枝工具github链接，我找相关开发人员确认一下

**Comment by chen1399** [comment]
modelURL: https://deepspeech.bj.bcebos.com/zh_lm/zhidao_giga.klm
kenlm: https://github.com/kpu/kenlm

**Comment by heavengate** [comment]
> modelURL: https://deepspeech.bj.bcebos.com/zh_lm/zhidao_giga.klm

这个是inference_model，有Paddle的模型代码链接么，我确认一下模型结构和相关开发

**Comment by chen1399** [comment]
> > modelURL: https://deepspeech.bj.bcebos.com/zh_lm/zhidao_giga.klm
> 
> 这个是inference_model，有Paddle的模型代码链接么，我确认一下模型结构和相关开发

没有模型，这是百度已经发布的模型，原话是：A language model is required to improve the decoder's performance. We have prepared two language models (with lossy compression) for users to download and try. One is for English and the other is for Mandarin.

**Comment by chen1399** [comment]
> > modelURL: https://deepspeech.bj.bcebos.com/zh_lm/zhidao_giga.klm
> 
> 这个是inference_model，有Paddle的模型代码链接么，我确认一下模型结构和相关开发

是基于KenLM生成的，如果没办法基于.klm文件进行剪枝，我想如果方便的话baidu大大在发布一个Mandarin LM Medium的版本，感谢baidu.

**Comment by heavengate** [comment]
和开发人员确认了一下，这个模型的Large和Small精度相差没有特别大，发布medium模型价值不大，你可以考虑一下使用Small的模型，要尝试剪枝的话可以参考https://github.com/kpu/kenlm

**Comment by chen1399** [comment]
> 这个

谢谢
