### ISSUE TITLE
当我在docker中运行run_infer_golden.sh时，报了如下错误，请问什么原因导致的？

### ISSUE THREAD

**Issue by MrCuiHao** [PaddlePaddle/DeepSpeech#365]
运行时只使用了一个显卡，１张GTX 1080TI ，显存11GB

root@1e103b8c3b19:/DeepSpeech/examples/tiny# sh run_infer_golden.sh 
-----------  Configuration Arguments -----------
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
error_rate_type: wer
infer_manifest: data/tiny/manifest.test-clean
lang_model_path: models/lm/common_crawl_00.prune01111.trie.klm
mean_std_path: models/librispeech/mean_std.npz
model_path: models/librispeech/params.tar.gz
num_conv_layers: 2
num_proc_bsearch: 8
num_rnn_layers: 3
num_samples: 10
rnn_layer_size: 2048
share_rnn_weights: 1
specgram_type: linear
trainer_count: 1
use_gpu: 1
use_gru: 0
vocab_path: models/librispeech/vocab.txt
------------------------------------------------
I0923 13:29:14.188905    36 Util.cpp:166] commandline:  --use_gpu=1 --rnn_use_batch=True --trainer_count=1 
[INFO 2019-09-23 13:29:20,204 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-09-23 13:29:20,207 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-09-23 13:29:20,209 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-09-23 13:29:20,211 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-09-23 13:29:20,214 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-09-23 13:29:20,215 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-09-23 13:29:24,914 model.py:243] begin to initialize the external scorer for decoding
[INFO 2019-09-23 13:33:51,108 model.py:253] language model: is_character_based = 0, max_order = 5, dict_size = 400000
[INFO 2019-09-23 13:33:51,589 model.py:254] end initializing scorer
[INFO 2019-09-23 13:33:51,589 infer.py:103] start inference ...
F0923 13:33:57.753219    36 hl_cuda_device.cc:273] Check failed: cudaSuccess == cudaStat (0 vs. 2) Cuda Error: out of memory
*** Check failure stack trace: ***
    @     0x7f475d89b04d  google::LogMessage::Fail()
    @     0x7f475d89d398  google::LogMessage::SendToLog()
    @     0x7f475d89ab5b  google::LogMessage::Flush()
    @     0x7f475d89e26e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f475d843a9f  hl_malloc_device()
    @     0x7f475d6977c7  paddle::GpuAllocator::alloc()
    @     0x7f475d684458  paddle::PoolAllocator::alloc()
    @     0x7f475d683e33  paddle::GpuMemoryHandle::GpuMemoryHandle()
    @     0x7f475d69efef  paddle::GpuVectorT<>::GpuVectorT()
    @     0x7f475d69f388  paddle::VectorT<>::create()
    @     0x7f475d69f3f8  paddle::VectorT<>::createParallelVector()
    @     0x7f475d53de84  _ZNSt17_Function_handlerIFviPN6paddle9ParameterEEZNS0_15GradientMachine6createERKNS0_11ModelConfigEiRKSt6vectorINS0_19enumeration_wrapper13ParameterTypeESaISA_EEEUliS2_E_E9_M_invokeERKSt9_Any_dataOiOS2_
    @     0x7f475d527933  paddle::NeuralNetwork::init()
    @     0x7f475d53f331  paddle::GradientMachine::create()
    @     0x7f475d86b8bb  GradientMachine::createFromPaddleModelPtr()
    @     0x7f475d86c4ce  GradientMachine::createByConfigProtoStr()
    @     0x7f475d3533aa  _wrap_GradientMachine_createByConfigProtoStr
    @           0x4cb45e  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4de8b8  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4f492e  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4f46a7  (unknown)
    @           0x4b670c  (unknown)
    @           0x4b0cb3  PyObject_Call
    @           0x4c9faf  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
Aborted (core dumped)
Failed in inference!

**Comment by GC-Tom** [comment]
out of memory
