### ISSUE TITLE
Docker Image for non-gpu version 

### ISSUE THREAD

**Issue by dhirajsuvarna** [PaddlePaddle/DeepSpeech#370]
The Docker Image mentioned in the ReadMe.md file talks about the image with GPU support (NVIDIA). Is there a docker image for non gpu support (CPU-only)?

I do not have NVIDIA GPU nevertheless, would like to try out deepspeech, what are my options?

**Comment by dhirajsuvarna** [comment]
+1 would like to hear a comment for this

**Comment by ssokhey** [comment]
You have to install everything locally. It is not much of work if you have ubuntu. You should try that.

If you still can't get around, I can give you a CPU docker image but it will be better if you try yourself.

**Comment by dhirajsuvarna** [comment]
can you point me to any help guide for the steps to do it?

**Comment by ssokhey** [comment]
NOTE: paddlepaddle ported the code repository to paddlepaddle==1.6 (develop branch), previously it was supported till 0.13 (master branch)

I don't think you need a guide for that, it is very simple.

Assuming you have Ubuntu 16.04 & Anaconda/miniconda:

- First, install system packages as mentioned in instructions.

1. Create a virtual environment: `conda create -n paddle_cpu python=2.7`
2. Install paddlepaddle: `pip install paddlepaddle==0.13`
3. Clone the repo:  `https://github.com/PaddlePaddle/DeepSpeech` & switch to master branch.
(even the develop branch works fine but I faced some issues initially)
4. cd DeepSpeech
5. sh setup.sh

That's it. It is that simple.
