### ISSUE TITLE
如果已训练好一个模型，若有新的资料，如何做训练后续部份呢？

### ISSUE THREAD

**Issue by springminhcm** [PaddlePaddle/DeepSpeech#372]
拜托各位大神帮忙，如果在checkpoints下已做好了一个模型AAA.gz，这是经训练如100小时的语音，如果后续有新增新的20小时的训练资料时，请问要如何只针对那新的20小时训练呢？总不可能每次都要从头开始做学习吧？

**Comment by lfchener** [comment]
可以加载保存好的 checkpoint 继续训练。

**Comment by springminhcm** [comment]
> 可以加载保存好的 checkpoint 继续训练。

非常感谢回覆，请问相关的manifest.train、mean_std.npz、vocab.txt的档案，是只要针对那新增的20小时产生的manifest.train、mean_std.npz、vocab.txt，还是要用100小时(原来的)+20小时(新增)所产生的manifest.train、mean_std.npz、vocab.txt来做呢？

非常感谢你的回覆，真的麻烦你了，真的找不到人能回答~

**Comment by jchua127** [comment]
> > 可以加载保存好的 checkpoint 继续训练。
> 
> 非常感谢回覆，请问相关的manifest.train、mean_std.npz、vocab.txt的档案，是只要针对那新增的20小时产生的manifest.train、mean_std.npz、vocab.txt，还是要用100小时(原来的)+20小时(新增)所产生的manifest.train、mean_std.npz、vocab.txt来做呢？
> 
> 非常感谢你的回覆，真的麻烦你了，真的找不到人能回答~

我觉得应该是要重新用100+20小时的数据来训练，不然的话会有没有识别的字符导致报错的。

**Comment by springminhcm** [comment]
唉，说真的不知为何，lfchener  并不愿意回覆，我也不是伸手牌，自己都有做过相关测试，就是不行。我有试过用100+20小时的manifest，新做出的mean_std.npz、vocab.txt，搭配20小时的manifest.train与manifest.dev，做train.py时，会出现lhs_.getWidth() == rhs_.getWidth() (16089088 vs. 16142336) 的错误

若用原本的100小时的mean_std.npz、vocab.txt，搭配20小时的manifest.train与manifest.dev，做train.py时，会出现return [self._vocab_dict[token] for token in tokens]
KeyError: u'\u7444' 的错误，然后卡住。

但你用100+20全部重新训练则很正常的完成.......那请问这个专案到底是可不可以，仅针对新增部份做训练呢？我真的很希望官方能有人回覆一下，大概的方式，不用写的很细，就这样的小小希望都难以达到......

这一部份不是什么特殊的knowhow，因为说真的，挺多就是全部重train就好，但讨论区不就是这样精神吗？提点一下大家，让大家有一个方向，自己钻研，而不是一直找错的方向去试。

以上，小小心得~~~

**Comment by jchua127** [comment]
.......
> 以上，小小心得~~~
是的，我用aishell+自己的数据集，重新生成vocab，meanstd后是可以正常完成训练的，但是我还没有试过在已经训练好的.gz文件上累加训练。我不太理解你说的100+20小时的数据，搭配20小时的manifest.train是什么意思？你说的这两个问题我都没有遇到过，看上去还是因为vocab和manifest.train不匹配导致的。

**Comment by springminhcm** [comment]
> 自己的数据集，重新生成vocab，meanstd后是可以正常完成训练的，但是我还没有试过在已经训练好的.gz文件上累加训练。我不太理解你说的100+20小时的数据，搭配20小时的

你好，简单来说，我是想做到如jchua127你所提到的「**在已经训练好的.gz文件上累加训练**」。这一部份我目前是完全做不到，只能**全部重新train**。官方人员或文件上目前是都没有说明过如何做，只有lfchener 在本讨论中回覆到「**可以加载保存好的 checkpoint 继续训练。**」但是 ....也就提到一下而已，并没有提到具体的做法。

但我觉得这实在是一件很蛋疼的事情，那天你有1000小时语音了，也train完了，结果，后续又来了250小时的语音，然后本专案只能全部重头将这1250小时语音重新train.....这是什么跟什么呀@@

**Comment by jchua127** [comment]
我试过在BaiduCn1.2k模型基础上进行累加训练自己的数据集，vocab和meanstd用的就是BaiduCN1.2K的，虽然累加后的效果一般（可能是我的数据集不够），但没有出现你说的报错问题。

**Comment by sukibean163** [comment]
@springminhcm 后来解决了吗？新的训练数据vocab一般会增加，加载预训练的模型，最后一层也要相应更改吧。
