### ISSUE TITLE
请问一下，如何使用已训练模型识别数据

### ISSUE THREAD

**Issue by zhengyuelai-ctrl** [PaddlePaddle/DeepSpeech#373]
使用脚本下载了
`DeepSpeech/models/lm/zh_giga.no_cna_cmn.prune01244.klm`
请教一下该如何使用，或者在example中哪个例子是使用的方法（通过脚本指定语音文件输出识别内容）？
谢谢

**Comment by lfchener** [comment]
详见 README  **开始**  章节：
![image](https://user-images.githubusercontent.com/6771821/68022272-d3ed6300-fcde-11e9-919a-bb89a368095c.png)

**Comment by tutan123** [comment]
如何预测自己的wav文件呢

**Comment by duan348733684** [comment]
如何预测自己的wav文件呢

**Comment by YanqiangWang** [comment]
> 如何预测自己的wav文件呢

在manifest写好自己文件的路径，然后调用infer.py，
