### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lawlietAi** [PaddlePaddle/DeepSpeech#378]
各位好，我在WSL(Ubuntu 18.04)上配置了该项目，配置如下：
CUDA_VISIBLE_DEVICES=0 \
python -u infer.py \
--num_samples=10 \
--beam_size=300 \
--num_proc_bsearch=8 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=1024 \
--alpha=2.6 \
--beta=5.0 \
--cutoff_prob=0.99 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=False \
--share_rnn_weights=False \
--infer_manifest='data/aishell/manifest.test' \
--mean_std_path='data/librispeech/mean_std.npz' \
--vocab_path='data/librispeech/vocab.txt' \
--model_path='data/librispeech/params.tar.gz' \
--lang_model_path='models/lm/zh_giga.no_cna_cmn.prune01244.klm' \
--decoding_method='ctc_beam_search' \
--error_rate_type='cer' \
--specgram_type='linear'
图中路径有些乱，见谅。。

**Comment by lawlietAi** [comment]
报错如下：
[INFO 2019-10-31 11:51:04,233 model.py:475] begin to initialize the external scorer for decoding
[INFO 2019-10-31 11:51:04,264 model.py:485] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2019-10-31 11:51:04,265 model.py:486] end initializing scorer
[INFO 2019-10-31 11:51:04,266 infer.py:121] start inference ...
W1031 11:51:04.807015   673 init.cc:212] *** Aborted at 1572493864 (unix time) try "date -d @1572493864" if you are using GNU date ***
W1031 11:51:04.813829   673 init.cc:212] PC: @                0x0 (unknown)
W1031 11:51:04.814508   673 init.cc:212] *** SIGSEGV (@0x50) received by PID 673 (TID 0x7ff71b060740) from PID 80; stack trace: ***
W1031 11:51:04.820022   673 init.cc:212]     @     0x7ff71aa3ef20 (unknown)
W1031 11:51:04.825690   673 init.cc:212]     @     0x7ff71ae0cac8 (unknown)
W1031 11:51:04.831775   673 init.cc:212]     @     0x7ff71ae150bd (unknown)
W1031 11:51:04.838132   673 init.cc:212]     @     0x7ff71ab672df _dl_catch_exception
W1031 11:51:04.843402   673 init.cc:212]     @     0x7ff71ae147ca (unknown)
W1031 11:51:04.849170   673 init.cc:212]     @     0x7ff71ab663ad (unknown)
W1031 11:51:04.854698   673 init.cc:212]     @     0x7ff71ab672df _dl_catch_exception
W1031 11:51:04.861147   673 init.cc:212]     @     0x7ff71ab6736f _dl_catch_error
W1031 11:51:04.867319   673 init.cc:212]     @     0x7ff71ab664d9 __libc_dlopen_mode
W1031 11:51:04.872779   673 init.cc:212]     @     0x7ff71ab31075 (unknown)
W1031 11:51:04.878039   673 init.cc:212]     @     0x7ff71a7ef827 __pthread_once_slow
W1031 11:51:04.884569   673 init.cc:212]     @     0x7ff71ab3114f backtrace
W1031 11:51:04.894858   673 init.cc:212]     @     0x7ff6e1ddf324 paddle::platform::GetTraceBackString<>()
W1031 11:51:04.903975   673 init.cc:212]     @     0x7ff6e1ddf7ca paddle::platform::EnforceNotMet::EnforceNotMet()
W1031 11:51:04.918928   673 init.cc:212]     @     0x7ff6e297613c paddle::operators::LoadCombineOpKernel<>::Compute()
W1031 11:51:04.928972   673 init.cc:212]     @     0x7ff6e29764b3 _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators19LoadCombineOpKernelINS7_16CPUDeviceContextEfEENSA_ISB_dEENSA_ISB_iEENSA_ISB_aEENSA_ISB_lEEEEclEPKcSJ_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
W1031 11:51:04.944161   673 init.cc:212]     @     0x7ff6e351c53b paddle::framework::OperatorWithKernel::RunImpl()
W1031 11:51:04.963321   673 init.cc:212]     @     0x7ff6e351cec1 paddle::framework::OperatorWithKernel::RunImpl()
W1031 11:51:04.972717   673 init.cc:212]     @     0x7ff6e3517a04 paddle::framework::OperatorBase::Run()
W1031 11:51:04.991598   673 init.cc:212]     @     0x7ff6e1f7d656 paddle::framework::Executor::RunPreparedContext()
W1031 11:51:05.004420   673 init.cc:212]     @     0x7ff6e1f808ff paddle::framework::Executor::Run()
W1031 11:51:05.009606   673 init.cc:212]     @     0x7ff6e1dce35d _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL22pybind11_init_core_avxERNS_6moduleEEUlRNS2_9framework8ExecutorERKNS6_11ProgramDescEPNS6_5ScopeEibbRKSt6vectorISsSaISsEEE101_vIS8_SB_SD_ibbSI_EINS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES10_
W1031 11:51:05.019842   673 init.cc:212]     @     0x7ff6e1e12b36 pybind11::cpp_function::dispatcher()
W1031 11:51:05.026173   673 init.cc:212]     @     0x7ff71b2fdc85 PyEval_EvalFrameEx
W1031 11:51:05.031533   673 init.cc:212]     @     0x7ff71b2f2d3a PyEval_EvalCodeEx
W1031 11:51:05.037830   673 init.cc:212]     @     0x7ff71b2fae63 PyEval_EvalFrameEx
W1031 11:51:05.043659   673 init.cc:212]     @     0x7ff71b2f2d3a PyEval_EvalCodeEx
W1031 11:51:05.049491   673 init.cc:212]     @     0x7ff71b2fae63 PyEval_EvalFrameEx
W1031 11:51:05.055073   673 init.cc:212]     @     0x7ff71b2f2d3a PyEval_EvalCodeEx
W1031 11:51:05.062100   673 init.cc:212]     @     0x7ff71b2fa83e PyEval_EvalFrameEx
W1031 11:51:05.067919   673 init.cc:212]     @     0x7ff71b2f2d3a PyEval_EvalCodeEx
W1031 11:51:05.073608   673 init.cc:212]     @     0x7ff71b2fa83e PyEval_EvalFrameEx
Segmentation fault (core dumped)
Failed in inference!

**Comment by purijs** [comment]
@lawlietAi  was this resolved?
