### ISSUE TITLE
swig_decoders==1.1' distribution was not found 

### ISSUE THREAD

**Issue by artinegi1607** [PaddlePaddle/DeepSpeech#379]
Hi,

While running the setup.sh to install decoders, I got the below error.
Please help!

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jay/GIT_HCL/NLP_Project_GIT/arti_branch_voice_recognition/dev_voice_recognition/voice_recognition/asr/venv2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jay/GIT_HCL/NLP_Project_GIT/arti_branch_voice_recognition/dev_voice_recognition/voice_recognition/asr/venv2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'swig_decoders==1.1' distribution was not found and is required by the application
Install decoders ...
scorer.h:22: Warning 401: Nothing known about base class 'lm::EnumerateVocab'. Ignored.
....................
..................
.......

openfst-1.6.3/src/include/fst/vector-fst.h:149:53: warning: ‘dst’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   Weight Final(StateId state) const { return states_[state]->Final(); }
                                                     ^
decoder_utils.cpp:138:30: note: ‘dst’ was declared here
   fst::StdVectorFst::StateId dst;
                              ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Install all dependencies successfully.

**Comment by lfchener** [comment]
You can try to build and install swig by source 3.0.12:

1. build and install swig by source 3.0.12
wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz
tar xvzf swig-3.0.12.tar.gz
cd swig-3.0.12
./autogen.sh
./configure
make
make install

2. entry decoders/swig， rerun setup.sh

as in issue  #113

**Comment by changweioy** [comment]
> You can try to build and install swig by source 3.0.12:
> 
> 1. build and install swig by source 3.0.12
>    wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz
>    tar xvzf swig-3.0.12.tar.gz
>    cd swig-3.0.12
>    ./autogen.sh
>    ./configure
>    make
>    make install
> 2. entry decoders/swig， rerun setup.sh
> 
> as in issue #113

试了，完全没用。

**Comment by artinegi1607** [comment]
@lfchener  @changweioy  Thanks for your response. 
But I am getting the below error while running  ./autogen.sh 

+ test -d Tools/config
+ aclocal -I Tools/config
./autogen.sh: 11: ./autogen.sh: aclocal: not found

**Comment by inishchith** [comment]
```sh
sudo apt-get install automake
./autogen.sh
```

@artinegi1607 This should solve your problem

**Comment by tuanphan09** [comment]
@lfchener I cannot run setup.sh in decoders/swig because this git repo is not exist in github. Is there any problem?
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/decoders/swig/setup.sh#L4
