### ISSUE TITLE
manifest.noise 这些数据是要自己生成的吗？还是训练过程中自动生成的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/DeepSpeech#381]
我的训练数据太干净了，我想加点噪声，在配置文件中，manifest.noise 这些文件是要根据噪声音频生成的吗？还是说 train.py 代码在训练过程中自动帮我们生成？
```
    {
        "type": "noise",
        "params": {"min_snr_dB": 40,
                   "max_snr_dB": 50,
                   "noise_manifest_path": "datasets/manifest.noise"},
        "prob": 0.6
    },
    {
        "type": "impulse",
        "params": {"impulse_manifest_path": "datasets/manifest.impulse"},
        "prob": 0.5
    },
```

**Comment by lfchener** [comment]
数据增强已嵌入到训练的过程中，详细的过程请参考 README 的 Data Augmentation Pipeline 一节：
https://github.com/PaddlePaddle/DeepSpeech#data-augmentation-pipeline

**Comment by yeyupiaoling** [comment]
@lfchener 单纯配置这个文件不行呐，报错` datasets/manifest.impulse` 不存在，这个文件是不是指定噪声文件的？还是说要报噪声文件和普通的音频文件合成。还请告知，
因为文档中说到 `manifest`  这种文件要包含 `text` 的语音中文，但是如果是噪声就没有语音中文内容之说。

**Comment by yzcm1232** [comment]
请问最终怎么解决的
