### ISSUE TITLE
使用官方提供的模型作为预训练模型训练自己数据集报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/DeepSpeech#382]
我使用如下的官方中文训练模型作为预训练模型训练自己的数据集，报错，
![image](https://user-images.githubusercontent.com/26297768/68064516-924cce80-fd57-11e9-8922-9647577b30cb.png)

错误信息如下：
```
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main()
  File "train.py", line 114, in main
    train()
  File "train.py", line 109, in train
    test_off=args.test_off)
  File "/DeepSpeech/model_utils/model.py", line 307, in train
    pre_epoch = self.init_from_pretrained_model(exe, train_program)
  File "/DeepSpeech/model_utils/model.py", line 161, in init_from_pretrained_model
    filename="params.pdparams")
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 784, in load_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 668, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 727, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((1312L, 3072L)), while the loaded parameter (namely [ layer_2_forward_fc_weight ]) has a shape of  ((1312, 6144)).
Failed in training!
```

**Comment by lfchener** [comment]
baiduCN 1.2k 的网络结构参数如下，请确认您的结构与其一致：
![image](https://user-images.githubusercontent.com/6771821/68209752-0d8bda00-000f-11ea-895b-264dd29c84f9.png)

**Comment by yeyupiaoling** [comment]
@lfchener 参数结构是正确的，但是字典zh_vocab.txt 是我自己生成的，这个有影响吗？
```
python -u train.py \
--batch_size=8 \
--num_epoch=50 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=2048 \
--num_iter_print=100 \
--save_epoch=2 \
--num_samples=120000 \
--learning_rate=5e-4 \
--max_duration=27.0 \
--min_duration=0.0 \
--test_off=False \
--use_sortagrad=True \
--use_gru=True \
--use_gpu=True \
--is_local=True \
--share_rnn_weights=False \
--init_from_pretrained_model='models/baidu_cn1.2k_model_fluid/' \
--train_manifest='./dataset/manifest.train' \
--dev_manifest='./dataset/manifest.dev' \
--mean_std_path='./dataset/mean_std.npz' \
--vocab_path='./dataset/zh_vocab.txt' \
--output_model_dir='./models/checkpoints/' \
--augment_conf_path='./conf/augmentation.config' \
--specgram_type='linear' \
--shuffle_method='batch_shuffle_clipped' \

```

**Comment by yeyupiaoling** [comment]
如果不使用自己的字典就是出现无法识别的字符，具体报错如下：
```
  File "train.py", line 118, in <module>
    main()
  File "train.py", line 114, in main
    train()
  File "train.py", line 109, in train
    test_off=args.test_off)
  File "/DeepSpeech/model_utils/model.py", line 369, in train
    "epoch_" + str(epoch_id + pre_epoch))
  File "/DeepSpeech/model_utils/model.py", line 183, in save_param
    filename="params.pdparams")
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 325, in save_params
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 216, in save_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 256, in save_vars
    executor.run(save_program)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 817, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 894, in _run_program
    fetch_var_name)
KeyboardInterrupt

```

**Comment by llp123** [comment]
将预训练模型最后一层舍弃掉，换成你的vocab的尺寸，

**Comment by yeyupiaoling** [comment]
@llp123 官方提供的预训练模型是一个的，与其他的PaddlePaddle模型不一样呀，普通的模型是每一层都是一个问题的。
这种情况如何去掉最后一层呢？

**Comment by jchua127** [comment]
我在BaiduCN1.2K的基础上累加了自己的数据集，vocab和mean_std都是用的BaiduCN1.2K的。但累加后识别效果没有改进。

**Comment by yeyupiaoling** [comment]
@jchua127 我没加自己的数据，直接使用BaiduCN1.2K模型预测我们的语音，结果无法正确输出结果，一个字都没有输出

**Comment by jchua127** [comment]
> @jchua127 我没加自己的数据，直接使用BaiduCN1.2K模型预测我们的语音，结果无法正确输出结果，一个字都没有输出

你的录音文件格式是什么，BaiduCN1.2K对8K采样率的录音文件效果比较好

**Comment by yeyupiaoling** [comment]
@jchua127 
我使用的是官方的代码：https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_client.py
他是16k采样率的

**Comment by jchua127** [comment]
> @jchua127
> 我使用的是官方的代码：https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_client.py
> 他是16k采样率的

我用8K和16K的都可以正常识别，8K的识别率会高很多。你的可能是其他问题。

**Comment by yeyupiaoling** [comment]
@jchua127 好的，多谢提醒。我再看看。
顺便问题一下，你的显存多大呢，我的6G训练几个小时后就突然出现显存不足。

**Comment by llp123** [comment]
我的粗暴解决方式：将预训练模型下载解压，直接删掉最后一层的参数模型，然后再压缩成跟原来模型一样的tar文件，然后修改model.py中的_create_parameters()方法：
    def _create_parameters(self, model_path=None, is_update=False):
        """Load or create model parameters."""
        if model_path is None:
            self._parameters = paddle.parameters.create(self._total_loss)
        elif is_update: # 更新vocab
            self._parameters = paddle.parameters.create(self._total_loss)
            self._parameters.init_from_tar(gzip.open(model_path))
        else:
            self._parameters = paddle.parameters.Parameters.from_tar(gzip.open(model_path))
仅供参考。

**Comment by llp123** [comment]
我的粗暴解决方式：将预训练模型下载解压，直接删掉最后一层的参数模型，然后再压缩成跟原来模型一样的tar文件，然后修改model.py中的_create_parameters()方法：
```python
def _create_parameters(self, model_path=None, is_update=False):
    """Load or create model parameters."""
    if model_path is None:
        self._parameters = paddle.parameters.create(self._total_loss)
    elif is_update: # 更新vocab
        self._parameters = paddle.parameters.create(self._total_loss)
        self._parameters.init_from_tar(gzip.open(model_path))
    else:
        self._parameters = paddle.parameters.Parameters.from_tar(gzip.open(model_path))
```
仅供参考。

**Comment by yeyupiaoling** [comment]
@llp123 能解决问题的办法都是好办法

**Comment by jchua127** [comment]
> @jchua127 好的，多谢提醒。我再看看。
> 顺便问题一下，你的显存多大呢，我的6G训练几个小时后就突然出现显存不足。

2块16G。内存不足的话把batchsize调小一点就好。

**Comment by yeyupiaoling** [comment]
@jchua127 调小也没有用，我从原来的32，调到8也不行。

**Comment by jchua127** [comment]
@yeyupiaoling 那看来只能加卡了

**Comment by yeyupiaoling** [comment]
@llp123 这个文件无法解压呢？你是如何解压的？
![image](https://user-images.githubusercontent.com/26297768/69782284-7ff57180-11eb-11ea-99b6-02b2bab701e7.png)

**Comment by yeyupiaoling** [comment]
@jchua127 好的，我换一个8G的卡试试

**Comment by llp123** [comment]
@yeyupiaoling 我这个是在改版fluid之前(master分支)的解决方案，新api参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/model_save_reader.html#api-guide-model-save-reader中的fluid.io.load_vars， 应该是可以选择加载参数列表，没有测试可行性，你可以试一下

**Comment by yeyupiaoling** [comment]
>我用8K和16K的都可以正常识别，8K的识别率会高很多。你的可能是其他问题。

@jchua127 请问您有修改什么参数吗？我的参数如下，一个字都没有识别到。

客户端：
```
    stream = p.open(
        format=pyaudio.paInt16,
        channels=1,
        rate=8000,
        input=True,
        stream_callback=callback)
    stream.start_stream()
```

启动服务参数：
```
CUDA_VISIBLE_DEVICES=0 \
PYTHONPATH=.:$PYTHONPATH python -u deploy/server.py \
--host_ip="192.168.1.119" \
--host_port=10086 \
--beam_size=500 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=2048 \
--alpha=2.5 \
--beta=0.3 \
--cutoff_prob=1.0 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=True \
--share_rnn_weights=False \
--speech_save_dir="./audios_cache" \
--warmup_manifest="./dataset/manifest.test" \
--mean_std_path="./models/baidu_cn1.2k_model_fluid/mean_std.npz" \
--vocab_path="./models/baidu_cn1.2k_model_fluid/vocab.txt" \
--model_path="./models/baidu_cn1.2k_model_fluid/" \
--lang_model_path="./models/zhidao_giga.klm" \
--decoding_method="ctc_beam_search" \
--specgram_type="linear"
```

**Comment by jchua127** [comment]
> > 我用8K和16K的都可以正常识别，8K的识别率会高很多。你的可能是其他问题。
> 
> @jchua127 请问您有修改什么参数吗？我的参数如下，一个字都没有识别到。
> 
> 客户端：
> 
> ```
>     stream = p.open(
>         format=pyaudio.paInt16,
>         channels=1,
>         rate=8000,
>         input=True,
>         stream_callback=callback)
>     stream.start_stream()
> ```
> 
> 启动服务参数：
> 
> ```
> CUDA_VISIBLE_DEVICES=0 \
> PYTHONPATH=.:$PYTHONPATH python -u deploy/server.py \
> --host_ip="192.168.1.119" \
> --host_port=10086 \
> --beam_size=500 \
> --num_conv_layers=2 \
> --num_rnn_layers=3 \
> --rnn_layer_size=2048 \
> --alpha=2.5 \
> --beta=0.3 \
> --cutoff_prob=1.0 \
> --cutoff_top_n=40 \
> --use_gru=True \
> --use_gpu=True \
> --share_rnn_weights=False \
> --speech_save_dir="./audios_cache" \
> --warmup_manifest="./dataset/manifest.test" \
> --mean_std_path="./models/baidu_cn1.2k_model_fluid/mean_std.npz" \
> --vocab_path="./models/baidu_cn1.2k_model_fluid/vocab.txt" \
> --model_path="./models/baidu_cn1.2k_model_fluid/" \
> --lang_model_path="./models/zhidao_giga.klm" \
> --decoding_method="ctc_beam_search" \
> --specgram_type="linear"
> ```

你用的是fluid版本？model_path不对吧？应该是一个.gz压缩包

**Comment by yeyupiaoling** [comment]
@jchua127 是的，我用的是fluid版本，模型路径是没有问题的。你的音频文件处理是这样的吗？？
```
        # write to wav file
        file = wave.open(out_filename, 'wb')
        file.setnchannels(1)
        file.setsampwidth(4)
        file.setframerate(16000)
        file.writeframes(data)
        file.close()
```

**Comment by jchua127** [comment]
@yeyupiaoling 我是用infer.py进行识别的，我用的不是fluid版。

**Comment by AshishKarel** [comment]
Hello everyone, I also got the same issue as the original one. I had a small dataset of 3000 audio files(wav) and created its vocabulary to infer trained model(librespeech) and it gave shape mismatch error. So i changed it to the default vocab provided in examples/tiny and it worked. Or we could also have tried the method where we need to reconfigure the last layer. But i will leave that for some other day

**Comment by yeyupiaoling** [comment]
>Or we could also have tried the method where we need to reconfigure the last layer. 

@AshishKarel hi， What should I do?

**Comment by AshishKarel** [comment]
@yeyupiaoling  i'm no expert in this but first check compare your vocab with the one provided in the repo. And if that doesnt match means you have to redefine the last layer(see @llp123 answer above) of model and retrain it.

**Comment by yeyupiaoling** [comment]
@AshishKarel He's using V2. But I using Fliuid.

**Comment by yeyupiaoling** [comment]
@AshishKarel Could you please answer this question? #392

**Comment by AshishKarel** [comment]
Nope not yet worked on mandarin models

**Comment by yeyupiaoling** [comment]
I see. Thank you.

**Comment by gaozheyuan** [comment]
> @yeyupiaoling 我是用infer.py进行识别的，我用的不是fluid版。

你用的是什么版本呀？

**Comment by francislinker** [comment]
@llp123 fluid版本中采用的save_params 保存参数,无法通过load_vars 选择加载参数列表，这种方法似乎不可行,有没有其他方法能够去掉最后一个全连接层,望指教.

**Comment by nemo9903** [comment]
请问fluid版本的链接在哪里？谢谢



---原始邮件---
发件人: "FrancisChan"<notifications@github.com&gt;
发送时间: 2019年12月16日(周一) 下午5:02
收件人: "PaddlePaddle/DeepSpeech"<DeepSpeech@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PaddlePaddle/DeepSpeech] 使用官方提供的模型作为预训练模型训练自己数据集报错 (#382)



@llp123 fluid版本中采用的save_params 保存参数,无法通过load_vars 选择加载参数列表，这种方法似乎不可行,有没有其他方法能够去掉最后一个全连接层,望指教.

**Comment by chadlwm** [comment]
@jchua127 把音频格式转为8k就来识别内容了，只是准确度有点低

**Comment by gezimonkey** [comment]
我也遇到这个FLUID下用自己的vocab报Shape not matching错误,请问你解决了吗?

**Comment by yeyupiaoling** [comment]
@gezimonkey 没有
