### ISSUE TITLE
使用官方的中文语音识别模型，不能正确识别语音

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/DeepSpeech#385]
使用官方的中文语音识别模型，不能正确识别语音。输出都是空值

```
PYTHONPATH=.:$PYTHONPATH python -u deploy/server.py \
--host_ip="192.168.1.130" \
--host_port=10086 \
--beam_size=500 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=2048 \
--alpha=2.5 \
--beta=0.3 \
--cutoff_prob=1.0 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=True \
--share_rnn_weights=True \
--speech_save_dir="./audios_cache" \
--warmup_manifest="./dataset/manifest.test" \
--mean_std_path="./models/baidu_cn1.2k_model_fluid/mean_std.npz" \
--vocab_path="./models/baidu_cn1.2k_model_fluid/vocab.txt" \
--model_path="./models/baidu_cn1.2k_model_fluid/" \
--lang_model_path="./models/zhidao_giga.klm" \
--decoding_method="ctc_beam_search" \
--specgram_type="linear"

```

**Comment by yeyupiaoling** [comment]
是不是因为官方这个模型没有训练好呢？

**Comment by jasonlbx13** [comment]
把音频转成8000试试，16000大部分都是空值

**Comment by yeyupiaoling** [comment]
@jasonlbx13 好的，我试试，谢谢。
你是修改这个吗：
https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_client.py#L69-L75

还是这个？
https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_server.py#L116-L121

**Comment by jasonlbx13** [comment]
我没有修改源码，只是把测试语音的采样频率用ffmpeg从16k转为了8k,你可以试下






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "夜雨飘零"<notifications@github.com&gt;; 
发送时间: 2019年12月10日(星期二) 下午3:43
收件人: "PaddlePaddle/DeepSpeech"<DeepSpeech@noreply.github.com&gt;; 
抄送: "骚浪大蹄子"<602465307@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [PaddlePaddle/DeepSpeech] 使用官方的中文语音识别模型，不能正确识别语音 (#385)




@jasonlbx13 好的，我试试，谢谢。
 你是修改这个吗：
 https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_client.py#L69-L75
 
还是这个？
 https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_server.py#L116-L121

**Comment by yeyupiaoling** [comment]
好的，谢谢。

**Comment by ghost** [comment]
> 好的，谢谢。

您好，请问问题被解决了吗？

**Comment by ghost** [comment]
> 我没有修改源码，只是把测试语音的采样频率用ffmpeg从16k转为了8k,你可以试下
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "夜雨飘零"<notifications@github.com&gt;; 发送时间: 2019年12月10日(星期二) 下午3:43 收件人: "PaddlePaddle/DeepSpeech"<DeepSpeech@noreply.github.com&gt;; 抄送: "骚浪大蹄子"<602465307@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [PaddlePaddle/DeepSpeech] 使用官方的中文语音识别模型，不能正确识别语音 (#385) @jasonlbx13 好的，我试试，谢谢。 你是修改这个吗： https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_client.py#L69-L75 还是这个？ https://github.com/PaddlePaddle/DeepSpeech/blob/517c027c5efd8f235fcf18316372a8923edcb00a/deploy/demo_server.py#L116-L121 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，请问调整测试语音的采样频率具体该怎么做呢？

**Comment by yeyupiaoling** [comment]
@TankAbraham 没有，我打算自己训练，https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech

**Comment by ghost** [comment]
> @TankAbraham 没有，我打算自己训练，https://github.com/yeyupiaoling/PaddlePaddle-DeepSpeech

那您试者把音频的采样率调整为 8k 了吗？

**Comment by yeyupiaoling** [comment]
@TankAbraham 试过了，效果还是不好。

**Comment by ghost** [comment]
大家好，我用自己的语音文件 flac 格式复现出了模型的效果。

调整音频采样率用如下bash命令：

```bash
ffmpeg -i [input file path] -ar 8000 [output file path]
```
