### ISSUE TITLE
AttributeError: 'module' object has no attribute 'RNNCell'

### ISSUE THREAD

**Issue by lamudazh** [PaddlePaddle/DeepSpeech#386]
I user docker to run based on the guide, but when it failed when running examples, could you help ?

/DeepSpeech/examples/tiny {develop} sh run_train.sh
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from model_utils.model import DeepSpeech2Model
  File "/DeepSpeech/model_utils/model.py", line 23, in <module>
    from model_utils.network import deep_speech_v2_network
  File "/DeepSpeech/model_utils/network.py", line 62, in <module>
    class RNNCell(fluid.layers.RNNCell):
AttributeError: 'module' object has no attribute 'RNNCell'

**Comment by lamudazh** [comment]
this issue solved by install latest paddlepaddle

**Comment by chadlwm** [comment]
@lamudazh  it works for me

**Comment by lfchener** [comment]
> I user docker to run based on the guide, but when it failed when running examples, could you help ?
> 
> /DeepSpeech/examples/tiny {develop} sh run_train.sh
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> Traceback (most recent call last):
> File "train.py", line 9, in
> from model_utils.model import DeepSpeech2Model
> File "/DeepSpeech/model_utils/model.py", line 23, in
> from model_utils.network import deep_speech_v2_network
> File "/DeepSpeech/model_utils/network.py", line 62, in
> class RNNCell(fluid.layers.RNNCell):
> AttributeError: 'module' object has no attribute 'RNNCell'

You most use PaddlePaddle 1.6.0 or later.
![image](https://user-images.githubusercontent.com/6771821/68916138-a0f7a480-079f-11ea-8a6f-4bcd04bf1cd5.png)

**Comment by jerrylususu** [comment]
If you're using the Docker container, run the following command to update PaddlePaddle, which should fix the problem. (Python 2.7 + CUDA 10)
`python -m pip install paddlepaddle-gpu==1.6.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by ghost** [comment]
Hello,
Any other way to get the file?  I am using the docker file. 
``
 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)",)': /simple/paddlepaddle-gpu/

 ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.6.2.post107 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==1.6.2.post107
``

**Comment by plseal** [comment]
im in japan and i reinstall paddlepaddle-gpu  1.6.2.post107. it works!
```
python -m pip install paddlepaddle-gpu==1.6.2.post107
```

**Comment by vuvincent** [comment]
> Hello,
> Any other way to get the file? I am using the docker file.
> ``
> WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)",)': /simple/paddlepaddle-gpu/
> 
> ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==1.6.2.post107 (from versions: none)
> ERROR: No matching distribution found for paddlepaddle-gpu==1.6.2.post107
> ``

Use this command to quote the indexes for finding that distribution:

`python -m pip install paddlepaddle-gpu==1.6.2.post107 -i https://pypi.tuna.tsinghua.edu.cn/simple`

**Comment by danielkope** [comment]
Why is the docker not up2date?

**Comment by bigpo** [comment]
you should update to 1.8.5 directly, otherwise you may encounter another error #462
