### ISSUE TITLE
baidu_cn1.2K的模型的params.pdparams如何直接用来识别？

### ISSUE THREAD

**Issue by jchua127** [PaddlePaddle/DeepSpeech#388]
从官网下载下来的BaiduCN1.2K模型中的params.pdparams该如何使用？
infer.py中的model_path要求是params.tar.gz这种格式的，请问这个params.pdparams该如何使用呀，谢谢。

![image](https://user-images.githubusercontent.com/26765635/69219622-2b7c4180-0bae-11ea-84bb-c792ef21d1f0.png)

**Comment by lfchener** [comment]
@jchua127  可以参考 examples/aishell/run_infer_golden.sh 来设置文件路径。

**Comment by jchua127** [comment]
> @jchua127 可以参考 examples/aishell/run_infer_golden.sh 来设置文件路径。

哦 明白了 是参考aishell中的download_model的例子来下载BaiduCN1.2K的模型是吧，谢谢了。

**Comment by jchua127** [comment]
> @jchua127 可以参考 examples/aishell/run_infer_golden.sh 来设置文件路径。

你好 参考aishell下载BaiduCN1.2K的模型，解压后也没有params.tar.gz，run_infer_golden中的也是用的params.tar.gz这个文件，应该如何设置呢？

![image](https://user-images.githubusercontent.com/26765635/69225216-e9a4c880-0bb8-11ea-8f1b-8ddaad94225e.png)

**Comment by gnaytx** [comment]
model_path 为解压后所在的目录即可， 他会自己拼接  目录 + params.pdparams

**Comment by jchua127** [comment]
> model_path 为解压后所在的目录即可， 他会自己拼接 目录 + params.pdparams

好像model_path要求必须是压缩包吧，我改成了目录，会报错的，‘

![image](https://user-images.githubusercontent.com/26765635/69299289-2de0a900-0c4b-11ea-9626-77543d39682a.png)

**Comment by jchua127** [comment]
问题已解决，是由于我下载的地址不对，导致没有params.tar.gz，应该用https://deepspeech.bj.bcebos.com/demo_models/baidu_cn1.2k_model.tar.gz这个地址，感谢大家的回复。
