### ISSUE TITLE
stuck at [INFO 2017-11-29 18:42:07,933 model.py:230] begin to initialize the external scorer for decoding

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#39]
demo server is stuck at [INFO 2017-11-29 18:42:07,933 model.py:230] begin to initialize the external scorer for decoding. No response on client side.

vocab_path: data/librispeech/eng_vocab.txt
warmup_manifest: data/librispeech/manifest.test-clean
------------------------------------------------
I1129 18:41:38.429951 29571 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2017-11-29 18:41:38,444 layers.py:2689] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-11-29 18:41:38,445 layers.py:3244] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-11-29 18:41:38,446 layers.py:7401] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-11-29 18:41:38,447 layers.py:2689] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-11-29 18:41:38,448 layers.py:3244] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-11-29 18:41:38,449 layers.py:7401] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
-----------------------------------------------------------
Warming up ...
-----------------------------------------------------------
ASR Server Started.
Received utterance[length=122880] from 10.40.0.206, saved to demo_cache/20171129184205_10.40.0.206.wav.
[INFO 2017-11-29 18:42:07,933 model.py:230] begin to initialize the external scorer for decoding

**Comment by john81529** [comment]
请问，你是怎么启动的呢？
