### ISSUE TITLE
Add download url for BaiduEN8k Model.

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/DeepSpeech#4]

**Comment by pkuyym** [comment]
Already fixed by https://github.com/PaddlePaddle/DeepSpeech/pull/5

**Comment by PES2g** [comment]
The download would failed after a few time. Could you check the url and model ?

**Comment by pkuyym** [comment]
@PES2g For this problem，please refer https://github.com/PaddlePaddle/models/issues/301

**Comment by PES2g** [comment]
@pkuyym, problem solved. Thanks.
