### ISSUE TITLE
Python process running after 'run_infer.sh'

### ISSUE THREAD

**Issue by yangliu2** [PaddlePaddle/DeepSpeech#41]
Each time after I ran 'run_infer.sh' or any of scripts in 'examples/', I can still see python process running when I type 'ps' in terminal. When I run 'nvidia-docker' the GPU memory are still being used. I had to manually 'kill -9' all the python processes. Is this a known issue? Any way of killing these python processes automatically?

**Comment by kuke** [comment]
@yangliu2  If you didn't change anything in the script ```run_test.sh```, this script will evaluate your own model and seems that this model is not well-trained. To get lower WER, you can continue to train this model until sufficient convergence or try another script ```run_test_golden.sh``` to test the golden model provided by us.

**Comment by yangliu2** [comment]
I closed it since I figured out the problem. I wasn't using the mean-std file came with the trained model.
