### ISSUE TITLE
python process still running after 'run_infer.sh'

### ISSUE THREAD

**Issue by yangliu2** [PaddlePaddle/DeepSpeech#42]
Each time after I ran 'run_infer.sh' or any of scripts in 'examples/', I can still see python process running when I type 'ps' in terminal. When I run 'nvidia-docker' the GPU memory are still being used. I had to manually 'kill -9' all the python processes. Is this a known issue? Any way of killing these python processes automatically?

**Comment by pkuyym** [comment]
Thanks, we have encountered this problem too and will try to fix it. 

For ```Any way of killing these python processes automatically?```, I suggest to use 

```shell
ps -ef | awk '$3==PROCESS_ID{print $2}' | xargs -I {} kill -9 {}
```

**Comment by yangliu2** [comment]
Thanks. I used 'pkill python'.
