### ISSUE TITLE
BaiduCN1.2k Model 显示 to-be added？

### ISSUE THREAD

**Issue by lezasantaizi** [PaddlePaddle/DeepSpeech#43]
这个模型可以提供一下吗？谢谢啦！

**Comment by pkuyym** [comment]
这个模型已经训练完成，需要等验证、批准后发布，请您耐心等待一下

**Comment by lezasantaizi** [comment]
期待！ @pkuyym

**Comment by harold-yh** [comment]
大概什么时候能提供呢？thanks

**Comment by pkuyym** [comment]
Already updated, please check again.

**Comment by harold-yh** [comment]
Downloading,thanks

**Comment by iou2much** [comment]
http://cloud.dlnel.org/filepub/?uuid=499569a6-0025-4f40-83e6-1c99527431a6

代码里的这个链接总是下到一半就断了..

**Comment by pkuyym** [comment]
@iou2much Please refer the following issue:
https://github.com/PaddlePaddle/DeepSpeech/issues/74
