### ISSUE TITLE
n best results

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#44]
Is there to way to tell demo server to send n best recognition results rather than just one? thanks.

**Comment by pkuyym** [comment]
Please check these lines:
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_server.py#L104
https://github.com/PaddlePaddle/DeepSpeech/blob/develop/deploy/demo_server.py#L191

**Comment by cogmeta** [comment]
Awesome, Thank you.
