### ISSUE TITLE
c/c++ decoder

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#48]
Is there a way to create c/c++ decoder for production deployment?

**Comment by pkuyym** [comment]
If possible, please list the detailed requirements for the production deployment. Currently, the decoder is written by c/c++ backend and wrapped to python api via swig, of course, you can directly call the decoder using c/c++ api.

**Comment by yyhlvdl** [comment]
那么，在我看解码器的代码的时候，是看没有进行 sh setup.sh的那些在decoders文件夹下的swig文件中的c++文件吗？

**Comment by cogmeta** [comment]
Can you please provide the reference to relevant files/line numbers? Thanks

**Comment by pkuyym** [comment]
For CAPI, please refer to https://github.com/PaddlePaddle/Paddle/blob/d398b96823e6df38897fc881b5b71d7bc66013dc/doc/v2/howto/capi/workflow_of_capi_cn.md
