### ISSUE TITLE
Correct the error rate's computation for multiple sentences

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/DeepSpeech#50]

**Comment by pkuyym** [comment]
Here, we align the computation logic to kaldi:
https://github.com/kaldi-asr/kaldi/blob/a3441c243638b029d254c19081f0f847326322b0/src/bin/compute-wer.cc#L92-L94

https://github.com/kaldi-asr/kaldi/blob/a3441c243638b029d254c19081f0f847326322b0/src/bin/compute-wer.cc#L104-L105
