### ISSUE TITLE
aishell的deploy出现的错误

### ISSUE THREAD

**Issue by john81529** [PaddlePaddle/DeepSpeech#59]
因为实验室硬件的问题，我实在是无法自己训练完aishell数据，那估计需要一个月。所以，我使用了你们发布的中文模型，来尝试识别我自己的语音。
warmup_manifest是使用aishell的test数据，然后出现这样的错误。
```
root@70ae495f3c96:/DeepSpeech# python deploy/demo_server.py 
-----------  Configuration Arguments -----------
alpha: 2.15
beam_size: 500
beta: 0.35
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: asset/preprocess/mean_std.npz
model_path: asset/train/aishell_model .tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: False
vocab_path: asset/preprocess/vocab.txt
warmup_manifest: asset/preprocess/test
------------------------------------------------
I1205 06:26:07.198161    93 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
[INFO 2017-12-05 06:26:09,496 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 06:26:09,498 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 06:26:09,499 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 06:26:09,500 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-05 06:26:09,502 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-05 06:26:09,503 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'asset/data/aishell/wav/test/S0765/BAC009S0765W0205.wav')
Traceback (most recent call last):
  File "deploy/demo_server.py", line 219, in <module>
    main()
  File "deploy/demo_server.py", line 215, in main
    start_server()
  File "deploy/demo_server.py", line 199, in start_server
    num_test_cases=3)
  File "deploy/demo_server.py", line 135, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "deploy/demo_server.py", line 190, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/DeepSpeech/deploy/../model_utils/model.py", line 207, in infer_batch
    output_layer=self._log_probs, parameters=self._parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___conv_0__.w0
```

**Comment by pkuyym** [comment]
看起来是模型跟配置不匹配，请double check一下所下载模型的md5跟预期是否一致

**Comment by john81529** [comment]
恩，其实是代码是基于librispeech的，我修改了适合aishell。不过，出现了新的错误：
root@70ae495f3c96:/DeepSpeech#  python deploy/demo_server.py 
-----------  Configuration Arguments -----------
alpha: 2.15
beam_size: 500
beta: 0.35
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: asset/preprocess/mean_std.npz
model_path: asset/train/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: True
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: True
use_gru: True
vocab_path: asset/preprocess/vocab.txt
warmup_manifest: asset/preprocess/test
------------------------------------------------
I1205 07:03:56.085741   180 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
[INFO 2017-12-05 07:03:56,454 layers.py:2606] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 07:03:56,454 layers.py:3133] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 07:03:56,455 layers.py:7224] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-05 07:03:56,455 layers.py:2606] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-05 07:03:56,456 layers.py:3133] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-05 07:03:56,456 layers.py:7224] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'asset/data/aishell/wav/test/S0765/BAC009S0765W0205.wav')
[INFO 2017-12-05 07:04:00,237 model.py:230] begin to initialize the external scorer for decoding
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  kenlm/lm/binary_format.cc:160 in void* lm::ngram::BinaryFormat::LoadBinary(std::size_t) threw FormatLoadException because `file_size != util::kBadSize && file_size < total_map'.
Binary file has size 31282576 but the headers say it should be at least 2953349384
*** Aborted at 1512457440 (unix time) try "date -d @1512457440" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0xb4) received by PID 180 (TID 0x7f86a79b1700) from PID 180; stack trace: ***
    @     0x7f86a758e390 (unknown)
    @     0x7f86a71e8428 gsignal
    @     0x7f86a71ea02a abort
    @     0x7f868f4e284d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f868f4e06b6 (unknown)
    @     0x7f868f4e0701 std::terminate()
    @     0x7f868f4e0919 __cxa_throw
    @     0x7f8683ef265f lm::ngram::BinaryFormat::LoadBinary()
    @     0x7f8683efd605 lm::ngram::detail::GenericModel<>::GenericModel()
    @     0x7f8683ef43db lm::ngram::LoadVirtual()
    @     0x7f8684025a5f Scorer::load_lm()
    @     0x7f8684029041 Scorer::setup()
    @     0x7f868402913d Scorer::Scorer()
    @     0x7f8683fe3f48 _wrap_new_Scorer
    @           0x4c468a PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4de6fe (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4f492e (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4c9faf PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4de6fe (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4f492e (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4f46a7 (unknown)
    @           0x4b670c (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4c9faf PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4ca8d1 PyEval_EvalFrameEx
Aborted (core dumped)
也许，我应该修改add_arg('host_port',        int,    8086,    "Server's IP port.")
add_arg('beam_size',        int,    500,    "Beam search width.")的大小来适应我的硬件。

**Comment by pkuyym** [comment]
@john81529 看起来像是语言模型没有下载完全，你看一下问件大小和md5是否跟脚本匹配

**Comment by john81529** [comment]
是的，这个问题解决了。然后，我开始执行python -u deploy/demo_client.py，本来我是想在docker中执行的，只是显示没有pyuput这个模块，于是我就在命令端执行了这个文件，同时，root@14e9a03548c8:/DeepSpeech# python deploy/demo_server.py 这个文件在docker里面执行，于是出现这样的错误：
yyh@yyh-System-Product-Name:~/DeepSpeech$ python -u deploy/demo_client.py
ALSA lib pcm_dsnoop.c:606:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Start Recording ...                Traceback (most recent call last):
  File "deploy/demo_client.py", line 58, in callback
    sock.connect((args.host_ip, args.host_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

**Comment by john81529** [comment]
同时，Warming up ...
('Warm-up Test Case %d: %s', 0, u'asset/data/aishell/wav/test/S0765/BAC009S0765W0205.wav')
[INFO 2017-12-05 10:06:54,859 model.py:230] begin to initialize the external scorer for decoding
[INFO 2017-12-05 10:06:55,001 model.py:241] language model: is_character_based = 1, max_order = 5, dict_size = 0
[INFO 2017-12-05 10:06:55,001 model.py:242] end initializing scorer. Start decoding ...
表明ASR Server Started.没有实现
