### ISSUE TITLE
Illegal instruction (core dumped) when run sh run_train.sh

### ISSUE THREAD

**Issue by gdfspy** [PaddlePaddle/DeepSpeech#60]
I follow the steps to do the test, but when run "sh run_train.sh", the application crashed.
I set the GPU to False, and when I test by PythonCharm, this line cause the crash:

import py_paddle.swig_paddle as api

**Comment by pkuyym** [comment]
Which example did you try? Please make sure ```swig-decoders``` has been installed successfully, you can check it by ```pip show swig-decoders``` and the version of ```swig-decoders``` should be 01.1

**Comment by gdfspy** [comment]
Version: 1.1

Process finished with exit code 132 (interrupted by signal 4: SIGILL)

**Comment by gdfspy** [comment]
I try the examples/tiny

**Comment by pkuyym** [comment]
It looks weird, please paste the full log, thanks

**Comment by gdfspy** [comment]
![111](https://user-images.githubusercontent.com/733680/33595322-8fa49082-d9d2-11e7-99ae-7c6e04bf279e.png)

**Comment by pkuyym** [comment]
What's your platform? Can you run PaddlePaddle normally?

**Comment by gdfspy** [comment]
Ubuntu 16.04 -> docker -> pull paddlepaddle/paddle

**Comment by pkuyym** [comment]
You can try our docker image. https://github.com/PaddlePaddle/DeepSpeech#running-in-docker-container

**Comment by gdfspy** [comment]
So deep speech only support GPU version now?

**Comment by pkuyym** [comment]
Not really, CPU is also supported, currently I can't figure out the reason just based on your information.

**Comment by kuke** [comment]
@gdfspy This Docker image can only run with the support of NVIDIA GPUs even if ```use_gpu=False```, otherwise something weird will happen. It doesn't mean that DS2 only support GPU mode. You can setup local environment or continue to run in Docker on another machine with GPUs.

**Comment by gdfspy** [comment]
OK, I'll try it later.

**Comment by gdfspy** [comment]
The reason is my old CPU not support AVX2.

**Comment by hui001** [comment]
my cpu doesn't support AVX2 either, could you please tell me how you solved it finally?
