### ISSUE TITLE
couldn't download the noise data

### ISSUE THREAD

**Issue by yangliu2** [PaddlePaddle/DeepSpeech#62]
I have some noisy audio files and I'm trying to put noise in clean data (like librispeech) to generate a denoise autoencoder. The link for downloading noise data in '/data/noise/chime3_background.py' doesn't exist anymore. Wget return a 404. Do you guys still have that data?

**Comment by gdfspy** [comment]
https://chime.myairbridge.com/eng/#!/link/5b9rm9zce

**Comment by gdfspy** [comment]
http://spandh.dcs.shef.ac.uk/chime_challenge/chime_download.html

**Comment by yangliu2** [comment]
I used the same link here to download. But I get errors using browser and 404 html page using wget.
