### ISSUE TITLE
Data augmentor problem

### ISSUE THREAD

**Issue by lispc** [PaddlePaddle/DeepSpeech#63]
change_speed function changes tempo and pitch both. 
Is it reasonable? Is just changing tempo a better choice?

[code here](https://github.com/PaddlePaddle/DeepSpeech/blob/develop/data_utils/audio.py#L301)

**Comment by pkuyym** [comment]
The code shows that interpolation is applied to the first dimension.
If possible, please point out where the pitch is modified.

**Comment by lispc** [comment]
"interpolation is applied to the first dimension" means changing tempo and pitch at the same time.
You can listen to one audio segment after the change_speed function and will find that the pitch is changed.
The current method is like 'sox speed' command, just changing tempo in sox is 'sox tempo' command, which is usually implemented by WSOLA algorithm.

**Comment by kuke** [comment]
@lispc Changing the speed of audio signal is a proven effective approach for data augmentation. [Here](http://www.danielpovey.com/files/2015_interspeech_augmentation.pdf) is an article for you, in which the authors conclude “Speed perturbation, which emulates both VTLP and tempo perturbation, is shown to give more WER improvement than either of those methods”.

**Comment by lispc** [comment]
Great! A very good theoretical explanation!
