### ISSUE TITLE
'slice_from_file' in 'data_util/audio.py'

### ISSUE THREAD

**Issue by yangliu2** [PaddlePaddle/DeepSpeech#70]
The default behavior for the method is to get AudioSegment from begin to end if 'start' or 'end' is not provided. 
https://github.com/PaddlePaddle/DeepSpeech/blob/4bf526e78d8531551fce1f4d8bfb119e297812d7/data_utils/audio.py#L99
On line 99, 'end = 0. if end is None else end' should be 'end = duration if end is None else end'. 
Please let me know if this is what was intended or I missed something. 

Thanks.

**Comment by pkuyym** [comment]
Yes, I think your right, this is a bug. Thanks

**Comment by zh794390558** [comment]
fixed.
