### ISSUE TITLE
Problem about Librispeech data process and training params

### ISSUE THREAD

**Issue by zh794390558** [PaddlePaddle/DeepSpeech#72]
The largest sample of LibriSpeech is about 40s, how do you use these data? Or the full data is used in your training process?  I see your batch size is 10, does it can be larger, e.g. 32?

Does rnn hidden size is sensitive to the result? Now you use 2048, does 1024 or other size is sensitive to the result?

**Comment by pkuyym** [comment]
Which example do you try? There is a parameter to filter out instance with long duration, for librispeech example, this threshold is 27s. Of course, you can try larger batch size if your GPU's memory is big enough. 

Size of rnn is a critical parameter, please tune this parameter according to your data.

**Comment by zh794390558** [comment]
@pkuyym Do the WER of LibriSpeech rescored  with the released English LM ?

**Comment by pkuyym** [comment]
@zh794390558 Yes, what's the problem?
