### ISSUE TITLE
中文语言模型无法下载，下了几十M之后就像断了，一直都这样

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#74]
只要是这个地址的文件都是这样子的
http://cloud.dlnel.org/filepub/?uuid=245d02bb-cd01-4ebe-b079-b97be864ec37

**Comment by pkuyym** [comment]
Seems our DNS forwarding limits the download, you can set /etc/hosts file mannually adding:

180.76.189.142  cloud.dlnel.org
and try download again.

**Comment by witkeyshare** [comment]
ok thanks

**Comment by bliunlpr** [comment]
I have added 180.76.189.142  cloud.dlnel.org to /etc/hosts, but failed to download the language model. How can I check? Thanks

**Comment by pkuyym** [comment]
@bliunlpr Please paste more information, thx

**Comment by bliunlpr** [comment]
I have solved it.  I updated /etc/hosts, but I forgot to restart my network service. When I restarted the service, the problem has been sovled. Thanks for your commit! @pkuyym

**Comment by pkuyym** [comment]
@bliunlpr Great.
