### ISSUE TITLE
decoder_utils.h:55: Error: Syntax error in input(1).

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#76]
compile decoders  find error：

decoder_utils.h:55: Error: Syntax error in input(1).

**Comment by witkeyshare** [comment]
[root@bogon swig]# sh setup.sh 
Install decoders ...
decoder_utils.h:55: Error: Syntax error in input(1).
running install
running bdist_egg
running egg_info
writing swig_decoders.egg-info/PKG-INFO
writing top-level names to swig_decoders.egg-info/top_level.txt
writing dependency_links to swig_decoders.egg-info/dependency_links.txt
file swig_decoders.py (for module swig_decoders) not found
reading manifest file 'swig_decoders.egg-info/SOURCES.txt'
writing manifest file 'swig_decoders.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file swig_decoders.py (for module swig_decoders) not found
file swig_decoders.py (for module swig_decoders) not found
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/_swig_decoders.so -> build/bdist.linux-x86_64/egg
creating stub loader for _swig_decoders.so
byte-compiling build/bdist.linux-x86_64/egg/_swig_decoders.py to _swig_decoders.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying swig_decoders.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying swig_decoders.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying swig_decoders.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying swig_decoders.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/swig_decoders-1.1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing swig_decoders-1.1-py2.7-linux-x86_64.egg
Removing /usr/lib64/python2.7/site-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg
Copying swig_decoders-1.1-py2.7-linux-x86_64.egg to /usr/lib64/python2.7/site-packages
swig-decoders 1.1 is already the active version in easy-install.pth

Installed /usr/lib64/python2.7/site-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg
Processing dependencies for swig-decoders==1.1
Finished processing dependencies for swig-decoders==1.1

**Comment by pkuyym** [comment]
Please make sure ```swig>=3.0.0``` and try again.

**Comment by zy486at189cn** [comment]
我也遇到了这个问题，不知如何解决？
