### ISSUE TITLE
lanaguge model 的blank id能从0 开始吗？

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/DeepSpeech#79]
lanaguge model 的blank id能从0 开始吗？

因为我训练出来的模型，其blank id是从0 开始的，有办法修正她，让她不是voc.size吗？

**Comment by pkuyym** [comment]
这个可能得改decoder内部的逻辑了，简单修复恐怕不行

**Comment by guoying1030** [comment]
@pkuyym   如果我再进入ctc_beam_search_decoder之前，把prob_seqs里面的，每一行里面，把第一个和最后一个的值进行交换。。。。这样也算变相的把blank id换成了最后一个吗？就是voc.size

**Comment by guoying1030** [comment]
@pkuyym ，也就是交换第一列和最后一列的值。。。这样可以做到把blankid 换到最后吗？

**Comment by pkuyym** [comment]
@guoying1030 听起来可以，不过decoder结果你需要重新映射过来，可以试下看，如果遇到问题我们再讨论

**Comment by guoying1030** [comment]
@pkuyym ,,我试了下，结果是可以的。


beam_search_results=swig_wrapper.ctc_beam_search_decoder(prob_seq,vocab_list,beam_size,ext_scoring_func=ext_score)

print beam_search_results[0][1]



这样就可以拿到最终的结果了吗？？？

**Comment by guoying1030** [comment]
swig_wrapper.ctc_beam_search_decoder(prob_seq,vocab_list,beam_size,ext_scoring_func=ext_score)


这个函数返回了多个结果，我应该使用哪个呢？？？？

每个都是一个二元组，那么第一列是一个分数，后面是结果？


应该用分数最高的吗？

**Comment by pkuyym** [comment]
@guoying1030 嗯，返回的结果是排过序的，你取top的结果就好

**Comment by guoying1030** [comment]
5.65099954605-充电加热片清洁
-3.14632582664-充电盒加热片清洁
10.722237587-充电加热清洁
0.726086080074-充电金加热片清洁
1.92503786087-充电盒加热清洁
5.79635477066-充电金加热清洁
6.89821386337-充电式加热片清洁
4.04756975174-充电完加热片清洁
10.1655168533-充电加热片清清
2.90369915962-充电急加热片清洁
2.99799275398-充电食加热片清洁
12.9944171906-充电加热外清洁
3.69065904617-充电盖加热片清洁
6.2815785408-充电会加热片清洁
5.61768007278-充电煮加热片清洁
5.92196464539-充电荒加热片清洁
1.36818802357-充电盒加热片清清
15.87251091-充电加热水清洁
12.7559099197-充电加热升清洁
11.9684896469-充电式加热清洁
15.2367572784-充电加热清清
5.20564699173-充电常加热片清洁
3.85345482826-充电命加热片清洁
7.57977581024-充电缆加热片清洁
6.39660692215-充电点加热片清洁
4.30826234818-充电徐加热片清洁
4.19708776474-充电盒加热外清洁
4.16304349899-充电竞加热片清洁
4.54313850403-充电余加热片清洁
9.11784648895-充电完加热清洁
5.33842134476-充电意加热片清洁
4.05095624924-东电盒加热片清洁
6.92233419418-充电镜加热片清洁
13.2523450851-充电加热出清洁
2.83694291115-充电盆加热片清洁
7.97396802902-充电急加热清洁
6.43943119049-充电盒加热清清
12.0488233566-充电盒加清洁
12.0104141235-充电加热十清洁
5.24047803879-充电金加热片清清
11.5781812668-充电加热片清活
14.4824733734-充电加热片清污
11.2210063934-充电加热片清告
11.9878234863-充电加热片清渣
12.5214834213-充电加热片清浩
10.3107481003-充电金加热清清
12.1799507141-充电加热片清游
16.5593738556-充电加热片洁
12.011346817-充电加热片清语
12.5178279877-充电加热片清治



这个结果是没有做任何排序的呀。。。。那么我取分数最高的吗？？

**Comment by kuke** [comment]
@guoying1030 这个分数被处理过，不具有参考意义。所以你直接按这个顺序取top结果就行。
