### ISSUE TITLE
有一个层不清楚

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/DeepSpeech#80]
在network中有一个层paddle.layer.sub_seq，这个层我在百度的api中，实在是找不到，有人可以告诉我在哪里吗？

**Comment by pkuyym** [comment]
请参考
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L7396

**Comment by yyhlvdl** [comment]
多谢，就我的理解，network中，conv2seq = paddle.layer.block_expand是把卷积图转为矩阵，那么，paddle.layer.sub_seq这一步是将矩阵中对应的batch补0的区域给清除掉。我的疑惑是，返回的是矩阵呢？还是序列呢？

**Comment by yyhlvdl** [comment]
谢谢。就我的理解，paddle.layer.sub_seq这一步生成的矩阵，paddle.layer.sub_seq这一步是把batch补0的区域对应的地方删除，那么，这一步返回的是矩阵还是序列呢？因为，我在试着把这步的结果调出来查看，输入到gru的时候，报错：F1221 12:37:28.518826  4116 RecurrentGradientMachine.cpp:417] Check failed: !commonSeqInfo_.empty() At least one input needs to be sequence or subsequence
说实话，官方api中的很多层的数据结构真的非常不清楚。
