### ISSUE TITLE
run deploy/demo_client.py error

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#81]
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave

Start Recording ...                                              Speech[length=110592] Sent.
Traceback (most recent call last):
  File "/home/zxj/DeepSpeech/deploy/demo_client.py", line 63, in callback
    received = sock.recv(1024)
socket.error: [Errno 104] Connection reset by peer

anyone know how to solve this error?

**Comment by kuke** [comment]
Seems that you have a problem with the ALSA configuration. Please try [this solution](https://www.raspberrypi.org/forums/viewtopic.php?t=136974) to see if it works.

**Comment by pkuyym** [comment]
Please make sure the communication between client and server is normal. 
```
Traceback (most recent call last):
File "/home/zxj/DeepSpeech/deploy/demo_client.py", line 63, in callback
received = sock.recv(1024)
socket.error: [Errno 104] Connection reset by peer
```
