### ISSUE TITLE
DeepSpeech/examples/librispeech run_infer_golden.sh inference failed

### ISSUE THREAD

**Issue by jayiind** [PaddlePaddle/DeepSpeech#83]
I downloaded librispeech model and ran inference with run_infer_golden.sh. Inference failed with the following error
F1219 07:07:20.167259 36066 MKLDNNConcatLayer.cpp:38] Check failed: (size_t)ic * ih * iw == inputLayers_[0]->getSize() (0 vs. 2048)
*** Check failure stack trace: ***
    @     0x7f46a4c0226d  google::LogMessage::Fail()
    @     0x7f46a4c045b8  google::LogMessage::SendToLog()
    @     0x7f46a4c01d7b  google::LogMessage::Flush()
    @     0x7f46a4c0548e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f46a4a01d0d  paddle::MKLDNNConcatLayer::reshape()
    @     0x7f46a48bfa25  paddle::MKLDNNLayer::forward()
    @     0x7f46a486be77  paddle::NeuralNetwork::forward()
    @     0x7f46a47cd816  _wrap_GradientMachine_forward
    @           0x4c45fa  PyEval_EvalFrameEx
    @           0x4c9d7f  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4ddd6a  (unknown)
    @           0x4c4bdc  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4c24a9  PyEval_EvalCode
    @           0x4f19ef  (unknown)
    @           0x4ec372  PyRun_FileExFlags
    @           0x4eaaf1  PyRun_SimpleFileExFlags
    @           0x49e208  Py_Main
    @     0x7f471fe55830  __libc_start_main
    @           0x49da59  _start
Aborted (core dumped)
Failed in inference!

**Comment by kuke** [comment]
How do you compile PaddlePaddle? MKLDNN maybe goes wrong here.

**Comment by jayiind** [comment]
i compiled paddle paddle from sources. 
cmake .. -DWITH_MKL=ON -DMAKE_INSTALL_PREFIX=${install_dir}
make -j `nproc`

this is the output of paddle version
PaddlePaddle 0.10.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

**Comment by kuke** [comment]
Please set ```-DWITH_MKLDNN=OFF``` and recompile PaddlePaddle. MKLDNN has not supported RNNs yet.

**Comment by jayiind** [comment]
ok. so the command to be used is
cmake .. -DWITH_MKL=ON -DWITH_MKLDNN=OFF -DMAKE_INSTALL_PREFIX=${install_dir}

is this correct?
and while inference, 
use_mkl=True
correct?

**Comment by luotao1** [comment]
The original `cmake .. -DWITH_MKL=ON` is ok, but while training and inference, don't set `use_mkldnn=true`.

**Comment by jayiind** [comment]
ok. but still will it use the mkl libraries?

**Comment by luotao1** [comment]
Yes, it will use mkl libraries default.
> i compiled paddle paddle from sources

Do you use the latest develop sources, or could you tell use the commit id of your sources?

**Comment by jayiind** [comment]
e09e21beeee4368f727b189226b0560031b4f0ad this is the commit id
