### ISSUE TITLE
What language model do you use in the LibriSpeech benchmark?

### ISSUE THREAD

**Issue by ksellesk** [PaddlePaddle/DeepSpeech#84]
We can not get a WER 6.85% with CommonCrawl(en.00) Language model.

Do you use the CommonCrawl(en.00) Language model in the LibriSpeech benchmark?

**Comment by pkuyym** [comment]
Yes, the English LM has been released and the url is http://paddlepaddle.bj.bcebos.com/model_zoo/speech/common_crawl_00.prune01111.trie.klm

**Comment by sivagururaman** [comment]
Is this path for the language model correct? I am not able to download the model from this link.... Can you please help?

**Comment by sahilanguralla** [comment]
+1
