### ISSUE TITLE
batch-norm paramters

### ISSUE THREAD

**Issue by bliunlpr** [PaddlePaddle/DeepSpeech#85]
When I print the paramters of the model, I found:
___batch_norm_2__.w0 (1, 3072)
___batch_norm_2__.w1 (1, 3072)
___batch_norm_2__.w2 (1, 3072)
___batch_norm_2__.wbias (1, 3072).
I wonder why batch-norm layer has four paramters(w0, w1, w2, wbias)?  I guess these are \\gamma, \\beta, running_average, running_var.  So what's the meaning for batch-norm paramters respectively? Thanks very much!

**Comment by pkuyym** [comment]
_batch_norm_2.w0 for gamma
_batch_norm_2.wbias for beta
_batch_norm_2.w1 for mean
_batch_norm_2.w2 for variance

**Comment by bliunlpr** [comment]
Thanks! 
 I found CNN paramters are flattened, such as  ___conv_1__.w0 (1, 473088).  It is paramter of CNN which filter_size=(11, 21), num_channels_in=32, num_channels_out=64. What is the original shape of paramters? [64, 32, 21, 11]? Thanks!

**Comment by pkuyym** [comment]
The saving order is row-first and the shape is [out_channels_num, in_channels_num, h, w], for your case the shape is [64, 32, 21, 11].
It seems that you are trying to parse weights of the model?

**Comment by bliunlpr** [comment]
Yes, I want to do some analysis of model paramter weights distribution. So I asked the above questions. Thanks for your commit!

**Comment by wudeshi** [comment]
> Yes, I want to do some analysis of model paramter weights distribution. So I asked the above questions. Thanks for your commit!

hi,do you know what '___gru_0__.w0 (1024, 3072)' means?

**Comment by wudeshi** [comment]
> _batch_norm_2.w0 for gamma
> _batch_norm_2.wbias for beta
> _batch_norm_2.w1 for mean
> _batch_norm_2.w2 for variance

___gru_0__.w0 (1024, 3072) . Where is the update weight, reset weight, candidate weight respectively
