### ISSUE TITLE
BaiduCN1.2k Model识别结果不对

### ISSUE THREAD

**Issue by harold-yh** [PaddlePaddle/DeepSpeech#94]
使用deploy_server.py和deploy_client.py进行识别，声音来源麦克风，音频文件正常，识别结果不对
语言模型使用：Mandarin LM Small     Speech Model使用：BaiduCN1.2k Model，参数按照BaiduCN1.2k Model的README设置，识别出来的结果完全不对，一句话只识别成一个字，并且还是错的，麻烦指导一下是我使用的不对吗？
```
-----------  Configuration Arguments -----------
alpha: 1.15
beam_size: 500
beta: 0.15
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: models/lm/MandarinLMSmall.klm
mean_std_path: models/baidu_cn1.2k_model/mean_std.npz
model_path: models/baidu_cn1.2k_model/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: 0
specgram_type: linear
speech_save_dir: demo_cache
use_gpu: 0
use_gru: 1
vocab_path: models/baidu_cn1.2k_model/vocab.txt
------------------------------------------------
```
结果全是下面这样的
Recognition Results: 人
Recognition Results: 在
Recognition Results: 我

**Comment by pkuyym** [comment]
这个问题主要是采样频率导致的，baidu_cn1.2k的采样频率是8k，但是默认应该是16k，你可以在demo_server.py和demo_client.py里面设置这个频率，改成8k

**Comment by harold-yh** [comment]
已修改为8000，识别结果还是差不多的
Recognition Results: 我有时候真的
Start Recording ... Speech[length=229376] Sent.
Recognition Results: 那
Start Recording ... Speech[length=192512] Sent.
Recognition Results: 我啥事都
Start Recording ... Speech[length=135168] Sent.
Recognition Results: 我
               Start Recording ... Speech[length=253952] Sent.
Recognition Results: 我还是

存储的录音文件信息如下：
Input File     : '../../demo_cache/20171221100507_127.0.0.1.wav'
Channels       : 1
Sample Rate    : 8000
Precision      : 32-bit
Duration       : 00:00:07.94 = 63488 samples ~ 595.2 CDDA sectors
File Size      : 254k
Bit Rate       : 256k
Sample Encoding: 32-bit Signed Integer PCM

**Comment by pkuyym** [comment]
请打印一下warmup的识别结果？

**Comment by harold-yh** [comment]
warmup相关段被我注释了，它需要使用manifest，baidu_cn1.2k没有提供manifest
    # warming up with utterrances sampled from Librispeech
    #print('-----------------------------------------------------------')
    #print('Warming up ...')
    #warm_up_test(
    #    audio_process_handler=file_to_transcript,
    #    manifest_path=args.warmup_manifest,
    #    num_test_cases=3)
    #print('-----------------------------------------------------------')

**Comment by pkuyym** [comment]
看起来没什么问题，可能是训练数据本身的问题
```
Recognition Results: 我有时候真的
Start Recording ... Speech[length=229376] Sent.
Recognition Results: 那
Start Recording ... Speech[length=192512] Sent.
Recognition Results: 我啥事都
Start Recording ... Speech[length=135168] Sent.
Recognition Results: 我
Start Recording ... Speech[length=253952] Sent.
Recognition Results: 我还是
```

**Comment by harold-yh** [comment]
调整过，一样没有用。我现在尝试自己训练aishell的数据看下
不知道其它人有没有测试BaiduCN1.2k

**Comment by fedoral** [comment]
I Tried BaiduCN1.2k Model

## Change params 
```
# deploy/demo_client.py
def main():
    # prepare audio recorder
    p = pyaudio.PyAudio()
    stream = p.open(
        format=pyaudio.paInt32,
        channels=1,
        rate=8000,
        input=True,
        stream_callback=callback)
```

```
# deploy/demo_server.py 
file = wave.open(out_filename, 'wb')
file.setnchannels(1)
file.setsampwidth(4)
file.setframerate(8000)
file.writeframes(data)
file.close()
```

## The result
```
Received utterance[length=77824] from 127.0.0.1, saved to demo_cache/20180103060920_127.0.0.1.wav.
Response Time: 10.883582, Transcript: 今天是星期
Received utterance[length=131072] from 127.0.0.1, saved to demo_cache/20180103060939_127.0.0.1.wav.
Response Time: 18.083878, Transcript: 天朗气清惠风和畅春眠不觉晓
Received utterance[length=135168] from 127.0.0.1, saved to demo_cache/20180103061017_127.0.0.1.wav.
Response Time: 18.740344, Transcript: 轰炸机出现在太平洋
Received utterance[length=143360] from 127.0.0.1, saved to demo_cache/20180103061417_127.0.0.1.wav.
Response Time: 19.563584, Transcript: 我去买几个曲子你站在这里不要动了
Received utterance[length=98304] from 127.0.0.1, saved to demo_cache/20180103061443_127.0.0.1.wav.
Response Time: 13.369101, Transcript: 橘子和苹果哪个好吃的
```

**Comment by pkuyym** [comment]
@fedoral We have also noticed the phenomenon, and I think the main reason may be the training data. Model trained on Aishell seems working well.

**Comment by yyhlvdl** [comment]
hi,我也尝试了这个模型，用aishell文件的test进行warm up,然后报错：
alpha: 2.5
beam_size: 500
beta: 0.3
cutoff_prob: 1.0
cutoff_top_n: 40
decoding_method: ctc_beam_search
host_ip: localhost
host_port: 8086
lang_model_path: asset/lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: asset/preprocess/mean_std.npz
model_path: asset/checkpoints/params.tar.gz
num_conv_layers: 2
num_rnn_layers: 3
rnn_layer_size: 2048
share_rnn_weights: False
specgram_type: linear
speech_save_dir: asset/myspeech
use_gpu: False
use_gru: True
vocab_path: asset/vocab/vocab.txt
warmup_manifest: asset/preprocess/manifest.test
------------------------------------------------
I0103 16:24:39.946882 19095 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2018-01-03 16:24:40,074 layers.py:2689] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-03 16:24:40,075 layers.py:3251] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-03 16:24:40,075 layers.py:7411] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2018-01-03 16:24:40,075 layers.py:2689] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-01-03 16:24:40,076 layers.py:3251] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2018-01-03 16:24:40,076 layers.py:7411] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
-----------------------------------------------------------
Warming up ...
('Warm-up Test Case %d: %s', 0, u'asset/data/data_aishell/wav/train/S0722/BAC009S0722W0180.wav')
Traceback (most recent call last):
  File "deploy/demo_server.py", line 207, in <module>
    main()
  File "deploy/demo_server.py", line 203, in main
    start_server()
  File "deploy/demo_server.py", line 187, in start_server
    num_test_cases=3)
  File "deploy/demo_server.py", line 135, in warm_up_test
    transcript = audio_process_handler(sample['audio_filepath'])
  File "deploy/demo_server.py", line 178, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/home/yyh/Chi-Rec/deploy/../model_utils/model.py", line 228, in infer_batch
    output_layer=self._log_probs, parameters=self._parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___fc_layer_7__.w0

**Comment by harold-yh** [comment]
@fedoral 
能否提供一下data/tiny/manifest.test-clean测试下？
方便的话麻烦发一下我邮箱：lovethefeel@qq.com，谢谢
我用aishell在训练，还没完成。

**Comment by tangsipeng** [comment]
@fedoral  我看你跑的是 baidu_cn1.2k  ，而 warmup_manifest='data/tiny/manifest.test-clean'  ，不会出问题吗？一个中文模型用英文的 warmup ？

**Comment by sunjunlishi** [comment]
@fedoral你输出了，识别结果，识别的正确吗？效果怎么样

**Comment by sukibean163** [comment]
@pkuyym 问题解决了吗？

**Comment by VegetableWithChicken** [comment]
现在模型识别准确率大概多少
