### ISSUE TITLE
Installation issue on installing package - Install python dependencies failed !!!

### ISSUE THREAD

**Issue by vucuong12** [PaddlePaddle/DeepSpeech#95]
The setup.py file contains this line 
`pip install package -r requirements.txt `, which outputs the following error.
`

>   Downloading/unpacking package
>   Downloading package-0.1.1.tar.gz
>   Running setup.py (path:/tmp/pip_build_root/package/setup.py) egg_info for package package
>     
>     Greetings!
>     
>     It looks like you are trying to install this package (called `package`). STOP!
>     
>     package` is a set of tools to make Python packages easier to write and
>     maintain, and to make the resulting packages easier for their users to
>     install.
>     
>     If you are not a (possibly aspiring) Python package author, you can stop
>     
>     ...
>     
>     I'm glad you are still reading. You must be a (possibly aspiring) Python
>     package author. Good on you!
>     
>     To use this stuff either untar package-#.#.#.tar.gz (get it from
>     http://pypi.python.org/pypi/package/) or get/git the development sources
>     directly from http://github.com/ingydotnet/package-py. Put the `package`
>     directory under your src directory, next to the Python packages you are
>     authoring, and call it `package-py/`.
>     
>     Further instructions can be found at http://pypi.python.org/pypi/package/
>     
>     Enjoy!
>     
>     
> Cleaning up...
> No files/directories in /tmp/pip_build_root/package/pip-egg-info (from PKG-INFO)
> Storing debug log for failure in /home/koki/.pip/pip.log
> Install python dependencies failed !!!

It seems for the package _package_, we cannot install it via its setup.py, which causes `Install python dependencies failed !!!`. The [official doc](https://pypi.python.org/pypi/package/) said 

> DON’T INSTALL THIS PACKAGE (package)!!!
> 
> package isn’t meant to be installed like normal Python packages. It is meant to be copied and distributed as a part of other Python packages.
> 
> The best thing to do is to to git clone it from GitHub, and put it beside the other packages that you package for Python:
> 
> git clone git://github.com/ingydotnet/package-py.git
> 
> The second best thing to do is get the latest package-#.#.#.tar.gz from http://pypi.python.org/pypi/package/, untar it and rename the directory to package-py.

I am wondering whether you guys also follow this guideline to use the package _package_.

**Comment by kuke** [comment]
No. This line should be ```pip install -r requirements.txt``` and no ```package``` there. Please try to run setup by ```sh setup.sh``` directly.

**Comment by vucuong12** [comment]
It turns out that the `package' word was somehow put into that line accidentally in my local repository. Thanks :)
