### ISSUE TITLE
DeepSpeech 交流QQ群，欢迎加入共同交流学习

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#97]

**Comment by kuke** [comment]
我们建议大家有问题都在issue中直接提问，有利于问题的及时反馈与解决、也方便后来者查阅历史issue。除issue外我们暂无其它交流渠道、也不建议在issue下发布任何非官方的组织活动。

最后要感谢@witkeyshare 对DeepSpeech这个项目的支持！
